services:
  web:
    image: registry.lab.tcctech.app/obk/obk-wifi-auth-web/production:latest
    deploy:
      replicas: 3
    restart: always
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      # - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always
    networks:
      - webnet

networks:
  webnet: