package seeder

import (
	artCEntity "example.com/art-culture-api/domain/act_c/entity"
	"gorm.io/gorm"
)

func ArtCSeeder(db *gorm.DB) {
	var searchContent artCEntity.ArtCType
	db.First(&searchContent)

	if(searchContent.ID == 0) {
		artCItems := []artCEntity.ArtCType{
			{
				OrderType: 1,
				ModifyStrict: false,
				ArtCTranslation: []artCEntity.ArtCTranslation{
					{
						Locale: "th",
						Title: "The Wireless House One Bangkok",
						ShortDesc: "A mix of cultural learning space",
						Desc: "The Wireless Club is a mix of cultural learning space for first-time visitors, a seamless blend of cultural experience, lifestyle and leisure.",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469095584_bnlxboo.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469102177_mzqdy4.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "",
						PlaylistSectionTitle: "",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
					{
						Locale: "en",
						Title: "The Wireless House One Bangkok",
						ShortDesc: "A mix of cultural learning space",
						Desc: "The Wireless Club is a mix of cultural learning space for first-time visitors, a seamless blend of cultural experience, lifestyle and leisure.",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469095584_bnlxboo.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469102177_mzqdy4.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "",
						PlaylistSectionTitle: "",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
					{
						Locale: "zh",
						Title: "The Wireless House One Bangkok",
						ShortDesc: "A mix of cultural learning space",
						Desc: "The Wireless Club is a mix of cultural learning space for first-time visitors, a seamless blend of cultural experience, lifestyle and leisure.",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469095584_bnlxboo.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469102177_mzqdy4.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "",
						PlaylistSectionTitle: "",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
				},
			},
			{
				OrderType: 2,
				ModifyStrict: true,
				ArtCTranslation: []artCEntity.ArtCTranslation{
					{
						Locale: "th",
						Title: "The Wireless Club",
						ShortDesc: "Live broadcast streaming with diverse content communities",
						Desc: "The Wireless Club is a mix of cultural learning space for first-time visitors, a seamless blend of cultural experience, lifestyle and leisure.",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469230770_zw1y2r.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469237795_mggm6n.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "Discover",
						PlaylistSectionTitle: "Playlist",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
					{
						Locale: "en",
						Title: "The Wireless Club",
						ShortDesc: "Live broadcast streaming with diverse content communities",
						Desc: "The Wireless Club is a mix of cultural learning space for first-time visitors, a seamless blend of cultural experience, lifestyle and leisure.",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469230770_zw1y2r.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469237795_mggm6n.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "Discover",
						PlaylistSectionTitle: "Playlist",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
					{
						Locale: "zh",
						Title: "The Wireless Club",
						ShortDesc: "Live broadcast streaming with diverse content communities",
						Desc: "The Wireless Club is a mix of cultural learning space for first-time visitors, a seamless blend of cultural experience, lifestyle and leisure.",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469230770_zw1y2r.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469237795_mggm6n.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "Discover",
						PlaylistSectionTitle: "Playlist",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
				},
			},
			{
				OrderType: 3,
				ModifyStrict: false,
				ArtCTranslation: []artCEntity.ArtCTranslation{
					{
						Locale: "th",
						Title: "Public Art Collection",
						ShortDesc: "Created by both local and international artists",
						Desc: "The Public Art Collection consists of artworks created by both local and international artists to suit One Bangkok's public space, either indoor or outdoor, and private facilities that are accessible to specified target audiences.",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469632671_50xqu.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469636780_eh3x5c.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "",
						PlaylistSectionTitle: "",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
					{
						Locale: "en",
						Title: "Public Art Collection",
						ShortDesc: "Created by both local and international artists",
						Desc: "The Public Art Collection consists of artworks created by both local and international artists to suit One Bangkok's public space, either indoor or outdoor, and private facilities that are accessible to specified target audiences.",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469632671_50xqu.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469636780_eh3x5c.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "",
						PlaylistSectionTitle: "",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
					{
						Locale: "zh",
						Title: "Public Art Collection",
						ShortDesc: "Created by both local and international artists",
						Desc: "The Public Art Collection consists of artworks created by both local and international artists to suit One Bangkok's public space, either indoor or outdoor, and private facilities that are accessible to specified target audiences.",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469632671_50xqu.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469636780_eh3x5c.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "",
						PlaylistSectionTitle: "",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
				},
			},
			{
				OrderType: 4,
				ModifyStrict: false,
				ArtCTranslation: []artCEntity.ArtCTranslation{
					{
						Locale: "th",
						Title: "Art Gallery",
						ShortDesc: "A testing ground for creative ideas",
						Desc: "The Art Gallery is a multifaceted platform. It is a space for several topics to be told and challenged. A testing ground for creative ideas and opportunities, as well as a meeting hub for Bangkok's art community",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469784961_x81vtl.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469790820_t4aoagk.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "",
						PlaylistSectionTitle: "",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
					{
						Locale: "en",
						Title: "Art Gallery",
						ShortDesc: "A testing ground for creative ideas",
						Desc: "The Art Gallery is a multifaceted platform. It is a space for several topics to be told and challenged. A testing ground for creative ideas and opportunities, as well as a meeting hub for Bangkok's art community",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469784961_x81vtl.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469790820_t4aoagk.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "",
						PlaylistSectionTitle: "",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
					{
						Locale: "zh",
						Title: "Art Gallery",
						ShortDesc: "A testing ground for creative ideas",
						Desc: "The Art Gallery is a multifaceted platform. It is a space for several topics to be told and challenged. A testing ground for creative ideas and opportunities, as well as a meeting hub for Bangkok's art community",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469784961_x81vtl.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469790820_t4aoagk.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "",
						PlaylistSectionTitle: "",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
				},
			},
			{
				OrderType: 5,
				ModifyStrict: false,
				ArtCTranslation: []artCEntity.ArtCTranslation{
					{
						Locale: "th",
						Title: "Art Activities",
						ShortDesc: "",
						Desc: "The Art Activities at One Bangkok comprises of both signature art activity initiated by A&C and seasonal art activity for the district and each component in various scales.",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469915427_l4dj4g.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469909480_qd9adb.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "",
						PlaylistSectionTitle: "",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
					{
						Locale: "en",
						Title: "Art Activities",
						ShortDesc: "Art activity initiated by Art and Culture team",
						Desc: "The Art Activities at One Bangkok comprises of both signature art activity initiated by A&C and seasonal art activity for the district and each component in various scales.",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469915427_l4dj4g.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469909480_qd9adb.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "",
						PlaylistSectionTitle: "",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
					{
						Locale: "zh",
						Title: "Art Activities",
						ShortDesc: "Art activity initiated by Art and Culture team",
						Desc: "The Art Activities at One Bangkok comprises of both signature art activity initiated by A&C and seasonal art activity for the district and each component in various scales.",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469915427_l4dj4g.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728469909480_qd9adb.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "",
						PlaylistSectionTitle: "",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
				},
			},
			{
				OrderType: 6,
				ModifyStrict: false,
				ArtCTranslation: []artCEntity.ArtCTranslation{
					{
						Locale: "th",
						Title: "What is Art & Culture?",
						ShortDesc: "",
						Desc: "What is Artloop? of artworks created by both local and international artists to suit One Bangkok's public space, either indoor or accessible to specified target audiences.What is Artloop? of artworks created by both local and international artists to suit One Bangkok's public space, either indoor orWhat is Artloop? of artworks created by both local and international artists to suit One Bangkok's public space, either indoor",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728470323238_2vsoy6.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728470336202_x2kqmg.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "",
						PlaylistSectionTitle: "",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
					{
						Locale: "en",
						Title: "What is Art & Culture?",
						ShortDesc: "",
						Desc: "What is Artloop? of artworks created by both local and international artists to suit One Bangkok's public space, either indoor or accessible to specified target audiences.What is Artloop? of artworks created by both local and international artists to suit One Bangkok's public space, either indoor orWhat is Artloop? of artworks created by both local and international artists to suit One Bangkok's public space, either indoor",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728470323238_2vsoy6.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728470336202_x2kqmg.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "",
						PlaylistSectionTitle: "",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
					{
						Locale: "zh",
						Title: "What is Art & Culture?",
						ShortDesc: "",
						Desc: "What is Artloop? of artworks created by both local and international artists to suit One Bangkok's public space, either indoor or accessible to specified target audiences.What is Artloop? of artworks created by both local and international artists to suit One Bangkok's public space, either indoor orWhat is Artloop? of artworks created by both local and international artists to suit One Bangkok's public space, either indoor",
						Thumbnail: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728470323238_2vsoy6.png",
						Banner: "https://obk-dev-image.s3.ap-southeast-1.amazonaws.com/1728470336202_x2kqmg.png",
						OpeningHours: []string{},
						Locations: []string{},
						CategorySectionTitle: "",
						PlaylistSectionTitle: "",
						ProgramSectionTitle: "Programs",
						EnterFee: 0,
						ExternalLink: "",
						Tags: []string{},
					},
				},
			},
		}

		for _, artCItem := range artCItems {
			db.Create(&artCItem)
		}
	}
}