version: "3.4"

services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass $$REDIS_PASSWORD
    ports:
      - "6379:6379"
    container_name: redis
    environment:
      - REDIS_PASSWORD=yourpassword
  obk-art-culture-api:
    container_name: prod-obk-art-culture-api
    image: registry.lab.tcctech.app/obk/obk-art-culture-api:production
    environment:
      - ENV=Prod
      - SERVER.PORT=0.0.0.0:8080
      - APP_URL=xx
      - OBK_S3_URL=xx
      - DATASOURCE_USERNAME=xx
      - DATASOURCE_PASSWORD=xx
      - DATASOURCE_HOST=xx
      - DATASOURCE_PORT=xxx
      - DATASOURCE_DB_NAME=xxx
      - DATASOURCE_POOL_MAX_CONN=xx
      - DATASOURCE_POOL_IDLE_CONN=xx
      - DATASOURCE_POOL_LIFE_TIME=xxx
      - JWT_SECRET_KEY=xxx
      - JWT_EXPIRE_MINUTES_COUNT=xxx
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=yourpassword
      - REDIS_POOL_MAX_SIZE=10
      - TZ="Asia/Bangkok"
    ports:
      - "80:8080"
    networks:
      - prod-obk-art-culture-api
    restart: always

networks:
  prod-obk-art-culture-api:
    name: prod-obk-art-culture-api
    driver: bridge
