apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base

commonLabels:
  app: ob-ws
  
namePrefix: ob-ws-

patches:
- patch: |-
    - op: replace
      path: /stringData/url
      value: https://github.com/mtel-thailand/one-bangkok
  target:
    kind: Secret
