export const COUNTRY_CODE_LIST = [
  {
    name: 'Thailand',
    flag: '🇹🇭',
    code: 'TH',
    dial_code: '+66',
  },
  {
    name: 'Afghanistan',
    flag: '🇦🇫',
    code: 'AF',
    dial_code: '+93',
  },
  {
    name: 'Åland Islands',
    flag: '🇦🇽',
    code: 'AX',
    dial_code: '+358',
  },
  {
    name: 'Albania',
    flag: '🇦🇱',
    code: 'AL',
    dial_code: '+355',
  },
  {
    name: 'Algeria',
    flag: '🇩🇿',
    code: 'DZ',
    dial_code: '+213',
  },
  {
    name: 'American Samoa',
    flag: '🇦🇸',
    code: 'AS',
    dial_code: '+1684',
  },
  {
    name: 'Andorra',
    flag: '🇦🇩',
    code: 'AD',
    dial_code: '+376',
  },
  {
    name: 'Angola',
    flag: '🇦🇴',
    code: 'AO',
    dial_code: '+244',
  },
  {
    name: 'Anguilla',
    flag: '🇦🇮',
    code: 'AI',
    dial_code: '+1264',
  },
  {
    name: 'Antarctica',
    flag: '🇦🇶',
    code: 'AQ',
    dial_code: '+672',
  },
  {
    name: 'Antigua and Barbuda',
    flag: '🇦🇬',
    code: 'AG',
    dial_code: '+1268',
  },
  {
    name: 'Argentina',
    flag: '🇦🇷',
    code: 'AR',
    dial_code: '+54',
  },
  {
    name: 'Armenia',
    flag: '🇦🇲',
    code: 'AM',
    dial_code: '+374',
  },
  {
    name: 'Aruba',
    flag: '🇦🇼',
    code: 'AW',
    dial_code: '+297',
  },
  {
    name: 'Australia',
    flag: '🇦🇺',
    code: 'AU',
    dial_code: '+61',
  },
  {
    name: 'Austria',
    flag: '🇦🇹',
    code: 'AT',
    dial_code: '+43',
  },
  {
    name: 'Azerbaijan',
    flag: '🇦🇿',
    code: 'AZ',
    dial_code: '+994',
  },
  {
    name: 'Bahamas',
    flag: '🇧🇸',
    code: 'BS',
    dial_code: '+1242',
  },
  {
    name: 'Bahrain',
    flag: '🇧🇭',
    code: 'BH',
    dial_code: '+973',
  },
  {
    name: 'Bangladesh',
    flag: '🇧🇩',
    code: 'BD',
    dial_code: '+880',
  },
  {
    name: 'Barbados',
    flag: '🇧🇧',
    code: 'BB',
    dial_code: '+1246',
  },
  {
    name: 'Belarus',
    flag: '🇧🇾',
    code: 'BY',
    dial_code: '+375',
  },
  {
    name: 'Belgium',
    flag: '🇧🇪',
    code: 'BE',
    dial_code: '+32',
  },
  {
    name: 'Belize',
    flag: '🇧🇿',
    code: 'BZ',
    dial_code: '+501',
  },
  {
    name: 'Benin',
    flag: '🇧🇯',
    code: 'BJ',
    dial_code: '+229',
  },
  {
    name: 'Bermuda',
    flag: '🇧🇲',
    code: 'BM',
    dial_code: '+1441',
  },
  {
    name: 'Bhutan',
    flag: '🇧🇹',
    code: 'BT',
    dial_code: '+975',
  },
  {
    name: 'Bolivia, Plurinational State of bolivia',
    flag: '🇧🇴',
    code: 'BO',
    dial_code: '+591',
  },
  {
    name: 'Bosnia and Herzegovina',
    flag: '🇧🇦',
    code: 'BA',
    dial_code: '+387',
  },
  {
    name: 'Botswana',
    flag: '🇧🇼',
    code: 'BW',
    dial_code: '+267',
  },
  {
    name: 'Bouvet Island',
    flag: '🇧🇻',
    code: 'BV',
    dial_code: '+47',
  },
  {
    name: 'Brazil',
    flag: '🇧🇷',
    code: 'BR',
    dial_code: '+55',
  },
  {
    name: 'British Indian Ocean Territory',
    flag: '🇮🇴',
    code: 'IO',
    dial_code: '+246',
  },
  {
    name: 'Brunei Darussalam',
    flag: '🇧🇳',
    code: 'BN',
    dial_code: '+673',
  },
  {
    name: 'Bulgaria',
    flag: '🇧🇬',
    code: 'BG',
    dial_code: '+359',
  },
  {
    name: 'Burkina Faso',
    flag: '🇧🇫',
    code: 'BF',
    dial_code: '+226',
  },
  {
    name: 'Burundi',
    flag: '🇧🇮',
    code: 'BI',
    dial_code: '+257',
  },
  {
    name: 'Cambodia',
    flag: '🇰🇭',
    code: 'KH',
    dial_code: '+855',
  },
  {
    name: 'Cameroon',
    flag: '🇨🇲',
    code: 'CM',
    dial_code: '+237',
  },
  {
    name: 'Canada',
    flag: '🇨🇦',
    code: 'CA',
    dial_code: '+1',
  },
  {
    name: 'Cape Verde',
    flag: '🇨🇻',
    code: 'CV',
    dial_code: '+238',
  },
  {
    name: 'Cayman Islands',
    flag: '🇰🇾',
    code: 'KY',
    dial_code: '+345',
  },
  {
    name: 'Central African Republic',
    flag: '🇨🇫',
    code: 'CF',
    dial_code: '+236',
  },
  {
    name: 'Chad',
    flag: '🇹🇩',
    code: 'TD',
    dial_code: '+235',
  },
  {
    name: 'Chile',
    flag: '🇨🇱',
    code: 'CL',
    dial_code: '+56',
  },
  {
    name: 'China',
    flag: '🇨🇳',
    code: 'CN',
    dial_code: '+86',
  },
  {
    name: 'Christmas Island',
    flag: '🇨🇽',
    code: 'CX',
    dial_code: '+61',
  },
  {
    name: 'Cocos (Keeling) Islands',
    flag: '🇨🇨',
    code: 'CC',
    dial_code: '+61',
  },
  {
    name: 'Colombia',
    flag: '🇨🇴',
    code: 'CO',
    dial_code: '+57',
  },
  {
    name: 'Comoros',
    flag: '🇰🇲',
    code: 'KM',
    dial_code: '+269',
  },
  {
    name: 'Congo',
    flag: '🇨🇬',
    code: 'CG',
    dial_code: '+242',
  },
  {
    name: 'Congo, The Democratic Republic of the Congo',
    flag: '🇨🇩',
    code: 'CD',
    dial_code: '+243',
  },
  {
    name: 'Cook Islands',
    flag: '🇨🇰',
    code: 'CK',
    dial_code: '+682',
  },
  {
    name: 'Costa Rica',
    flag: '🇨🇷',
    code: 'CR',
    dial_code: '+506',
  },
  {
    name: "Cote d'Ivoire",
    flag: '🇨🇮',
    code: 'CI',
    dial_code: '+225',
  },
  {
    name: 'Croatia',
    flag: '🇭🇷',
    code: 'HR',
    dial_code: '+385',
  },
  {
    name: 'Cuba',
    flag: '🇨🇺',
    code: 'CU',
    dial_code: '+53',
  },
  {
    name: 'Cyprus',
    flag: '🇨🇾',
    code: 'CY',
    dial_code: '+357',
  },
  {
    name: 'Czech Republic',
    flag: '🇨🇿',
    code: 'CZ',
    dial_code: '+420',
  },
  {
    name: 'Denmark',
    flag: '🇩🇰',
    code: 'DK',
    dial_code: '+45',
  },
  {
    name: 'Djibouti',
    flag: '🇩🇯',
    code: 'DJ',
    dial_code: '+253',
  },
  {
    name: 'Dominica',
    flag: '🇩🇲',
    code: 'DM',
    dial_code: '+1767',
  },
  {
    name: 'Dominican Republic',
    flag: '🇩🇴',
    code: 'DO',
    dial_code: '+1849',
  },
  {
    name: 'Ecuador',
    flag: '🇪🇨',
    code: 'EC',
    dial_code: '+593',
  },
  {
    name: 'Egypt',
    flag: '🇪🇬',
    code: 'EG',
    dial_code: '+20',
  },
  {
    name: 'El Salvador',
    flag: '🇸🇻',
    code: 'SV',
    dial_code: '+503',
  },
  {
    name: 'Equatorial Guinea',
    flag: '🇬🇶',
    code: 'GQ',
    dial_code: '+240',
  },
  {
    name: 'Eritrea',
    flag: '🇪🇷',
    code: 'ER',
    dial_code: '+291',
  },
  {
    name: 'Estonia',
    flag: '🇪🇪',
    code: 'EE',
    dial_code: '+372',
  },
  {
    name: 'Ethiopia',
    flag: '🇪🇹',
    code: 'ET',
    dial_code: '+251',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    flag: '🇫🇰',
    code: 'FK',
    dial_code: '+500',
  },
  {
    name: 'Faroe Islands',
    flag: '🇫🇴',
    code: 'FO',
    dial_code: '+298',
  },
  {
    name: 'Fiji',
    flag: '🇫🇯',
    code: 'FJ',
    dial_code: '+679',
  },
  {
    name: 'Finland',
    flag: '🇫🇮',
    code: 'FI',
    dial_code: '+358',
  },
  {
    name: 'France',
    flag: '🇫🇷',
    code: 'FR',
    dial_code: '+33',
  },
  {
    name: 'French Guiana',
    flag: '🇬🇫',
    code: 'GF',
    dial_code: '+594',
  },
  {
    name: 'French Polynesia',
    flag: '🇵🇫',
    code: 'PF',
    dial_code: '+689',
  },
  {
    name: 'French Southern Territories',
    flag: '🇹🇫',
    code: 'TF',
    dial_code: '+262',
  },
  {
    name: 'Gabon',
    flag: '🇬🇦',
    code: 'GA',
    dial_code: '+241',
  },
  {
    name: 'Gambia',
    flag: '🇬🇲',
    code: 'GM',
    dial_code: '+220',
  },
  {
    name: 'Georgia',
    flag: '🇬🇪',
    code: 'GE',
    dial_code: '+995',
  },
  {
    name: 'Germany',
    flag: '🇩🇪',
    code: 'DE',
    dial_code: '+49',
  },
  {
    name: 'Ghana',
    flag: '🇬🇭',
    code: 'GH',
    dial_code: '+233',
  },
  {
    name: 'Gibraltar',
    flag: '🇬🇮',
    code: 'GI',
    dial_code: '+350',
  },
  {
    name: 'Greece',
    flag: '🇬🇷',
    code: 'GR',
    dial_code: '+30',
  },
  {
    name: 'Greenland',
    flag: '🇬🇱',
    code: 'GL',
    dial_code: '+299',
  },
  {
    name: 'Grenada',
    flag: '🇬🇩',
    code: 'GD',
    dial_code: '+1473',
  },
  {
    name: 'Guadeloupe',
    flag: '🇬🇵',
    code: 'GP',
    dial_code: '+590',
  },
  {
    name: 'Guam',
    flag: '🇬🇺',
    code: 'GU',
    dial_code: '+1671',
  },
  {
    name: 'Guatemala',
    flag: '🇬🇹',
    code: 'GT',
    dial_code: '+502',
  },
  {
    name: 'Guernsey',
    flag: '🇬🇬',
    code: 'GG',
    dial_code: '+44',
  },
  {
    name: 'Guinea',
    flag: '🇬🇳',
    code: 'GN',
    dial_code: '+224',
  },
  {
    name: 'Guinea-Bissau',
    flag: '🇬🇼',
    code: 'GW',
    dial_code: '+245',
  },
  {
    name: 'Guyana',
    flag: '🇬🇾',
    code: 'GY',
    dial_code: '+592',
  },
  {
    name: 'Haiti',
    flag: '🇭🇹',
    code: 'HT',
    dial_code: '+509',
  },
  {
    name: 'Heard Island and Mcdonald Islands',
    flag: '🇭🇲',
    code: 'HM',
    dial_code: '+672',
  },
  {
    name: 'Holy See (Vatican City State)',
    flag: '🇻🇦',
    code: 'VA',
    dial_code: '+379',
  },
  {
    name: 'Honduras',
    flag: '🇭🇳',
    code: 'HN',
    dial_code: '+504',
  },
  {
    name: 'Hong Kong',
    flag: '🇭🇰',
    code: 'HK',
    dial_code: '+852',
  },
  {
    name: 'Hungary',
    flag: '🇭🇺',
    code: 'HU',
    dial_code: '+36',
  },
  {
    name: 'Iceland',
    flag: '🇮🇸',
    code: 'IS',
    dial_code: '+354',
  },
  {
    name: 'India',
    flag: '🇮🇳',
    code: 'IN',
    dial_code: '+91',
  },
  {
    name: 'Indonesia',
    flag: '🇮🇩',
    code: 'ID',
    dial_code: '+62',
  },
  {
    name: 'Iran, Islamic Republic of Persian Gulf',
    flag: '🇮🇷',
    code: 'IR',
    dial_code: '+98',
  },
  {
    name: 'Iraq',
    flag: '🇮🇶',
    code: 'IQ',
    dial_code: '+964',
  },
  {
    name: 'Ireland',
    flag: '🇮🇪',
    code: 'IE',
    dial_code: '+353',
  },
  {
    name: 'Isle of Man',
    flag: '🇮🇲',
    code: 'IM',
    dial_code: '+44',
  },
  {
    name: 'Israel',
    flag: '🇮🇱',
    code: 'IL',
    dial_code: '+972',
  },
  {
    name: 'Italy',
    flag: '🇮🇹',
    code: 'IT',
    dial_code: '+39',
  },
  {
    name: 'Jamaica',
    flag: '🇯🇲',
    code: 'JM',
    dial_code: '+1876',
  },
  {
    name: 'Japan',
    flag: '🇯🇵',
    code: 'JP',
    dial_code: '+81',
  },
  {
    name: 'Jersey',
    flag: '🇯🇪',
    code: 'JE',
    dial_code: '+44',
  },
  {
    name: 'Jordan',
    flag: '🇯🇴',
    code: 'JO',
    dial_code: '+962',
  },
  {
    name: 'Kazakhstan',
    flag: '🇰🇿',
    code: 'KZ',
    dial_code: '+7',
  },
  {
    name: 'Kenya',
    flag: '🇰🇪',
    code: 'KE',
    dial_code: '+254',
  },
  {
    name: 'Kiribati',
    flag: '🇰🇮',
    code: 'KI',
    dial_code: '+686',
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    flag: '🇰🇵',
    code: 'KP',
    dial_code: '+850',
  },
  {
    name: 'Korea, Republic of South Korea',
    flag: '🇰🇷',
    code: 'KR',
    dial_code: '+82',
  },
  {
    name: 'Kosovo',
    flag: '🇽🇰',
    code: 'XK',
    dial_code: '+383',
  },
  {
    name: 'Kuwait',
    flag: '🇰🇼',
    code: 'KW',
    dial_code: '+965',
  },
  {
    name: 'Kyrgyzstan',
    flag: '🇰🇬',
    code: 'KG',
    dial_code: '+996',
  },
  {
    name: 'Laos',
    flag: '🇱🇦',
    code: 'LA',
    dial_code: '+856',
  },
  {
    name: 'Latvia',
    flag: '🇱🇻',
    code: 'LV',
    dial_code: '+371',
  },
  {
    name: 'Lebanon',
    flag: '🇱🇧',
    code: 'LB',
    dial_code: '+961',
  },
  {
    name: 'Lesotho',
    flag: '🇱🇸',
    code: 'LS',
    dial_code: '+266',
  },
  {
    name: 'Liberia',
    flag: '🇱🇷',
    code: 'LR',
    dial_code: '+231',
  },
  {
    name: 'Libyan Arab Jamahiriya',
    flag: '🇱🇾',
    code: 'LY',
    dial_code: '+218',
  },
  {
    name: 'Liechtenstein',
    flag: '🇱🇮',
    code: 'LI',
    dial_code: '+423',
  },
  {
    name: 'Lithuania',
    flag: '🇱🇹',
    code: 'LT',
    dial_code: '+370',
  },
  {
    name: 'Luxembourg',
    flag: '🇱🇺',
    code: 'LU',
    dial_code: '+352',
  },
  {
    name: 'Macao',
    flag: '🇲🇴',
    code: 'MO',
    dial_code: '+853',
  },
  {
    name: 'Macedonia',
    flag: '🇲🇰',
    code: 'MK',
    dial_code: '+389',
  },
  {
    name: 'Madagascar',
    flag: '🇲🇬',
    code: 'MG',
    dial_code: '+261',
  },
  {
    name: 'Malawi',
    flag: '🇲🇼',
    code: 'MW',
    dial_code: '+265',
  },
  {
    name: 'Malaysia',
    flag: '🇲🇾',
    code: 'MY',
    dial_code: '+60',
  },
  {
    name: 'Maldives',
    flag: '🇲🇻',
    code: 'MV',
    dial_code: '+960',
  },
  {
    name: 'Mali',
    flag: '🇲🇱',
    code: 'ML',
    dial_code: '+223',
  },
  {
    name: 'Malta',
    flag: '🇲🇹',
    code: 'MT',
    dial_code: '+356',
  },
  {
    name: 'Marshall Islands',
    flag: '🇲🇭',
    code: 'MH',
    dial_code: '+692',
  },
  {
    name: 'Martinique',
    flag: '🇲🇶',
    code: 'MQ',
    dial_code: '+596',
  },
  {
    name: 'Mauritania',
    flag: '🇲🇷',
    code: 'MR',
    dial_code: '+222',
  },
  {
    name: 'Mauritius',
    flag: '🇲🇺',
    code: 'MU',
    dial_code: '+230',
  },
  {
    name: 'Mayotte',
    flag: '🇾🇹',
    code: 'YT',
    dial_code: '+262',
  },
  {
    name: 'Mexico',
    flag: '🇲🇽',
    code: 'MX',
    dial_code: '+52',
  },
  {
    name: 'Micronesia, Federated States of Micronesia',
    flag: '🇫🇲',
    code: 'FM',
    dial_code: '+691',
  },
  {
    name: 'Moldova',
    flag: '🇲🇩',
    code: 'MD',
    dial_code: '+373',
  },
  {
    name: 'Monaco',
    flag: '🇲🇨',
    code: 'MC',
    dial_code: '+377',
  },
  {
    name: 'Mongolia',
    flag: '🇲🇳',
    code: 'MN',
    dial_code: '+976',
  },
  {
    name: 'Montenegro',
    flag: '🇲🇪',
    code: 'ME',
    dial_code: '+382',
  },
  {
    name: 'Montserrat',
    flag: '🇲🇸',
    code: 'MS',
    dial_code: '+1664',
  },
  {
    name: 'Morocco',
    flag: '🇲🇦',
    code: 'MA',
    dial_code: '+212',
  },
  {
    name: 'Mozambique',
    flag: '🇲🇿',
    code: 'MZ',
    dial_code: '+258',
  },
  {
    name: 'Myanmar',
    flag: '🇲🇲',
    code: 'MM',
    dial_code: '+95',
  },
  {
    name: 'Namibia',
    flag: '🇳🇦',
    code: 'NA',
    dial_code: '+264',
  },
  {
    name: 'Nauru',
    flag: '🇳🇷',
    code: 'NR',
    dial_code: '+674',
  },
  {
    name: 'Nepal',
    flag: '🇳🇵',
    code: 'NP',
    dial_code: '+977',
  },
  {
    name: 'Netherlands',
    flag: '🇳🇱',
    code: 'NL',
    dial_code: '+31',
  },
  {
    name: 'Netherlands Antilles',
    flag: '',
    code: 'AN',
    dial_code: '+599',
  },
  {
    name: 'New Caledonia',
    flag: '🇳🇨',
    code: 'NC',
    dial_code: '+687',
  },
  {
    name: 'New Zealand',
    flag: '🇳🇿',
    code: 'NZ',
    dial_code: '+64',
  },
  {
    name: 'Nicaragua',
    flag: '🇳🇮',
    code: 'NI',
    dial_code: '+505',
  },
  {
    name: 'Niger',
    flag: '🇳🇪',
    code: 'NE',
    dial_code: '+227',
  },
  {
    name: 'Nigeria',
    flag: '🇳🇬',
    code: 'NG',
    dial_code: '+234',
  },
  {
    name: 'Niue',
    flag: '🇳🇺',
    code: 'NU',
    dial_code: '+683',
  },
  {
    name: 'Norfolk Island',
    flag: '🇳🇫',
    code: 'NF',
    dial_code: '+672',
  },
  {
    name: 'Northern Mariana Islands',
    flag: '🇲🇵',
    code: 'MP',
    dial_code: '+1670',
  },
  {
    name: 'Norway',
    flag: '🇳🇴',
    code: 'NO',
    dial_code: '+47',
  },
  {
    name: 'Oman',
    flag: '🇴🇲',
    code: 'OM',
    dial_code: '+968',
  },
  {
    name: 'Pakistan',
    flag: '🇵🇰',
    code: 'PK',
    dial_code: '+92',
  },
  {
    name: 'Palau',
    flag: '🇵🇼',
    code: 'PW',
    dial_code: '+680',
  },
  {
    name: 'Palestinian Territory, Occupied',
    flag: '🇵🇸',
    code: 'PS',
    dial_code: '+970',
  },
  {
    name: 'Panama',
    flag: '🇵🇦',
    code: 'PA',
    dial_code: '+507',
  },
  {
    name: 'Papua New Guinea',
    flag: '🇵🇬',
    code: 'PG',
    dial_code: '+675',
  },
  {
    name: 'Paraguay',
    flag: '🇵🇾',
    code: 'PY',
    dial_code: '+595',
  },
  {
    name: 'Peru',
    flag: '🇵🇪',
    code: 'PE',
    dial_code: '+51',
  },
  {
    name: 'Philippines',
    flag: '🇵🇭',
    code: 'PH',
    dial_code: '+63',
  },
  {
    name: 'Pitcairn',
    flag: '🇵🇳',
    code: 'PN',
    dial_code: '+64',
  },
  {
    name: 'Poland',
    flag: '🇵🇱',
    code: 'PL',
    dial_code: '+48',
  },
  {
    name: 'Portugal',
    flag: '🇵🇹',
    code: 'PT',
    dial_code: '+351',
  },
  {
    name: 'Puerto Rico',
    flag: '🇵🇷',
    code: 'PR',
    dial_code: '+1939',
  },
  {
    name: 'Qatar',
    flag: '🇶🇦',
    code: 'QA',
    dial_code: '+974',
  },
  {
    name: 'Romania',
    flag: '🇷🇴',
    code: 'RO',
    dial_code: '+40',
  },
  {
    name: 'Russia',
    flag: '🇷🇺',
    code: 'RU',
    dial_code: '+7',
  },
  {
    name: 'Rwanda',
    flag: '🇷🇼',
    code: 'RW',
    dial_code: '+250',
  },
  {
    name: 'Reunion',
    flag: '🇷🇪',
    code: 'RE',
    dial_code: '+262',
  },
  {
    name: 'Saint Barthelemy',
    flag: '🇧🇱',
    code: 'BL',
    dial_code: '+590',
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    flag: '🇸🇭',
    code: 'SH',
    dial_code: '+290',
  },
  {
    name: 'Saint Kitts and Nevis',
    flag: '🇰🇳',
    code: 'KN',
    dial_code: '+1869',
  },
  {
    name: 'Saint Lucia',
    flag: '🇱🇨',
    code: 'LC',
    dial_code: '+1758',
  },
  {
    name: 'Saint Martin',
    flag: '🇲🇫',
    code: 'MF',
    dial_code: '+590',
  },
  {
    name: 'Saint Pierre and Miquelon',
    flag: '🇵🇲',
    code: 'PM',
    dial_code: '+508',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    flag: '🇻🇨',
    code: 'VC',
    dial_code: '+1784',
  },
  {
    name: 'Samoa',
    flag: '🇼🇸',
    code: 'WS',
    dial_code: '+685',
  },
  {
    name: 'San Marino',
    flag: '🇸🇲',
    code: 'SM',
    dial_code: '+378',
  },
  {
    name: 'Sao Tome and Principe',
    flag: '🇸🇹',
    code: 'ST',
    dial_code: '+239',
  },
  {
    name: 'Saudi Arabia',
    flag: '🇸🇦',
    code: 'SA',
    dial_code: '+966',
  },
  {
    name: 'Senegal',
    flag: '🇸🇳',
    code: 'SN',
    dial_code: '+221',
  },
  {
    name: 'Serbia',
    flag: '🇷🇸',
    code: 'RS',
    dial_code: '+381',
  },
  {
    name: 'Seychelles',
    flag: '🇸🇨',
    code: 'SC',
    dial_code: '+248',
  },
  {
    name: 'Sierra Leone',
    flag: '🇸🇱',
    code: 'SL',
    dial_code: '+232',
  },
  {
    name: 'Singapore',
    flag: '🇸🇬',
    code: 'SG',
    dial_code: '+65',
  },
  {
    name: 'Slovakia',
    flag: '🇸🇰',
    code: 'SK',
    dial_code: '+421',
  },
  {
    name: 'Slovenia',
    flag: '🇸🇮',
    code: 'SI',
    dial_code: '+386',
  },
  {
    name: 'Solomon Islands',
    flag: '🇸🇧',
    code: 'SB',
    dial_code: '+677',
  },
  {
    name: 'Somalia',
    flag: '🇸🇴',
    code: 'SO',
    dial_code: '+252',
  },
  {
    name: 'South Africa',
    flag: '🇿🇦',
    code: 'ZA',
    dial_code: '+27',
  },
  {
    name: 'South Sudan',
    flag: '🇸🇸',
    code: 'SS',
    dial_code: '+211',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    flag: '🇬🇸',
    code: 'GS',
    dial_code: '+500',
  },
  {
    name: 'Spain',
    flag: '🇪🇸',
    code: 'ES',
    dial_code: '+34',
  },
  {
    name: 'Sri Lanka',
    flag: '🇱🇰',
    code: 'LK',
    dial_code: '+94',
  },
  {
    name: 'Sudan',
    flag: '🇸🇩',
    code: 'SD',
    dial_code: '+249',
  },
  {
    name: 'Suriname',
    flag: '🇸🇷',
    code: 'SR',
    dial_code: '+597',
  },
  {
    name: 'Svalbard and Jan Mayen',
    flag: '🇸🇯',
    code: 'SJ',
    dial_code: '+47',
  },
  {
    name: 'Swaziland',
    flag: '🇸🇿',
    code: 'SZ',
    dial_code: '+268',
  },
  {
    name: 'Sweden',
    flag: '🇸🇪',
    code: 'SE',
    dial_code: '+46',
  },
  {
    name: 'Switzerland',
    flag: '🇨🇭',
    code: 'CH',
    dial_code: '+41',
  },
  {
    name: 'Syrian Arab Republic',
    flag: '🇸🇾',
    code: 'SY',
    dial_code: '+963',
  },
  {
    name: 'Taiwan',
    flag: '🇹🇼',
    code: 'TW',
    dial_code: '+886',
  },
  {
    name: 'Tajikistan',
    flag: '🇹🇯',
    code: 'TJ',
    dial_code: '+992',
  },
  {
    name: 'Tanzania, United Republic of Tanzania',
    flag: '🇹🇿',
    code: 'TZ',
    dial_code: '+255',
  },
  {
    name: 'Thailand',
    flag: '🇹🇭',
    code: 'TH',
    dial_code: '+66',
  },
  {
    name: 'Timor-Leste',
    flag: '🇹🇱',
    code: 'TL',
    dial_code: '+670',
  },
  {
    name: 'Togo',
    flag: '🇹🇬',
    code: 'TG',
    dial_code: '+228',
  },
  {
    name: 'Tokelau',
    flag: '🇹🇰',
    code: 'TK',
    dial_code: '+690',
  },
  {
    name: 'Tonga',
    flag: '🇹🇴',
    code: 'TO',
    dial_code: '+676',
  },
  {
    name: 'Trinidad and Tobago',
    flag: '🇹🇹',
    code: 'TT',
    dial_code: '+1868',
  },
  {
    name: 'Tunisia',
    flag: '🇹🇳',
    code: 'TN',
    dial_code: '+216',
  },
  {
    name: 'Turkey',
    flag: '🇹🇷',
    code: 'TR',
    dial_code: '+90',
  },
  {
    name: 'Turkmenistan',
    flag: '🇹🇲',
    code: 'TM',
    dial_code: '+993',
  },
  {
    name: 'Turks and Caicos Islands',
    flag: '🇹🇨',
    code: 'TC',
    dial_code: '+1649',
  },
  {
    name: 'Tuvalu',
    flag: '🇹🇻',
    code: 'TV',
    dial_code: '+688',
  },
  {
    name: 'Uganda',
    flag: '🇺🇬',
    code: 'UG',
    dial_code: '+256',
  },
  {
    name: 'Ukraine',
    flag: '🇺🇦',
    code: 'UA',
    dial_code: '+380',
  },
  {
    name: 'United Arab Emirates',
    flag: '🇦🇪',
    code: 'AE',
    dial_code: '+971',
  },
  {
    name: 'United Kingdom',
    flag: '🇬🇧',
    code: 'GB',
    dial_code: '+44',
  },
  {
    name: 'United States',
    flag: '🇺🇸',
    code: 'US',
    dial_code: '+1',
  },
  {
    name: 'Uruguay',
    flag: '🇺🇾',
    code: 'UY',
    dial_code: '+598',
  },
  {
    name: 'Uzbekistan',
    flag: '🇺🇿',
    code: 'UZ',
    dial_code: '+998',
  },
  {
    name: 'Vanuatu',
    flag: '🇻🇺',
    code: 'VU',
    dial_code: '+678',
  },
  {
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    flag: '🇻🇪',
    code: 'VE',
    dial_code: '+58',
  },
  {
    name: 'Vietnam',
    flag: '🇻🇳',
    code: 'VN',
    dial_code: '+84',
  },
  {
    name: 'Virgin Islands, British',
    flag: '🇻🇬',
    code: 'VG',
    dial_code: '+1284',
  },
  {
    name: 'Virgin Islands, U.S.',
    flag: '🇻🇮',
    code: 'VI',
    dial_code: '+1340',
  },
  {
    name: 'Wallis and Futuna',
    flag: '🇼🇫',
    code: 'WF',
    dial_code: '+681',
  },
  {
    name: 'Yemen',
    flag: '🇾🇪',
    code: 'YE',
    dial_code: '+967',
  },
  {
    name: 'Zambia',
    flag: '🇿🇲',
    code: 'ZM',
    dial_code: '+260',
  },
  {
    name: 'Zimbabwe',
    flag: '🇿🇼',
    code: 'ZW',
    dial_code: '+263',
  },
];

export const DEFAULT_COUNTRY_CODE = COUNTRY_CODE_LIST[0].dial_code;

export const COUNTRY_CODE_LISTS = [
  {
    name: {en: 'Thailand', th: 'ไทย', cs: '泰国'},
    flag: '🇹🇭',
    code: 'TH',
    dial_code: '+66',
  },
  {
    name: {en: 'Afghanistan', th: 'อัฟกานิสถาน', cs: '阿富汗'},
    flag: '🇦🇫',
    code: 'AF',
    dial_code: '+93',
  },
  {
    name: {en: 'Åland Islands', th: 'หมู่เกาะอาแลนด์', cs: '奥兰群岛'},
    flag: '🇦🇽',
    code: 'AX',
    dial_code: '+358',
  },
  {
    name: {en: 'Albania', th: 'แอลเบเนีย', cs: '阿尔巴尼亚'},
    flag: '🇦🇱',
    code: 'AL',
    dial_code: '+355',
  },
  {
    name: {en: 'Algeria', th: 'อัลจีเรีย', cs: '阿尔及利亚'},
    flag: '🇩🇿',
    code: 'DZ',
    dial_code: '+213',
  },
  {
    name: {en: 'American Samoa', th: 'อเมริกันซามัว', cs: '美属萨摩亚'},
    flag: '🇦🇸',
    code: 'AS',
    dial_code: '+1684',
  },
  {
    name: {en: 'Andorra', th: 'อันดอร์รา', cs: '安道尔'},
    flag: '🇦🇩',
    code: 'AD',
    dial_code: '+376',
  },
  {
    name: {en: 'Angola', th: 'แองโกลา', cs: '安哥拉'},
    flag: '🇦🇴',
    code: 'AO',
    dial_code: '+244',
  },
  {
    name: {en: 'Anguilla', th: 'แองกวิลลา', cs: '安圭拉'},
    flag: '🇦🇮',
    code: 'AI',
    dial_code: '+1264',
  },
  {
    name: {en: 'Antarctica', th: 'แอนตาร์กติกา', cs: '南极洲'},
    flag: '🇦🇶',
    code: 'AQ',
    dial_code: '+672',
  },
  {
    name: {
      en: 'Antigua and Barbuda',
      th: 'แอนติกาและบาร์บูดา',
      cs: '安提瓜和巴布达',
    },
    flag: '🇦🇬',
    code: 'AG',
    dial_code: '+1268',
  },
  {
    name: {en: 'Argentina', th: 'อาร์เจนตินา', cs: '阿根廷'},
    flag: '🇦🇷',
    code: 'AR',
    dial_code: '+54',
  },
  {
    name: {en: 'Armenia', th: 'อาร์เมเนีย', cs: '亚美尼亚'},
    flag: '🇦🇲',
    code: 'AM',
    dial_code: '+374',
  },
  {
    name: {en: 'Aruba', th: 'อารูบา', cs: '阿鲁巴'},
    flag: '🇦🇼',
    code: 'AW',
    dial_code: '+297',
  },
  {
    name: {en: 'Australia', th: 'ออสเตรเลีย', cs: '澳大利亚'},
    flag: '🇦🇺',
    code: 'AU',
    dial_code: '+61',
  },
  {
    name: {en: 'Austria', th: 'ออสเตรีย', cs: '奥地利'},
    flag: '🇦🇹',
    code: 'AT',
    dial_code: '+43',
  },
  {
    name: {en: 'Azerbaijan', th: 'อาเซอร์ไบจาน', cs: '阿塞拜疆'},
    flag: '🇦🇿',
    code: 'AZ',
    dial_code: '+994',
  },
  {
    name: {en: 'Bahamas', th: 'บาฮามาส', cs: '巴哈马'},
    flag: '🇧🇸',
    code: 'BS',
    dial_code: '+1242',
  },
  {
    name: {en: 'Bahrain', th: 'บาห์เรน', cs: '巴林'},
    flag: '🇧🇭',
    code: 'BH',
    dial_code: '+973',
  },
  {
    name: {en: 'Bangladesh', th: 'บังกลาเทศ', cs: '孟加拉国'},
    flag: '🇧🇩',
    code: 'BD',
    dial_code: '+880',
  },
  {
    name: {en: 'Barbados', th: 'บาร์เบโดส', cs: '巴巴多斯'},
    flag: '🇧🇧',
    code: 'BB',
    dial_code: '+1246',
  },
  {
    name: {en: 'Belarus', th: 'เบลารุส', cs: '白俄罗斯'},
    flag: '🇧🇾',
    code: 'BY',
    dial_code: '+375',
  },
  {
    name: {en: 'Belgium', th: 'เบลเยียม', cs: '比利时'},
    flag: '🇧🇪',
    code: 'BE',
    dial_code: '+32',
  },
  {
    name: {en: 'Belize', th: 'เบลีซ', cs: '伯利兹'},
    flag: '🇧🇿',
    code: 'BZ',
    dial_code: '+501',
  },
  {
    name: {en: 'Benin', th: 'เบนิน', cs: '贝宁'},
    flag: '🇧🇯',
    code: 'BJ',
    dial_code: '+229',
  },
  {
    name: {en: 'Bermuda', th: 'เบอร์มิวดา', cs: '百慕大'},
    flag: '🇧🇲',
    code: 'BM',
    dial_code: '+1441',
  },
  {
    name: {en: 'Bhutan', th: 'ภูฏาน', cs: '不丹'},
    flag: '🇧🇹',
    code: 'BT',
    dial_code: '+975',
  },
  {
    name: {
      en: 'Bolivia, Plurinational State of Bolivia',
      th: 'โบลิเวีย',
      cs: '玻利维亚',
    },
    flag: '🇧🇴',
    code: 'BO',
    dial_code: '+591',
  },
  {
    name: {
      en: 'Bosnia and Herzegovina',
      th: 'บอสเนียและเฮอร์เซโกวีนา',
      cs: '波斯尼亚和黑塞哥维那',
    },
    flag: '🇧🇦',
    code: 'BA',
    dial_code: '+387',
  },
  {
    name: {en: 'Botswana', th: 'บอตสวานา', cs: '博茨瓦纳'},
    flag: '🇧🇼',
    code: 'BW',
    dial_code: '+267',
  },
  {
    name: {en: 'Bouvet Island', th: 'เกาะบูเว', cs: '布韦岛'},
    flag: '🇧🇻',
    code: 'BV',
    dial_code: '+47',
  },
  {
    name: {en: 'Brazil', th: 'บราซิล', cs: '巴西'},
    flag: '🇧🇷',
    code: 'BR',
    dial_code: '+55',
  },
  {
    name: {
      en: 'British Indian Ocean Territory',
      th: 'บริติชอินเดียนโอเชียนเทร์ริทอรี',
      cs: '英属印度洋领地',
    },
    flag: '🇮🇴',
    code: 'IO',
    dial_code: '+246',
  },
  {
    name: {en: 'Brunei Darussalam', th: 'บรูไน', cs: '文莱'},
    flag: '🇧🇳',
    code: 'BN',
    dial_code: '+673',
  },
  {
    name: {en: 'Bulgaria', th: 'บัลแกเรีย', cs: '保加利亚'},
    flag: '🇧🇬',
    code: 'BG',
    dial_code: '+359',
  },
  {
    name: {en: 'Burkina Faso', th: 'บูร์กินาฟาโซ', cs: '布基纳法索'},
    flag: '🇧🇫',
    code: 'BF',
    dial_code: '+226',
  },
  {
    name: {en: 'Burundi', th: 'บุรุนดี', cs: '布隆迪'},
    flag: '🇧🇮',
    code: 'BI',
    dial_code: '+257',
  },
  {
    name: {en: 'Cambodia', th: 'กัมพูชา', cs: '柬埔寨'},
    flag: '🇰🇭',
    code: 'KH',
    dial_code: '+855',
  },
  {
    name: {en: 'Cameroon', th: 'แคเมอรูน', cs: '喀麦隆'},
    flag: '🇨🇲',
    code: 'CM',
    dial_code: '+237',
  },
  {
    name: {en: 'Canada', th: 'แคนาดา', cs: '加拿大'},
    flag: '🇨🇦',
    code: 'CA',
    dial_code: '+1',
  },
  {
    name: {en: 'Cape Verde', th: 'เคปเวิร์ด', cs: '佛得角'},
    flag: '🇨🇻',
    code: 'CV',
    dial_code: '+238',
  },
  {
    name: {en: 'Cayman Islands', th: 'หมู่เกาะเคย์แมน', cs: '开曼群岛'},
    flag: '🇰🇾',
    code: 'KY',
    dial_code: '+345',
  },
  {
    name: {
      en: 'Central African Republic',
      th: 'สาธารณรัฐแอฟริกากลาง',
      cs: '中非共和国',
    },
    flag: '🇨🇫',
    code: 'CF',
    dial_code: '+236',
  },
  {
    name: {en: 'Chad', th: 'ชาด', cs: '乍得'},
    flag: '🇹🇩',
    code: 'TD',
    dial_code: '+235',
  },
  {
    name: {en: 'Chile', th: 'ชิลี', cs: '智利'},
    flag: '🇨🇱',
    code: 'CL',
    dial_code: '+56',
  },
  {
    name: {en: 'China', th: 'จีน', cs: '中国'},
    flag: '🇨🇳',
    code: 'CN',
    dial_code: '+86',
  },
  {
    name: {en: 'Christmas Island', th: 'เกาะคริสต์มาส', cs: '圣诞岛'},
    flag: '🇨🇽',
    code: 'CX',
    dial_code: '+61',
  },
  {
    name: {
      en: 'Cocos (Keeling) Islands',
      th: 'หมู่เกาะโคโคส',
      cs: '科科斯（基林）群岛',
    },
    flag: '🇨🇨',
    code: 'CC',
    dial_code: '+61',
  },
  {
    name: {en: 'Colombia', th: 'โคลอมเบีย', cs: '哥伦比亚'},
    flag: '🇨🇴',
    code: 'CO',
    dial_code: '+57',
  },
  {
    name: {en: 'Comoros', th: 'คอโมโรส', cs: '科摩罗'},
    flag: '🇰🇲',
    code: 'KM',
    dial_code: '+269',
  },
  {
    name: {en: 'Congo', th: 'คองโก', cs: '刚果'},
    flag: '🇨🇬',
    code: 'CG',
    dial_code: '+242',
  },
  {
    name: {
      en: 'Congo, The Democratic Republic of the Congo',
      th: 'สาธารณรัฐประชาธิปไตยประชาชนคองโก',
      cs: '刚果民主共和国',
    },
    flag: '🇨🇩',
    code: 'CD',
    dial_code: '+243',
  },
  {
    name: {en: 'Cook Islands', th: 'หมู่เกาะคุก', cs: '库克群岛'},
    flag: '🇨🇰',
    code: 'CK',
    dial_code: '+682',
  },
  {
    name: {en: 'Costa Rica', th: 'ประเทศคอสตาริกา', cs: '哥斯达黎加'},
    flag: '🇨🇷',
    code: 'CR',
    dial_code: '+506',
  },
  {
    name: {en: "Cote d'Ivoire", th: 'ไอวอร์โคสต์', cs: '科特迪瓦'},
    flag: '🇨🇮',
    code: 'CI',
    dial_code: '+225',
  },
  {
    name: {en: 'Croatia', th: 'โครเอเชีย', cs: '克罗地亚'},
    flag: '🇭🇷',
    code: 'HR',
    dial_code: '+385',
  },
  {
    name: {en: 'Cuba', th: 'คิวบา', cs: '古巴'},
    flag: '🇨🇺',
    code: 'CU',
    dial_code: '+53',
  },
  {
    name: {en: 'Cyprus', th: 'ไซปรัส', cs: '塞浦路斯'},
    flag: '🇨🇾',
    code: 'CY',
    dial_code: '+357',
  },
  {
    name: {en: 'Czech Republic', th: 'สาธารณรัฐเช็ก', cs: '捷克共和国'},
    flag: '🇨🇿',
    code: 'CZ',
    dial_code: '+420',
  },
  {
    name: {en: 'Denmark', th: 'เดนมาร์ก', cs: '丹麦'},
    flag: '🇩🇰',
    code: 'DK',
    dial_code: '+45',
  },
  {
    name: {en: 'Djibouti', th: 'จิบูตี', cs: '吉布提'},
    flag: '🇩🇯',
    code: 'DJ',
    dial_code: '+253',
  },
  {
    name: {en: 'Dominica', th: 'โดมินิกา', cs: '多米尼加'},
    flag: '🇩🇲',
    code: 'DM',
    dial_code: '+1767',
  },
  {
    name: {
      en: 'Dominican Republic',
      th: 'สาธารณรัฐโดมินิกัน',
      cs: '多米尼加共和国',
    },
    flag: '🇩🇴',
    code: 'DO',
    dial_code: '+1849',
  },
  {
    name: {en: 'Ecuador', th: 'เอกวาดอร์', cs: '厄瓜多尔'},
    flag: '🇪🇨',
    code: 'EC',
    dial_code: '+593',
  },
  {
    name: {en: 'Egypt', th: 'อียิปต์', cs: '埃及'},
    flag: '🇪🇬',
    code: 'EG',
    dial_code: '+20',
  },
  {
    name: {en: 'El Salvador', th: 'เอลซัลวาดอร์', cs: '萨尔瓦多'},
    flag: '🇸🇻',
    code: 'SV',
    dial_code: '+503',
  },
  {
    name: {en: 'Equatorial Guinea', th: 'อิเควทอเรียลกินี', cs: '赤道几内亚'},
    flag: '🇬🇶',
    code: 'GQ',
    dial_code: '+240',
  },
  {
    name: {en: 'Eritrea', th: 'เอริเทรีย', cs: '厄立特里亚'},
    flag: '🇪🇷',
    code: 'ER',
    dial_code: '+291',
  },
  {
    name: {en: 'Estonia', th: 'เอสโตเนีย', cs: '爱沙尼亚'},
    flag: '🇪🇪',
    code: 'EE',
    dial_code: '+372',
  },
  {
    name: {en: 'Ethiopia', th: 'เอธิโอเปีย', cs: '埃塞俄比亚'},
    flag: '🇪🇹',
    code: 'ET',
    dial_code: '+251',
  },
  {
    name: {
      en: 'Falkland Islands (Malvinas)',
      th: 'หมู่เกาะฟอล์คแลนด์ (มัลวินาส)',
      cs: '福克兰群岛（马尔维纳斯）',
    },
    flag: '🇫🇰',
    code: 'FK',
    dial_code: '+500',
  },
  {
    name: {en: 'Faroe Islands', th: 'หมู่เกาะแฟโร', cs: '法罗群岛'},
    flag: '🇫🇴',
    code: 'FO',
    dial_code: '+298',
  },
  {
    name: {en: 'Fiji', th: 'ฟิจิ', cs: '斐济'},
    flag: '🇫🇯',
    code: 'FJ',
    dial_code: '+679',
  },
  {
    name: {en: 'Finland', th: 'ฟินแลนด์', cs: '芬兰'},
    flag: '🇫🇮',
    code: 'FI',
    dial_code: '+358',
  },
  {
    name: {en: 'France', th: 'ฝรั่งเศส', cs: '法国'},
    flag: '🇫🇷',
    code: 'FR',
    dial_code: '+33',
  },
  {
    name: {en: 'French Guiana', th: 'เฟรนช์เกียนา', cs: '法属圭亚那'},
    flag: '🇬🇫',
    code: 'GF',
    dial_code: '+594',
  },
  {
    name: {
      en: 'French Polynesia',
      th: 'เฟรนช์โปลินีเซีย',
      cs: '法属波利尼西亚',
    },
    flag: '🇵🇫',
    code: 'PF',
    dial_code: '+689',
  },
  {
    name: {
      en: 'French Southern Territories',
      th: 'เฟรนช์ซาเซิอะเทร์ริทอรีส์',
      cs: '法属南部领地',
    },
    flag: '🇹🇫',
    code: 'TF',
    dial_code: '+262',
  },
  {
    name: {en: 'Gabon', th: 'กาบอง', cs: '加蓬'},
    flag: '🇬🇦',
    code: 'GA',
    dial_code: '+241',
  },
  {
    name: {en: 'Gambia', th: 'แกมเบีย', cs: '冈比亚'},
    flag: '🇬🇲',
    code: 'GM',
    dial_code: '+220',
  },
  {
    name: {en: 'Georgia', th: 'จอร์เจีย', cs: '格鲁吉亚'},
    flag: '🇬🇪',
    code: 'GE',
    dial_code: '+995',
  },
  {
    name: {en: 'Germany', th: 'เยอรมนี', cs: '德国'},
    flag: '🇩🇪',
    code: 'DE',
    dial_code: '+49',
  },
  {
    name: {en: 'Ghana', th: 'กานา', cs: '加纳'},
    flag: '🇬🇭',
    code: 'GH',
    dial_code: '+233',
  },
  {
    name: {en: 'Gibraltar', th: 'ยิบรอลตาร์', cs: '直布罗陀'},
    flag: '🇬🇮',
    code: 'GI',
    dial_code: '+350',
  },
  {
    name: {en: 'Greece', th: 'กรีซ', cs: '希腊'},
    flag: '🇬🇷',
    code: 'GR',
    dial_code: '+30',
  },
  {
    name: {en: 'Greenland', th: 'กรีนแลนด์', cs: '格陵兰'},
    flag: '🇬🇱',
    code: 'GL',
    dial_code: '+299',
  },
  {
    name: {en: 'Grenada', th: 'เกรเนดา', cs: '格林纳达'},
    flag: '🇬🇩',
    code: 'GD',
    dial_code: '+1473',
  },
  {
    name: {en: 'Guadeloupe', th: 'กวาเดอลุป', cs: '瓜德罗普'},
    flag: '🇬🇵',
    code: 'GP',
    dial_code: '+590',
  },
  {
    name: {en: 'Guam', th: 'กวม', cs: '关岛'},
    flag: '🇬🇺',
    code: 'GU',
    dial_code: '+1671',
  },
  {
    name: {en: 'Guatemala', th: 'กัวเตมาลา', cs: '危地马拉'},
    flag: '🇬🇹',
    code: 'GT',
    dial_code: '+502',
  },
  {
    name: {en: 'Guernsey', th: 'เกิร์นซีย์', cs: '根西岛'},
    flag: '🇬🇬',
    code: 'GG',
    dial_code: '+44',
  },
  {
    name: {en: 'Guinea', th: 'กินี', cs: '几内亚'},
    flag: '🇬🇳',
    code: 'GN',
    dial_code: '+224',
  },
  {
    name: {en: 'Guinea-Bissau', th: 'กินี-บิสเซา', cs: '几内亚比绍'},
    flag: '🇬🇼',
    code: 'GW',
    dial_code: '+245',
  },
  {
    name: {en: 'Guyana', th: 'กายอานา', cs: '圭亚那'},
    flag: '🇬🇾',
    code: 'GY',
    dial_code: '+592',
  },
  {
    name: {en: 'Haiti', th: 'เฮติ', cs: '海地'},
    flag: '🇭🇹',
    code: 'HT',
    dial_code: '+509',
  },
  {
    name: {
      en: 'Heard Island and McDonald Islands',
      th: 'เกาะเฮิร์ดและหมู่เกาะแมคโดนัลด์',
      cs: '赫德岛和麦克唐纳群岛',
    },
    flag: '🇭🇲',
    code: 'HM',
    dial_code: '+672',
  },
  {
    name: {
      en: 'Holy See (Vatican City State)',
      th: 'นครสวรรค์ (วาติกัน)',
      cs: '梵蒂冈',
    },
    flag: '🇻🇦',
    code: 'VA',
    dial_code: '+379',
  },
  {
    name: {en: 'Honduras', th: 'ฮอนดูรัส', cs: '洪都拉斯'},
    flag: '🇭🇳',
    code: 'HN',
    dial_code: '+504',
  },
  {
    name: {en: 'Hong Kong', th: 'ฮ่องกง', cs: '香港'},
    flag: '🇭🇰',
    code: 'HK',
    dial_code: '+852',
  },
  {
    name: {en: 'Hungary', th: 'ฮังการี', cs: '匈牙利'},
    flag: '🇭🇺',
    code: 'HU',
    dial_code: '+36',
  },
  {
    name: {en: 'Iceland', th: 'ไอซ์แลนด์', cs: '冰岛'},
    flag: '🇮🇸',
    code: 'IS',
    dial_code: '+354',
  },
  {
    name: {en: 'India', th: 'อินเดีย', cs: '印度'},
    flag: '🇮🇳',
    code: 'IN',
    dial_code: '+91',
  },
  {
    name: {en: 'Indonesia', th: 'อินโดนีเซีย', cs: '印度尼西亚'},
    flag: '🇮🇩',
    code: 'ID',
    dial_code: '+62',
  },
  {
    name: {
      en: 'Iran, Islamic Republic of',
      th: 'อิหร่าน, สาธารณรัฐอิสลาม',
      cs: '伊朗，伊斯兰共和国',
    },
    flag: '🇮🇷',
    code: 'IR',
    dial_code: '+98',
  },
  {
    name: {en: 'Iraq', th: 'อิรัก', cs: '伊拉克'},
    flag: '🇮🇶',
    code: 'IQ',
    dial_code: '+964',
  },
  {
    name: {en: 'Ireland', th: 'ไอร์แลนด์', cs: '爱尔兰'},
    flag: '🇮🇪',
    code: 'IE',
    dial_code: '+353',
  },
  {
    name: {en: 'Isle of Man', th: 'เกาะแมน', cs: '马恩岛'},
    flag: '🇮🇲',
    code: 'IM',
    dial_code: '+44',
  },
  {
    name: {en: 'Israel', th: 'อิสราเอล', cs: '以色列'},
    flag: '🇮🇱',
    code: 'IL',
    dial_code: '+972',
  },
  {
    name: {en: 'Italy', th: 'อิตาลี', cs: '意大利'},
    flag: '🇮🇹',
    code: 'IT',
    dial_code: '+39',
  },
  {
    name: {en: 'Jamaica', th: 'จาเมกา', cs: '牙买加'},
    flag: '🇯🇲',
    code: 'JM',
    dial_code: '+1876',
  },
  {
    name: {en: 'Japan', th: 'ญี่ปุ่น', cs: '日本'},
    flag: '🇯🇵',
    code: 'JP',
    dial_code: '+81',
  },
  {
    name: {en: 'Jersey', th: 'เจอร์ซีย์', cs: '泽西岛'},
    flag: '🇯🇪',
    code: 'JE',
    dial_code: '+44',
  },
  {
    name: {en: 'Jordan', th: 'จอร์แดน', cs: '约旦'},
    flag: '🇯🇴',
    code: 'JO',
    dial_code: '+962',
  },
  {
    name: {en: 'Kazakhstan', th: 'คาซัคสถาน', cs: '哈萨克斯坦'},
    flag: '🇰🇿',
    code: 'KZ',
    dial_code: '+7',
  },
  {
    name: {en: 'Kenya', th: 'เคนยา', cs: '肯尼亚'},
    flag: '🇰🇪',
    code: 'KE',
    dial_code: '+254',
  },
  {
    name: {en: 'Kiribati', th: 'คิริบาส', cs: '基里巴斯'},
    flag: '🇰🇮',
    code: 'KI',
    dial_code: '+686',
  },
  {
    name: {
      en: "Korea, Democratic People's Republic of",
      th: 'เกาหลีเหนือ',
      cs: '朝鲜',
    },
    flag: '🇰🇵',
    code: 'KP',
    dial_code: '+850',
  },
  {
    name: {en: 'Korea, Republic of', th: 'เกาหลีใต้', cs: '韩国'},
    flag: '🇰🇷',
    code: 'KR',
    dial_code: '+82',
  },
  {
    name: {en: 'Kosovo', th: 'โคโซโว', cs: '科索沃'},
    flag: '🇽🇰',
    code: 'XK',
    dial_code: '+383',
  },
  {
    name: {en: 'Kuwait', th: 'คูเวต', cs: '科威特'},
    flag: '🇰🇼',
    code: 'KW',
    dial_code: '+965',
  },
  {
    name: {en: 'Kyrgyzstan', th: 'คีร์กีซสถาน', cs: '吉尔吉斯斯坦'},
    flag: '🇰🇬',
    code: 'KG',
    dial_code: '+996',
  },
  {
    name: {en: 'Laos', th: 'ลาว', cs: '老挝'},
    flag: '🇱🇦',
    code: 'LA',
    dial_code: '+856',
  },
  {
    name: {en: 'Latvia', th: 'ลัตเวีย', cs: '拉脱维亚'},
    flag: '🇱🇻',
    code: 'LV',
    dial_code: '+371',
  },
  {
    name: {en: 'Lebanon', th: 'เลบานอน', cs: '黎巴嫩'},
    flag: '🇱🇧',
    code: 'LB',
    dial_code: '+961',
  },
  {
    name: {en: 'Lesotho', th: 'เลโซโท', cs: '莱索托'},
    flag: '🇱🇸',
    code: 'LS',
    dial_code: '+266',
  },
  {
    name: {en: 'Liberia', th: 'ลิเบีย', cs: '利比里亚'},
    flag: '🇱🇷',
    code: 'LR',
    dial_code: '+231',
  },
  {
    name: {en: 'Libyan Arab Jamahiriya', th: 'ลิเบีย', cs: '利比亚'},
    flag: '🇱🇾',
    code: 'LY',
    dial_code: '+218',
  },
  {
    name: {en: 'Liechtenstein', th: 'ลิกเตนสไตน์', cs: '列支敦士登'},
    flag: '🇱🇮',
    code: 'LI',
    dial_code: '+423',
  },
  {
    name: {en: 'Lithuania', th: 'ลิทัวเนีย', cs: '立陶宛'},
    flag: '🇱🇹',
    code: 'LT',
    dial_code: '+370',
  },
  {
    name: {en: 'Luxembourg', th: 'ลักเซมเบิร์ก', cs: '卢森堡'},
    flag: '🇱🇺',
    code: 'LU',
    dial_code: '+352',
  },
  {
    name: {en: 'Macao', th: 'มาเก๊า', cs: '澳门'},
    flag: '🇲🇴',
    code: 'MO',
    dial_code: '+853',
  },
  {
    name: {en: 'Macedonia', th: 'มาซิโดเนีย', cs: '马其顿'},
    flag: '🇲🇰',
    code: 'MK',
    dial_code: '+389',
  },
  {
    name: {en: 'Madagascar', th: 'มาดากัสการ์', cs: '马达加斯加'},
    flag: '🇲🇬',
    code: 'MG',
    dial_code: '+261',
  },
  {
    name: {en: 'Malawi', th: 'มาลาวี', cs: '马拉维'},
    flag: '🇲🇼',
    code: 'MW',
    dial_code: '+265',
  },
  {
    name: {en: 'Malaysia', th: 'มาเลเซีย', cs: '马来西亚'},
    flag: '🇲🇾',
    code: 'MY',
    dial_code: '+60',
  },
  {
    name: {en: 'Maldives', th: 'มัลดีฟส์', cs: '马尔代夫'},
    flag: '🇲🇻',
    code: 'MV',
    dial_code: '+960',
  },
  {
    name: {en: 'Mali', th: 'มาลี', cs: '马里'},
    flag: '🇲🇱',
    code: 'ML',
    dial_code: '+223',
  },
  {
    name: {en: 'Malta', th: 'มอลตา', cs: '马耳他'},
    flag: '🇲🇹',
    code: 'MT',
    dial_code: '+356',
  },
  {
    name: {en: 'Marshall Islands', th: 'หมู่เกาะมาร์แชลล์', cs: '马绍尔群岛'},
    flag: '🇲🇭',
    code: 'MH',
    dial_code: '+692',
  },
  {
    name: {en: 'Martinique', th: 'มาร์ตินีก', cs: '马提尼克'},
    flag: '🇲🇶',
    code: 'MQ',
    dial_code: '+596',
  },
  {
    name: {en: 'Mauritania', th: 'มอริเตเนีย', cs: '毛里塔尼亚'},
    flag: '🇲🇷',
    code: 'MR',
    dial_code: '+222',
  },
  {
    name: {en: 'Mauritius', th: 'มอริเชียส', cs: '毛里求斯'},
    flag: '🇲🇺',
    code: 'MU',
    dial_code: '+230',
  },
  {
    name: {en: 'Mayotte', th: 'มายอต', cs: '马约特'},
    flag: '🇾🇹',
    code: 'YT',
    dial_code: '+262',
  },
  {
    name: {en: 'Mexico', th: 'เม็กซิโก', cs: '墨西哥'},
    flag: '🇲🇽',
    code: 'MX',
    dial_code: '+52',
  },
  {
    name: {
      en: 'Micronesia, Federated States of',
      th: 'ไมโครนีเซีย',
      cs: '密克罗尼西亚',
    },
    flag: '🇫🇲',
    code: 'FM',
    dial_code: '+691',
  },
  {
    name: {en: 'Moldova', th: 'มอลโดวา', cs: '摩尔多瓦'},
    flag: '🇲🇩',
    code: 'MD',
    dial_code: '+373',
  },
  {
    name: {en: 'Monaco', th: 'โมนาโก', cs: '摩纳哥'},
    flag: '🇲🇨',
    code: 'MC',
    dial_code: '+377',
  },
  {
    name: {en: 'Mongolia', th: 'มองโกเลีย', cs: '蒙古'},
    flag: '🇲🇳',
    code: 'MN',
    dial_code: '+976',
  },
  {
    name: {en: 'Montenegro', th: 'มอนเตเนโกร', cs: '黑山'},
    flag: '🇲🇪',
    code: 'ME',
    dial_code: '+382',
  },
  {
    name: {en: 'Montserrat', th: 'มอนต์เซอร์รัต', cs: '蒙特塞拉特'},
    flag: '🇲🇸',
    code: 'MS',
    dial_code: '+1664',
  },
  {
    name: {en: 'Morocco', th: 'โมร็อกโก', cs: '摩洛哥'},
    flag: '🇲🇦',
    code: 'MA',
    dial_code: '+212',
  },
  {
    name: {en: 'Mozambique', th: 'โมซัมบิก', cs: '莫桑比克'},
    flag: '🇲🇿',
    code: 'MZ',
    dial_code: '+258',
  },
  {
    name: {en: 'Myanmar', th: 'พม่า', cs: '缅甸'},
    flag: '🇲🇲',
    code: 'MM',
    dial_code: '+95',
  },
  {
    name: {en: 'Namibia', th: 'นามิเบีย', cs: '纳米比亚'},
    flag: '🇳🇦',
    code: 'NA',
    dial_code: '+264',
  },
  {
    name: {en: 'Nauru', th: 'นาอูรู', cs: '瑙鲁'},
    flag: '🇳🇷',
    code: 'NR',
    dial_code: '+674',
  },
  {
    name: {en: 'Nepal', th: 'เนปาล', cs: '尼泊尔'},
    flag: '🇳🇵',
    code: 'NP',
    dial_code: '+977',
  },
  {
    name: {en: 'Netherlands', th: 'เนเธอร์แลนด์', cs: '荷兰'},
    flag: '🇳🇱',
    code: 'NL',
    dial_code: '+31',
  },
  {
    name: {
      en: 'Netherlands Antilles',
      th: 'เนเธอร์แลนด์แอนทิลลิส',
      cs: '荷属安的列斯',
    },
    flag: '',
    code: 'AN',
    dial_code: '+599',
  },
  {
    name: {en: 'New Caledonia', th: 'นิวแคลิโดเนีย', cs: '新喀里多尼亚'},
    flag: '🇳🇨',
    code: 'NC',
    dial_code: '+687',
  },
  {
    name: {en: 'New Zealand', th: 'นิวซีแลนด์', cs: '新西兰'},
    flag: '🇳🇿',
    code: 'NZ',
    dial_code: '+64',
  },
  {
    name: {en: 'Nicaragua', th: 'นิการากัว', cs: '尼加拉瓜'},
    flag: '🇳🇮',
    code: 'NI',
    dial_code: '+505',
  },
  {
    name: {en: 'Niger', th: 'ไนเจอร์', cs: '尼日尔'},
    flag: '🇳🇪',
    code: 'NE',
    dial_code: '+227',
  },
  {
    name: {en: 'Nigeria', th: 'ไนจีเรีย', cs: '尼日利亚'},
    flag: '🇳🇬',
    code: 'NG',
    dial_code: '+234',
  },
  {
    name: {en: 'Niue', th: 'นีอูเอ', cs: '纽埃'},
    flag: '🇳🇺',
    code: 'NU',
    dial_code: '+683',
  },
  {
    name: {en: 'Norfolk Island', th: 'นอร์ฟอล์ก', cs: '诺福克岛'},
    flag: '🇳🇫',
    code: 'NF',
    dial_code: '+672',
  },
  {
    name: {
      en: 'Northern Mariana Islands',
      th: 'หมู่เกาะนอร์เทิร์นมาร์เยนา',
      cs: '北马里亚纳群岛',
    },
    flag: '🇲🇵',
    code: 'MP',
    dial_code: '+1670',
  },
  {
    name: {en: 'Norway', th: 'นอร์เวย์', cs: '挪威'},
    flag: '🇳🇴',
    code: 'NO',
    dial_code: '+47',
  },
  {
    name: {en: 'Oman', th: 'โอมาน', cs: '阿曼'},
    flag: '🇴🇲',
    code: 'OM',
    dial_code: '+968',
  },
  {
    name: {en: 'Pakistan', th: 'ปากีสถาน', cs: '巴基斯坦'},
    flag: '🇵🇰',
    code: 'PK',
    dial_code: '+92',
  },
  {
    name: {en: 'Palau', th: 'ปาเลา', cs: '帕劳'},
    flag: '🇵🇼',
    code: 'PW',
    dial_code: '+680',
  },
  {
    name: {
      en: 'Palestinian Territory, Occupied',
      th: 'ดินแดนปาเลสไตน์',
      cs: '巴勒斯坦领土，已占领',
    },
    flag: '🇵🇸',
    code: 'PS',
    dial_code: '+970',
  },
  {
    name: {en: 'Panama', th: 'ปานามา', cs: '巴拿马'},
    flag: '🇵🇦',
    code: 'PA',
    dial_code: '+507',
  },
  {
    name: {en: 'Papua New Guinea', th: 'ปาปัวนิวกินี', cs: '巴布亚新几内亚'},
    flag: '🇵🇬',
    code: 'PG',
    dial_code: '+675',
  },
  {
    name: {en: 'Paraguay', th: 'ปารากวัย', cs: '巴拉圭'},
    flag: '🇵🇾',
    code: 'PY',
    dial_code: '+595',
  },
  {
    name: {en: 'Peru', th: 'เปรู', cs: '秘鲁'},
    flag: '🇵🇪',
    code: 'PE',
    dial_code: '+51',
  },
  {
    name: {en: 'Philippines', th: 'ฟิลิปปินส์', cs: '菲律宾'},
    flag: '🇵🇭',
    code: 'PH',
    dial_code: '+63',
  },
  {
    name: {en: 'Pitcairn', th: 'พิทแคร์น', cs: '皮特凯恩'},
    flag: '🇵🇳',
    code: 'PN',
    dial_code: '+64',
  },
  {
    name: {en: 'Poland', th: 'โปแลนด์', cs: '波兰'},
    flag: '🇵🇱',
    code: 'PL',
    dial_code: '+48',
  },
  {
    name: {en: 'Portugal', th: 'โปรตุเกส', cs: '葡萄牙'},
    flag: '🇵🇹',
    code: 'PT',
    dial_code: '+351',
  },
  {
    name: {en: 'Puerto Rico', th: 'เปอร์โตริโก', cs: '波多黎各'},
    flag: '🇵🇷',
    code: 'PR',
    dial_code: '+1939',
  },
  {
    name: {en: 'Qatar', th: 'กาตาร์', cs: '卡塔尔'},
    flag: '🇶🇦',
    code: 'QA',
    dial_code: '+974',
  },
  {
    name: {en: 'Romania', th: 'โรมาเนีย', cs: '罗马尼亚'},
    flag: '🇷🇴',
    code: 'RO',
    dial_code: '+40',
  },
  {
    name: {en: 'Russia', th: 'รัสเซีย', cs: '俄罗斯'},
    flag: '🇷🇺',
    code: 'RU',
    dial_code: '+7',
  },
  {
    name: {en: 'Rwanda', th: 'รวันดา', cs: '卢旺达'},
    flag: '🇷🇼',
    code: 'RW',
    dial_code: '+250',
  },
  {
    name: {en: 'Reunion', th: 'เรอูนียง', cs: '留尼汪'},
    flag: '🇷🇪',
    code: 'RE',
    dial_code: '+262',
  },
  {
    name: {en: 'Saint Barthelemy', th: 'เซนต์บาร์เธเลมี', cs: '圣巴泰勒米'},
    flag: '🇧🇱',
    code: 'BL',
    dial_code: '+590',
  },
  {
    name: {
      en: 'Saint Helena, Ascension and Tristan Da Cunha',
      th: 'เซนต์เฮเลนา, แอสเซ็นชัน และตริสตันดาคูนญ่า',
      cs: '圣赫勒拿、阿森松和特里斯坦-达库尼亚',
    },
    flag: '🇸🇭',
    code: 'SH',
    dial_code: '+290',
  },
  {
    name: {
      en: 'Saint Kitts and Nevis',
      th: 'เซนต์คิตส์และเนวิส',
      cs: '圣基茨和尼维斯',
    },
    flag: '🇰🇳',
    code: 'KN',
    dial_code: '+1869',
  },
  {
    name: {en: 'Saint Lucia', th: 'เซนต์ลูเซีย', cs: '圣卢西亚'},
    flag: '🇱🇨',
    code: 'LC',
    dial_code: '+1758',
  },
  {
    name: {en: 'Saint Martin', th: 'เซนต์มาร์ติน', cs: '圣马丁'},
    flag: '🇲🇫',
    code: 'MF',
    dial_code: '+590',
  },
  {
    name: {
      en: 'Saint Pierre and Miquelon',
      th: 'เซนต์ปิแอร์และมีเกอลง',
      cs: '圣皮埃尔和密克隆',
    },
    flag: '🇵🇲',
    code: 'PM',
    dial_code: '+508',
  },
  {
    name: {
      en: 'Saint Vincent and the Grenadines',
      th: 'เซนต์วินเซนต์และเกรนาดีนส์',
      cs: '圣文森特和格林纳丁斯',
    },
    flag: '🇻🇨',
    code: 'VC',
    dial_code: '+1784',
  },
  {
    name: {en: 'Samoa', th: 'ซามัว', cs: '萨摩亚'},
    flag: '🇼🇸',
    code: 'WS',
    dial_code: '+685',
  },
  {
    name: {en: 'San Marino', th: 'ซานมารีโน', cs: '圣马力诺'},
    flag: '🇸🇲',
    code: 'SM',
    dial_code: '+378',
  },
  {
    name: {
      en: 'Sao Tome and Principe',
      th: 'เซาตูเมและปรินซีปี',
      cs: '圣多美和普林西比',
    },
    flag: '🇸🇹',
    code: 'ST',
    dial_code: '+239',
  },
  {
    name: {en: 'Saudi Arabia', th: 'ซาอุดีอาระเบีย', cs: '沙特阿拉伯'},
    flag: '🇸🇦',
    code: 'SA',
    dial_code: '+966',
  },
  {
    name: {en: 'Senegal', th: 'เซเนกัล', cs: '塞内加尔'},
    flag: '🇸🇳',
    code: 'SN',
    dial_code: '+221',
  },
  {
    name: {en: 'Serbia', th: 'เซอร์เบีย', cs: '塞尔维亚'},
    flag: '🇷🇸',
    code: 'RS',
    dial_code: '+381',
  },
  {
    name: {en: 'Seychelles', th: 'เซเชลส์', cs: '塞舌尔'},
    flag: '🇸🇨',
    code: 'SC',
    dial_code: '+248',
  },
  {
    name: {en: 'Sierra Leone', th: 'เซียร์ราลีโอน', cs: '塞拉利昂'},
    flag: '🇸🇱',
    code: 'SL',
    dial_code: '+232',
  },
  {
    name: {en: 'Singapore', th: 'สิงคโปร์', cs: '新加坡'},
    flag: '🇸🇬',
    code: 'SG',
    dial_code: '+65',
  },
  {
    name: {en: 'Slovakia', th: 'สโลวะเกีย', cs: '斯洛伐克'},
    flag: '🇸🇰',
    code: 'SK',
    dial_code: '+421',
  },
  {
    name: {en: 'Slovenia', th: 'สโลวีเนีย', cs: '斯洛文尼亚'},
    flag: '🇸🇮',
    code: 'SI',
    dial_code: '+386',
  },
  {
    name: {en: 'Solomon Islands', th: 'หมู่เกาะโซโลมอน', cs: '所罗门群岛'},
    flag: '🇸🇧',
    code: 'SB',
    dial_code: '+677',
  },
  {
    name: {en: 'Somalia', th: 'โซมาเลีย', cs: '索马里'},
    flag: '🇸🇴',
    code: 'SO',
    dial_code: '+252',
  },
  {
    name: {en: 'South Africa', th: 'แอฟริกาใต้', cs: '南非'},
    flag: '🇿🇦',
    code: 'ZA',
    dial_code: '+27',
  },
  {
    name: {en: 'South Sudan', th: 'ซูดานใต้', cs: '南苏丹'},
    flag: '🇸🇸',
    code: 'SS',
    dial_code: '+211',
  },
  {
    name: {
      en: 'South Georgia and the South Sandwich Islands',
      th: 'เกาะแซวิชและหมู่เกาะซานด์วิช',
      cs: '南乔治亚和南桑威奇群岛',
    },
    flag: '🇬🇸',
    code: 'GS',
    dial_code: '+500',
  },
  {
    name: {en: 'Spain', th: 'สเปน', cs: '西班牙'},
    flag: '🇪🇸',
    code: 'ES',
    dial_code: '+34',
  },
  {
    name: {en: 'Sri Lanka', th: 'ศรีลังกา', cs: '斯里兰卡'},
    flag: '🇱🇰',
    code: 'LK',
    dial_code: '+94',
  },
  {
    name: {en: 'Sudan', th: 'ซูดาน', cs: '苏丹'},
    flag: '🇸🇩',
    code: 'SD',
    dial_code: '+249',
  },
  {
    name: {en: 'Suriname', th: 'ซูรินาเม', cs: '苏里南'},
    flag: '🇸🇷',
    code: 'SR',
    dial_code: '+597',
  },
  {
    name: {
      en: 'Svalbard and Jan Mayen',
      th: 'สวาลบาร์และยานไมเอน',
      cs: '斯瓦尔巴特和扬马延',
    },
    flag: '🇸🇯',
    code: 'SJ',
    dial_code: '+47',
  },
  {
    name: {en: 'Swaziland', th: 'สวาซิแลนด์', cs: '斯威士兰'},
    flag: '🇸🇿',
    code: 'SZ',
    dial_code: '+268',
  },
  {
    name: {en: 'Sweden', th: 'สวีเดน', cs: '瑞典'},
    flag: '🇸🇪',
    code: 'SE',
    dial_code: '+46',
  },
  {
    name: {en: 'Switzerland', th: 'สวิตเซอร์แลนด์', cs: '瑞士'},
    flag: '🇨🇭',
    code: 'CH',
    dial_code: '+41',
  },
  {
    name: {
      en: 'Syrian Arab Republic',
      th: 'สาธารณรัฐอาหรับซีเรีย',
      cs: '叙利亚阿拉伯共和国',
    },
    flag: '🇸🇾',
    code: 'SY',
    dial_code: '+963',
  },
  {
    name: {en: 'Taiwan', th: 'ไต้หวัน', cs: '台湾'},
    flag: '🇹🇼',
    code: 'TW',
    dial_code: '+886',
  },
  {
    name: {en: 'Tajikistan', th: 'ทาจิกิสถาน', cs: '塔吉克斯坦'},
    flag: '🇹🇯',
    code: 'TJ',
    dial_code: '+992',
  },
  {
    name: {
      en: 'Tanzania, United Republic of Tanzania',
      th: 'แทนซาเนีย',
      cs: '坦桑尼亚',
    },
    flag: '🇹🇿',
    code: 'TZ',
    dial_code: '+255',
  },
  {
    name: {en: 'Thailand', th: 'ไทย', cs: '泰国'},
    flag: '🇹🇭',
    code: 'TH',
    dial_code: '+66',
  },
  {
    name: {en: 'Timor-Leste', th: 'ติมอร์เลสเต', cs: '东帝汶'},
    flag: '🇹🇱',
    code: 'TL',
    dial_code: '+670',
  },
  {
    name: {en: 'Togo', th: 'โตโก', cs: '多哥'},
    flag: '🇹🇬',
    code: 'TG',
    dial_code: '+228',
  },
  {
    name: {en: 'Tokelau', th: 'โทเคเลา', cs: '托克劳'},
    flag: '🇹🇰',
    code: 'TK',
    dial_code: '+690',
  },
  {
    name: {en: 'Tonga', th: 'ตองกา', cs: '汤加'},
    flag: '🇹🇴',
    code: 'TO',
    dial_code: '+676',
  },
  {
    name: {
      en: 'Trinidad and Tobago',
      th: 'ตรินิแดดและโตเบโก',
      cs: '特立尼达和多巴哥',
    },
    flag: '🇹🇹',
    code: 'TT',
    dial_code: '+1868',
  },
  {
    name: {en: 'Tunisia', th: 'ตูนิเซีย', cs: '突尼斯'},
    flag: '🇹🇳',
    code: 'TN',
    dial_code: '+216',
  },
  {
    name: {en: 'Turkey', th: 'ตุรกี', cs: '土耳其'},
    flag: '🇹🇷',
    code: 'TR',
    dial_code: '+90',
  },
  {
    name: {en: 'Turkmenistan', th: 'เติร์กเมนิสถาน', cs: '土库曼斯坦'},
    flag: '🇹🇲',
    code: 'TM',
    dial_code: '+993',
  },
  {
    name: {
      en: 'Turks and Caicos Islands',
      th: 'หมู่เกาะเติกส์และเคโคส',
      cs: '特克斯和凯科斯群岛',
    },
    flag: '🇹🇨',
    code: 'TC',
    dial_code: '+1649',
  },
  {
    name: {en: 'Tuvalu', th: 'ตูวาลู', cs: '图瓦卢'},
    flag: '🇹🇻',
    code: 'TV',
    dial_code: '+688',
  },
  {
    name: {en: 'Uganda', th: 'ยูกันดา', cs: '乌干达'},
    flag: '🇺🇬',
    code: 'UG',
    dial_code: '+256',
  },
  {
    name: {en: 'Ukraine', th: 'ยูเครน', cs: '乌克兰'},
    flag: '🇺🇦',
    code: 'UA',
    dial_code: '+380',
  },
  {
    name: {
      en: 'United Arab Emirates',
      th: 'สหรัฐอาหรับเอมิเรตส์',
      cs: '阿拉伯联合酋长国',
    },
    flag: '🇦🇪',
    code: 'AE',
    dial_code: '+971',
  },
  {
    name: {en: 'United Kingdom', th: 'สหราชอาณาจักร', cs: '英国'},
    flag: '🇬🇧',
    code: 'GB',
    dial_code: '+44',
  },
  {
    name: {en: 'United States', th: 'สหรัฐอเมริกา', cs: '美国'},
    flag: '🇺🇸',
    code: 'US',
    dial_code: '+1',
  },
  {
    name: {en: 'Uruguay', th: 'อุรุกวัย', cs: '乌拉圭'},
    flag: '🇺🇾',
    code: 'UY',
    dial_code: '+598',
  },
  {
    name: {en: 'Uzbekistan', th: 'อุซเบกิสถาน', cs: '乌兹别克斯坦'},
    flag: '🇺🇿',
    code: 'UZ',
    dial_code: '+998',
  },
  {
    name: {en: 'Vanuatu', th: 'วานูอาตู', cs: '瓦努阿图'},
    flag: '🇻🇺',
    code: 'VU',
    dial_code: '+678',
  },
  {
    name: {
      en: 'Venezuela, Bolivarian Republic of Venezuela',
      th: 'เวเนซุเอลา สาธารณรัฐโบลิวารี',
      cs: '委内瑞拉',
    },
    flag: '🇻🇪',
    code: 'VE',
    dial_code: '+58',
  },
  {
    name: {en: 'Vietnam', th: 'เวียดนาม', cs: '越南'},
    flag: '🇻🇳',
    code: 'VN',
    dial_code: '+84',
  },
  {
    name: {
      en: 'Virgin Islands, British',
      th: 'หมู่เกาะบริติชเวอร์จิน',
      cs: '英属维尔京群岛',
    },
    flag: '🇻🇬',
    code: 'VG',
    dial_code: '+1284',
  },
  {
    name: {
      en: 'Virgin Islands, U.S.',
      th: 'หมู่เกาะเวอร์จินของสหรัฐอเมริกา',
      cs: '美属维尔京群岛',
    },
    flag: '🇻🇮',
    code: 'VI',
    dial_code: '+1340',
  },
  {
    name: {
      en: 'Wallis and Futuna',
      th: 'วาลลิสและฟุตูนา',
      cs: '瓦利斯和富图纳',
    },
    flag: '🇼🇫',
    code: 'WF',
    dial_code: '+681',
  },
  {
    name: {en: 'Yemen', th: 'เยเมน', cs: '也门'},
    flag: '🇾🇪',
    code: 'YE',
    dial_code: '+967',
  },
  {
    name: {en: 'Zambia', th: 'แซมเบีย', cs: '赞比亚'},
    flag: '🇿🇲',
    code: 'ZM',
    dial_code: '+260',
  },
  {
    name: {en: 'Zimbabwe', th: 'ซิมบับเว', cs: '津巴布韦'},
    flag: '🇿🇼',
    code: 'ZW',
    dial_code: '+263',
  },
];

export const DEFAULT_COUNTRY_CODES = COUNTRY_CODE_LISTS[0].dial_code;
