import {StyleSheet} from 'react-native';
import {Colors} from './Colors';

export default StyleSheet.create({
  registrationScrollView: {
    paddingVertical: 60,
    paddingHorizontal: 24,
    width: '100%',
    height: '100%',
    color: Colors.white100,
  },
  textH2Medium: {
    flexShrink: 1,
    fontFamily: 'One Bangkok BETA',
    fontWeight: '500',
    fontSize: 32,
    // lineHeight: 32,
    color: Colors.white100,
  },
  textH3Medium: {
    flexShrink: 1,
    fontFamily: 'One Bangkok BETA',
    fontWeight: '500',
    fontSize: 20,
    // lineHeight: 20,
    letterSpacing: 0.02,
    // color: Colors.white100,
  },
  textB1Medium: {
    flexShrink: 1,
    fontFamily: 'One Bangkok BETA',
    fontWeight: '500',
    fontSize: 16,
    // lineHeight: 19.2,
    color: Colors.white100,
    textAlign: 'center',
  },
  textB1Regular: {
    flexShrink: 1,
    fontFamily: 'One Bangkok BETA',
    fontWeight: '400',
    fontSize: 16,
    // lineHeight: 19.2,
    color: Colors.white100,
  },
  textB2Regular: {
    flexShrink: 1,
    fontFamily: 'One Bangkok BETA',
    fontWeight: '400',
    fontSize: 14,
    // lineHeight: 16.8,
    color: Colors.white100,
  },
  textRegular: {
    flexShrink: 1,
    fontFamily: 'One Bangkok BETA',
    fontWeight: '400',
    fontSize: 16,
    // lineHeight: 18,
    letterSpacing: 0.02,
    color: Colors.white100,
  },
  textB1Bold: {
    flexShrink: 1,
    fontFamily: 'One Bangkok BETA',
    fontWeight: '700',
    fontSize: 16,
    // lineHeight: 19.2,
    color: Colors.white100,
  },
  textB1Light: {
    flexShrink: 1,
    fontFamily: 'One Bangkok BETA',
    fontWeight: '300',
    fontSize: 16,
    // lineHeight: 19.2,
    color: Colors.white100,
  },
  textC1Regular: {
    flexShrink: 1,
    fontFamily: 'One Bangkok BETA',
    fontWeight: '400',
    fontSize: 12,
    // lineHeight: 14.4,
    color: Colors.blue,
  },
  textB1Default: {
    flexShrink: 1,
    fontFamily: 'One Bangkok BETA',
    fontWeight: '300',
    fontSize: 16,
    color: Colors.white100,
  },
});
