package model

import (
	_ "time/tzdata"

	"example.com/art-culture-api/configuration"
)

type RouteItem struct {
	ID          	int    		`json:"id"`
	Time        	int    		`json:"time"`
	Title       	string 		`json:"title"`
	SubTitle    	string 		`json:"subTitle"`
	Description 	string 		`json:"description"`
	Mins        	string 		`json:"mins"`
	Distance    	int    		`json:"distance"`
	Calories    	string 		`json:"calories"`
	Steps       	string 		`json:"steps"`
	Thumbnail   	string 		`json:"thumbnail"`
	Image       	string 		`json:"image"`
	RouteIds		[]string	`json:"routeIds"`
}

func GetRouteItems(config configuration.Config) map[string][]RouteItem {
	// Get the base URL from config
	baseURL := config.Get("OBK_S3_URL")
	
	 
	// Define route items
	return map[string][]RouteItem{
		"en": {
			{1, 10, "Boulevard Recharge Walk", "Recharge Walk",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"10", 460, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-1.png",
				baseURL + "/sustainability/map-en/map-10-mins-en-1.png", 
				[]string{"Route01-A", "Route01-B", "Route01-C", "Route01-D"}},
			{2, 10, "One Bangkok Park Recharge Walk", "Recharge Walk",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"10", 420, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-2.png",
				baseURL + "/sustainability/map-en/map-10-mins-en-2.png", 
				[]string{"Route02-A", "Route02-B", "Route02-C", "Route02-D"}},
			{3, 10, "One Bangkok Park Art & Arbor Walk", "Art & Arbor",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"10", 460, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-3.png",
				baseURL + "/sustainability/map-en/map-10-mins-en-3.png", 
				[]string{"Route03-A", "Route03-B", "Route03-C", "Route03-D", "Route03-E", "Route03-F", "Route03-G"}},
			{4, 15, "Parade Park Art & Arbor Walk", "Art & Arbor",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"15", 540, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-4.png",
				baseURL + "/sustainability/map-en/map-15-mins-en-1.png", 
				[]string{"Route04-A", "Route04-B", "Route04-C", "Route04-D", "Route04-E", "Route04-F", "Route04-G", "Route04-H", "Route04-I", "Route04-J"}},
			{5, 15, "Boulevard & Park Meeting Mile", "Meeting Mile",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"15", 550, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-5.png",
				baseURL + "/sustainability/map-en/map-15-mins-en-2.png", 
				[]string{"Route05-A", "Route05-B", "Route05-C", "Route05-D", "Route05-E", "Route05-F"}},
			{6, 15, "Wireless Heritage Grove Walk", "Heritage Grove Walk",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"15", 615, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-6.png",
				baseURL + "/sustainability/map-en/map-15-mins-en-3.png", 
				[]string{"Route06-A", "Route06-B", "Route06-C", "Route06-D", "Route06-E", "Route06-F", "Route06-G"}},
			{7, 30, "Avenue and Arbor Walk", "Heritage Grove Walk",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"30", 1090, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-7.png",
				baseURL + "/sustainability/map-en/map-30-mins-en-1.png", 
				[]string{"Route07-A", "Route07-B", "Route07-C", "Route07-D", "Route07-E", "Route07-F", "Route07-G", "Route07-H", "Route07-I", "Route07-J", "Route07-K", "Route07-L", "Route07-M", "Route07-N"}},
			// {8, 30, "Complete Green Meeting Mile", "Meeting Mile",
			// 	"Complete Green Experience Route",
			// 	"30", 1172, "210", "4,500",
			// 	baseURL + "/sustainability/map-en/mock-walking-8.png",
			// 	baseURL + "/sustainability/map-en/map-30-mins-en-2.png", 
			// 	[]string{"Route08-A", "Route08-B", "Route08-C", "Route08-D", "Route08-E", "Route08-F", "Route08-G", "Route08-H", "Route08-I", "Route08-A"}},
			// {9, 30, "Complete Green Experience Route", "Complete Green Experience",
			// 	"A scenic route passing through the central park, featuring lush greenery and fountain.",
			// 	"30", 1270, "210", "4,500",
			// 	baseURL + "/sustainability/map-en/mock-walking-9.png",
			// 	baseURL + "/sustainability/map-en/map-30-mins-en-3.png", 
			// 	[]string{"Route05-D", "Route04-B", "Route04-D", "Route04-E", "Route04-F", "Route04-G", "Route04-H", "Route04-I", "Route04-J", "Route04-A", "Route06-E", "Route06-F", "Route06-A", "Route06-B", "Route08-B", "Route08-C", "Route01-C", "Route03-C", "Route03-D", "Route05-D"}},
		},
		"th": {
			{1, 10, "บูเลอวาร์ด รี ชาร์จ วอล์ค", "Recharge Walk",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"10", 460, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-1.png",
				baseURL + "/sustainability/map-en/map-10-mins-en-1.png", 
				[]string{"Route01-A", "Route01-B", "Route01-C", "Route01-D"}},
			{2, 10, "วัน แบงค็อก ปาร์ค รี ชาร์จ วอล์ค", "Recharge Walk",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"10", 420, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-2.png",
				baseURL + "/sustainability/map-en/map-10-mins-en-2.png", 
				[]string{"Route02-A", "Route02-B", "Route02-C", "Route02-D"}},
			{3, 10, "วัน แบงค็อก ปาร์ค อาร์ต & อาร์เบอร์ วอล์ค", "Art & Arbor",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"10", 460, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-3.png",
				baseURL + "/sustainability/map-en/map-10-mins-en-3.png", 
				[]string{"Route03-A", "Route03-B", "Route03-C", "Route03-D", "Route03-E", "Route03-F", "Route03-G"}},
			{4, 15, "พาเหรด ปาร์ค อาร์ต & อาร์เบอร์ วอล์ค", "Art & Arbor",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"15", 540, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-4.png",
				baseURL + "/sustainability/map-en/map-15-mins-en-1.png", 
				[]string{"Route04-A", "Route04-B", "Route04-C", "Route04-D", "Route04-E", "Route04-F", "Route04-G", "Route04-H", "Route04-I", "Route04-J"}},
			{5, 15, "บูเลอวาร์ด & ปาร์ค มีตติ้ง ไมล์", "Meeting Mile",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"15", 550, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-5.png",
				baseURL + "/sustainability/map-en/map-15-mins-en-2.png", 
				[]string{"Route05-A", "Route05-B", "Route05-C", "Route05-D", "Route05-E", "Route05-F"}},
			{6, 15, "พื้นที่สีเขียวรอบ ไวร์เลส เฮาส์ วัน แบงค็อก", "Heritage Grove Walk",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"15", 615, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-6.png",
				baseURL + "/sustainability/map-en/map-15-mins-en-3.png", 
				[]string{"Route06-A", "Route06-B", "Route06-C", "Route06-D", "Route06-E", "Route06-F", "Route06-G"}},
			{7, 30, "อเวนิว & อาร์เบอร์ วอล์ค", "Heritage Grove Walk",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"30", 1090, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-7.png",
				baseURL + "/sustainability/map-en/map-30-mins-en-1.png", 
				[]string{"Route07-A", "Route07-B", "Route07-C", "Route07-D", "Route07-E", "Route07-F", "Route07-G", "Route07-H", "Route07-I", "Route07-J", "Route07-K", "Route07-L", "Route07-M", "Route07-N"}},
			// {8, 30, "พื้นที่สีเขียวรอบ วัน แบงค็อก", "Meeting Mile",
			// 	"Complete Green Experience Route",
			// 	"30", 1172, "210", "4,500",
			// 	baseURL + "/sustainability/map-en/mock-walking-8.png",
			// 	baseURL + "/sustainability/map-en/map-30-mins-en-2.png", 
			// 	[]string{"Route08-A", "Route08-B", "Route08-C", "Route08-D", "Route08-E", "Route08-F", "Route08-G", "Route08-H", "Route08-I", "Route08-A"}},
			// {9, 30, "ประสบการณ์แห่งธรรมชาติ แห่ง วัน แบงค็อก", "Heritage Grove Walk",
			// 	"A scenic route passing through the central park, featuring lush greenery and fountain.",
			// 	"30", 1270, "210", "4,500",
			// 	baseURL + "/sustainability/map-en/mock-walking-9.png",
			// 	baseURL + "/sustainability/map-en/map-30-mins-en-3.png", 
			// 	[]string{"Route05-D", "Route04-B", "Route04-D", "Route04-E", "Route04-F", "Route04-G", "Route04-H", "Route04-I", "Route04-J", "Route04-A", "Route06-E", "Route06-F", "Route06-A", "Route06-B", "Route08-B", "Route08-C", "Route01-C", "Route03-C", "Route03-D", "Route05-D"}},
		},
		"zh": {
			{1, 10, "Boulevard Recharge Walk", "Recharge Walk",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"10", 460, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-1.png",
				baseURL + "/sustainability/map-en/map-10-mins-en-1.png", 
				[]string{"Route01-A", "Route01-B", "Route01-C", "Route01-D"}},
			{2, 10, "One Bangkok Park Recharge Walk", "Recharge Walk",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"10", 420, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-2.png",
				baseURL + "/sustainability/map-en/map-10-mins-en-2.png", 
				[]string{"Route02-A", "Route02-B", "Route02-C", "Route02-D"}},
			{3, 10, "One Bangkok Park Art & Arbor Walk", "Art & Arbor",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"10", 460, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-3.png",
				baseURL + "/sustainability/map-en/map-10-mins-en-3.png", 
				[]string{"Route03-A", "Route03-B", "Route03-C", "Route03-D", "Route03-E", "Route03-F", "Route03-G"}},
			{4, 15, "Parade Park Art & Arbor Walk", "Art & Arbor",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"15", 540, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-4.png",
				baseURL + "/sustainability/map-en/map-15-mins-en-1.png", 
				[]string{"Route04-A", "Route04-B", "Route04-C", "Route04-D", "Route04-E", "Route04-F", "Route04-G", "Route04-H", "Route04-I", "Route04-J"}},
			{5, 15, "Boulevard & Park Meeting Mile", "Meeting Mile",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"15", 550, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-5.png",
				baseURL + "/sustainability/map-en/map-15-mins-en-2.png", 
				[]string{"Route05-A", "Route05-B", "Route05-C", "Route05-D", "Route05-E", "Route05-F"}},
			{6, 15, "Wireless Heritage Grove Walk", "Heritage Grove Walk",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"15", 615, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-6.png",
				baseURL + "/sustainability/map-en/map-15-mins-en-3.png", 
				[]string{"Route06-A", "Route06-B", "Route06-C", "Route06-D", "Route06-E", "Route06-F", "Route06-G"}},
			{7, 30, "Avenue and Arbor Walk", "Heritage Grove Walk",
				"A scenic route passing through the central park, featuring lush greenery and fountain.",
				"30", 1090, "210", "4,500",
				baseURL + "/sustainability/map-en/mock-walking-7.png",
				baseURL + "/sustainability/map-en/map-30-mins-en-1.png", 
				[]string{"Route07-A", "Route07-B", "Route07-C", "Route07-D", "Route07-E", "Route07-F", "Route07-G", "Route07-H", "Route07-I", "Route07-J", "Route07-K", "Route07-L", "Route07-M", "Route07-N"}},
			// {8, 30, "Complete Green Meeting Mile", "Meeting Mile",
			// 	"Complete Green Experience Route",
			// 	"30", 1172, "210", "4,500",
			// 	baseURL + "/sustainability/map-en/mock-walking-8.png",
			// 	baseURL + "/sustainability/map-en/map-30-mins-en-2.png", 
			// 	[]string{"Route08-A", "Route08-B", "Route08-C", "Route08-D", "Route08-E", "Route08-F", "Route08-G", "Route08-H", "Route08-I", "Route08-A"}},
			// {9, 30, "Complete Green Experience Route", "Complete Green Experience",
			// 	"A scenic route passing through the central park, featuring lush greenery and fountain.",
			// 	"30", 1270, "210", "4,500",
			// 	baseURL + "/sustainability/map-en/mock-walking-9.png",
			// 	baseURL + "/sustainability/map-en/map-30-mins-en-3.png", 
			// 	[]string{"Route05-D", "Route04-B", "Route04-D", "Route04-E", "Route04-F", "Route04-G", "Route04-H", "Route04-I", "Route04-J", "Route04-A", "Route06-E", "Route06-F", "Route06-A", "Route06-B", "Route08-B", "Route08-C", "Route01-C", "Route03-C", "Route03-D", "Route05-D"}},
		},
	}
}