/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /** Check health */
    get: operations["health_controller.get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Error: {
      /**
       * @example INTERNAL_SERVER_ERROR 
       * @enum {string}
       */
      code: "BAD_REQUEST" | "NOT_FOUND" | "USER_NOT_FOUND" | "INTERNAL_SERVER_ERROR";
      /** @example error message */
      message: string;
    };
    HealthData: {
      health: boolean;
    };
    HealthResponse: {
      data: components["schemas"]["HealthData"];
    };
  };
  responses: {
    /** @description Health response */
    HealthResponse: {
      content: {
        "application/json": components["schemas"]["HealthResponse"];
      };
    };
    /** @description Unexpected error occurred */
    ErrorResp: {
      content: {
        "application/json": {
          error: components["schemas"]["Error"];
        };
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** Check health */
  "health_controller.get": {
    responses: {
      200: components["responses"]["HealthResponse"];
      400: components["responses"]["ErrorResp"];
      500: components["responses"]["ErrorResp"];
    };
  };
}
