apiVersion: apps/v1
kind: Deployment
metadata:
  name: ob-bus
spec:
  selector:
    matchLabels:
      name: ob-bus
  template:
    metadata:
      labels:
        name: ob-bus
    spec:
      containers:
        - name: ob-bus
          image: 418772626632.dkr.ecr.ap-southeast-1.amazonaws.com/one-bangkok-dev:ob-bus_latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: dev
            - name: DATABASE_URL
              value: postgresql://postgres:2a843c492f23fdbd6d586d0911d275fc@ob-bus-dev.caktmhpgapyr.ap-southeast-1.rds.amazonaws.com/ob_bus_development
            - name: AWS_ACCESS_KEY_ID
              value: AKIAWDAGLFTEC3EVLYNN
            - name: AWS_SECRET_ACCESS_KEY
              value: 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
            - name: AWS_S3_BUCKET_NAME
              value: bucket-ob-bus-dev
            - name: ENABLE_S3_DOWNLOAD
              value: 'true'
            - name: OB_EVENT_CONFIG_PATH
              value: event.config.dev.json
            - name: OB_WEB_SOCKET_URL
              value: 'https://ws.glorymtel.xyz'
            - name: KAFKA_KRAFE_ENABLED
              value: 'true'
            - name: OB_IAM_SDK_BASE_URL
              value: 'https://iam.glorymtel.xyz'
