apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ./ing.yaml
commonLabels:
  app: ob-bus
namePrefix: ob-bus-
namespace: default
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: 730335418784.dkr.ecr.ap-southeast-1.amazonaws.com/ob-bus/sit:latest
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
- patch: |-
    - op: replace
      path: /spec/ports/0/port
      value: 3000
    - op: replace
      path: /spec/ports/0/targetPort
      value: 3000
  target:
    kind: Service
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: DATABASE_URL
          value: postgresql://postgres:2a843c492f23fdbd6d586d0911d275fc@obk-sit-ob-bus.c70qsyku4z3y.ap-southeast-1.rds.amazonaws.com/ob_bus_sit?connection_limit=65&connect_timeout=10
        - name: AWS_ACCESS_KEY_ID
          value: AKIA2UC3CDGQONFWRE4F
        - name: AWS_SECRET_ACCESS_KEY
          value: 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
        - name: OB_IAM_SDK_BASE_URL
          value: 'http://iam-sit.glorymtel.xyz'
        - name: GOOGLEMAP_API_URL
          value: 'https://maps.googleapis.com/maps/api/distancematrix/json'
        - name: GOOGLE_API_KEY
          value: AIzaSyDt0oD3BqU2Y9LSHkxoHl10xSxNH95Kp28
        - name: OB_WEB_SOCKET_URL
          value: 'http://ws-sit.glorymtel.xyz'
  target:
    kind: Deployment
commonAnnotations:
  deploy-timestamp: "1724077808"
images:
- name: 730335418784.dkr.ecr.ap-southeast-1.amazonaws.com/ob-bus/sit
  newTag: latest
