apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
# - ing.yaml

commonLabels:
  app: ob-kafka

namePrefix: ob-kafka-

configMapGenerator:
  - literals:
      - NODE_ENV=uat
    name: configmap

patches:
  - patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: https://github.com/mtel-thailand/one-bangkok
      - op: replace
        path: /spec/source/targetRevision
        value: main
      - op: replace
        path: /spec/source/path
        value: infra/kafka/k8s/uat
    target:
      kind: Application
  - patch: |-
      - op: replace
        path: /stringData/url
        value: https://github.com/mtel-thailand/one-bangkok
    target:
      kind: Secret
