apiVersion: batch/v1
kind: CronJob
metadata:
  name: ob-iam-cronjob-delete-expired-otp
  labels:
    app: ob-iam-cronjob-delete-expired-otp
spec:
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  schedule: '0 0 * * *' # Run at 00:00 (midnight) every day
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ob-iam-cronjob-delete-expired-otp
        spec:
          restartPolicy: Never
          containers:
            - name: bash
              image: curlimages/curl:7.70.0
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - 'curl -X POST https://dev.glorymtel.xyz/ob-iam/task/delete_expired_otp -H "accept: application/json"'
