import FSParkingClient from '../../src/libs/fs_parking_client';

let spy: any;

afterEach(() => {
  spy && spy.mockRestore();
});

const MOCK_PARKING_DATA_RESPONSE = [
  {
    id: 4,
    createdAt: '2024-01-28T07:06:54.446Z',
    updatedAt: '2024-01-28T07:06:54.446Z',
    deletedAt: null,
    name: 'Building 1',
    floors: [
      {
        id: 197492,
        createdAt: '2024-01-28T07:06:54.990Z',
        updatedAt: '2024-01-28T07:06:54.990Z',
        deletedAt: null,
        name: 'L1',
        buildingId: 4,
        zones: [
          {
            id: 1,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P1',
            floorId: 197492,
            totalSpot: 70,
            availableSpot: 28,
            unavailableSpot: 45,
            reserveSpot: -3,
            types: [
              {
                type: 'VIP1',
                totalSpot: 38,
                availableSpot: 83,
                unavailableSpot: 93,
                reserveSpot: -138,
              },
              {
                type: 'VIP2',
                totalSpot: 70,
                availableSpot: 93,
                unavailableSpot: 45,
                reserveSpot: -68,
              },
              {
                type: 'VIP3',
                totalSpot: 12,
                availableSpot: 61,
                unavailableSpot: 95,
                reserveSpot: -144,
              },
              {
                type: 'HADICAP',
                totalSpot: 54,
                availableSpot: 95,
                unavailableSpot: 88,
                reserveSpot: -129,
              },
              {
                type: 'LAY',
                totalSpot: 24,
                availableSpot: 52,
                unavailableSpot: 26,
                reserveSpot: -54,
              },
            ],
          },
          {
            id: 2,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P2',
            floorId: 197492,
            totalSpot: 33,
            availableSpot: 50,
            unavailableSpot: 10,
            reserveSpot: -27,
            types: [
              {
                type: 'VIP1',
                totalSpot: 21,
                availableSpot: 50,
                unavailableSpot: 98,
                reserveSpot: -127,
              },
              {
                type: 'VIP2',
                totalSpot: 77,
                availableSpot: 59,
                unavailableSpot: 23,
                reserveSpot: -5,
              },
              {
                type: 'VIP3',
                totalSpot: 95,
                availableSpot: 2,
                unavailableSpot: 70,
                reserveSpot: 23,
              },
              {
                type: 'HADICAP',
                totalSpot: 85,
                availableSpot: 16,
                unavailableSpot: 43,
                reserveSpot: 26,
              },
              {
                type: 'LAY',
                totalSpot: 73,
                availableSpot: 38,
                unavailableSpot: 60,
                reserveSpot: -25,
              },
            ],
          },
          {
            id: 3,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P3',
            floorId: 197492,
            totalSpot: 38,
            availableSpot: 98,
            unavailableSpot: 26,
            reserveSpot: -86,
            types: [
              {
                type: 'VIP1',
                totalSpot: 52,
                availableSpot: 11,
                unavailableSpot: 57,
                reserveSpot: -16,
              },
              {
                type: 'VIP2',
                totalSpot: 42,
                availableSpot: 71,
                unavailableSpot: 39,
                reserveSpot: -68,
              },
              {
                type: 'VIP3',
                totalSpot: 70,
                availableSpot: 84,
                unavailableSpot: 15,
                reserveSpot: -29,
              },
              {
                type: 'HADICAP',
                totalSpot: 13,
                availableSpot: 100,
                unavailableSpot: 10,
                reserveSpot: -97,
              },
              {
                type: 'LAY',
                totalSpot: 48,
                availableSpot: 51,
                unavailableSpot: 59,
                reserveSpot: -62,
              },
            ],
          },
          {
            id: 4,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P4',
            floorId: 197492,
            totalSpot: 62,
            availableSpot: 94,
            unavailableSpot: 79,
            reserveSpot: -111,
            types: [
              {
                type: 'VIP1',
                totalSpot: 57,
                availableSpot: 37,
                unavailableSpot: 34,
                reserveSpot: -14,
              },
              {
                type: 'VIP2',
                totalSpot: 17,
                availableSpot: 12,
                unavailableSpot: 13,
                reserveSpot: -8,
              },
              {
                type: 'VIP3',
                totalSpot: 71,
                availableSpot: 97,
                unavailableSpot: 37,
                reserveSpot: -63,
              },
              {
                type: 'HADICAP',
                totalSpot: 57,
                availableSpot: 59,
                unavailableSpot: 59,
                reserveSpot: -61,
              },
              {
                type: 'LAY',
                totalSpot: 86,
                availableSpot: 50,
                unavailableSpot: 64,
                reserveSpot: -28,
              },
            ],
          },
          {
            id: 5,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P5',
            floorId: 197492,
            totalSpot: 13,
            availableSpot: 36,
            unavailableSpot: 6,
            reserveSpot: -29,
            types: [
              {
                type: 'VIP1',
                totalSpot: 30,
                availableSpot: 1,
                unavailableSpot: 82,
                reserveSpot: -53,
              },
              {
                type: 'VIP2',
                totalSpot: 48,
                availableSpot: 73,
                unavailableSpot: 86,
                reserveSpot: -111,
              },
              {
                type: 'VIP3',
                totalSpot: 97,
                availableSpot: 57,
                unavailableSpot: 76,
                reserveSpot: -36,
              },
              {
                type: 'HADICAP',
                totalSpot: 55,
                availableSpot: 31,
                unavailableSpot: 46,
                reserveSpot: -22,
              },
              {
                type: 'LAY',
                totalSpot: 90,
                availableSpot: 99,
                unavailableSpot: 63,
                reserveSpot: -72,
              },
            ],
          },
          {
            id: 6,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P6',
            floorId: 197492,
            totalSpot: 21,
            availableSpot: 72,
            unavailableSpot: 59,
            reserveSpot: -110,
            types: [
              {
                type: 'VIP1',
                totalSpot: 79,
                availableSpot: 84,
                unavailableSpot: 40,
                reserveSpot: -45,
              },
              {
                type: 'VIP2',
                totalSpot: 76,
                availableSpot: 53,
                unavailableSpot: 19,
                reserveSpot: 4,
              },
              {
                type: 'VIP3',
                totalSpot: 40,
                availableSpot: 2,
                unavailableSpot: 33,
                reserveSpot: 5,
              },
              {
                type: 'HADICAP',
                totalSpot: 90,
                availableSpot: 13,
                unavailableSpot: 43,
                reserveSpot: 34,
              },
              {
                type: 'LAY',
                totalSpot: 55,
                availableSpot: 44,
                unavailableSpot: 78,
                reserveSpot: -67,
              },
            ],
          },
        ],
        totalSpot: 55,
        availableSpot: 73,
        unavailableSpot: 6,
        reserveSpot: -24,
      },
      {
        id: 197493,
        createdAt: '2024-01-28T07:06:54.991Z',
        updatedAt: '2024-01-28T07:06:54.991Z',
        deletedAt: null,
        name: 'B4',
        buildingId: 4,
        zones: [
          {
            id: 7,
            createdAt: '2024-01-28T07:06:54.991Z',
            updatedAt: '2024-01-28T07:06:54.991Z',
            deletedAt: null,
            name: 'P1',
            floorId: 197493,
            totalSpot: 79,
            availableSpot: 69,
            unavailableSpot: 56,
            reserveSpot: -46,
            types: [
              {
                type: 'VIP1',
                totalSpot: 63,
                availableSpot: 46,
                unavailableSpot: 18,
                reserveSpot: -1,
              },
              {
                type: 'VIP2',
                totalSpot: 99,
                availableSpot: 48,
                unavailableSpot: 19,
                reserveSpot: 32,
              },
              {
                type: 'VIP3',
                totalSpot: 90,
                availableSpot: 21,
                unavailableSpot: 58,
                reserveSpot: 11,
              },
              {
                type: 'HADICAP',
                totalSpot: 12,
                availableSpot: 36,
                unavailableSpot: 14,
                reserveSpot: -38,
              },
              {
                type: 'LAY',
                totalSpot: 37,
                availableSpot: 24,
                unavailableSpot: 60,
                reserveSpot: -47,
              },
            ],
          },
          {
            id: 8,
            createdAt: '2024-01-28T07:06:54.991Z',
            updatedAt: '2024-01-28T07:06:54.991Z',
            deletedAt: null,
            name: 'P2',
            floorId: 197493,
            totalSpot: 90,
            availableSpot: 47,
            unavailableSpot: 25,
            reserveSpot: 18,
            types: [
              {
                type: 'VIP1',
                totalSpot: 93,
                availableSpot: 14,
                unavailableSpot: 17,
                reserveSpot: 62,
              },
              {
                type: 'VIP2',
                totalSpot: 68,
                availableSpot: 15,
                unavailableSpot: 23,
                reserveSpot: 30,
              },
              {
                type: 'VIP3',
                totalSpot: 26,
                availableSpot: 24,
                unavailableSpot: 10,
                reserveSpot: -8,
              },
              {
                type: 'HADICAP',
                totalSpot: 27,
                availableSpot: 37,
                unavailableSpot: 13,
                reserveSpot: -23,
              },
              {
                type: 'LAY',
                totalSpot: 93,
                availableSpot: 81,
                unavailableSpot: 74,
                reserveSpot: -62,
              },
            ],
          },
          {
            id: 9,
            createdAt: '2024-01-28T07:06:54.991Z',
            updatedAt: '2024-01-28T07:06:54.991Z',
            deletedAt: null,
            name: 'P3',
            floorId: 197493,
            totalSpot: 78,
            availableSpot: 49,
            unavailableSpot: 81,
            reserveSpot: -52,
            types: [
              {
                type: 'VIP1',
                totalSpot: 84,
                availableSpot: 48,
                unavailableSpot: 44,
                reserveSpot: -8,
              },
              {
                type: 'VIP2',
                totalSpot: 74,
                availableSpot: 82,
                unavailableSpot: 20,
                reserveSpot: -28,
              },
              {
                type: 'VIP3',
                totalSpot: 38,
                availableSpot: 62,
                unavailableSpot: 30,
                reserveSpot: -54,
              },
              {
                type: 'HADICAP',
                totalSpot: 27,
                availableSpot: 38,
                unavailableSpot: 34,
                reserveSpot: -45,
              },
              {
                type: 'LAY',
                totalSpot: 22,
                availableSpot: 91,
                unavailableSpot: 39,
                reserveSpot: -108,
              },
            ],
          },
          {
            id: 10,
            createdAt: '2024-01-28T07:06:54.991Z',
            updatedAt: '2024-01-28T07:06:54.991Z',
            deletedAt: null,
            name: 'P4',
            floorId: 197493,
            totalSpot: 56,
            availableSpot: 15,
            unavailableSpot: 61,
            reserveSpot: -20,
            types: [
              {
                type: 'VIP1',
                totalSpot: 97,
                availableSpot: 15,
                unavailableSpot: 56,
                reserveSpot: 26,
              },
              {
                type: 'VIP2',
                totalSpot: 12,
                availableSpot: 62,
                unavailableSpot: 89,
                reserveSpot: -139,
              },
              {
                type: 'VIP3',
                totalSpot: 13,
                availableSpot: 24,
                unavailableSpot: 49,
                reserveSpot: -60,
              },
              {
                type: 'HADICAP',
                totalSpot: 39,
                availableSpot: 24,
                unavailableSpot: 38,
                reserveSpot: -23,
              },
              {
                type: 'LAY',
                totalSpot: 13,
                availableSpot: 6,
                unavailableSpot: 49,
                reserveSpot: -42,
              },
            ],
          },
          {
            id: 11,
            createdAt: '2024-01-28T07:06:54.991Z',
            updatedAt: '2024-01-28T07:06:54.991Z',
            deletedAt: null,
            name: 'P5',
            floorId: 197493,
            totalSpot: 94,
            availableSpot: 51,
            unavailableSpot: 37,
            reserveSpot: 6,
            types: [
              {
                type: 'VIP1',
                totalSpot: 35,
                availableSpot: 59,
                unavailableSpot: 58,
                reserveSpot: -82,
              },
              {
                type: 'VIP2',
                totalSpot: 68,
                availableSpot: 97,
                unavailableSpot: 48,
                reserveSpot: -77,
              },
              {
                type: 'VIP3',
                totalSpot: 55,
                availableSpot: 70,
                unavailableSpot: 39,
                reserveSpot: -54,
              },
              {
                type: 'HADICAP',
                totalSpot: 46,
                availableSpot: 90,
                unavailableSpot: 56,
                reserveSpot: -100,
              },
              {
                type: 'LAY',
                totalSpot: 80,
                availableSpot: 94,
                unavailableSpot: 8,
                reserveSpot: -22,
              },
            ],
          },
          {
            id: 12,
            createdAt: '2024-01-28T07:06:54.991Z',
            updatedAt: '2024-01-28T07:06:54.991Z',
            deletedAt: null,
            name: 'P6',
            floorId: 197493,
            totalSpot: 66,
            availableSpot: 21,
            unavailableSpot: 65,
            reserveSpot: -20,
            types: [
              {
                type: 'VIP1',
                totalSpot: 73,
                availableSpot: 29,
                unavailableSpot: 7,
                reserveSpot: 37,
              },
              {
                type: 'VIP2',
                totalSpot: 79,
                availableSpot: 58,
                unavailableSpot: 67,
                reserveSpot: -46,
              },
              {
                type: 'VIP3',
                totalSpot: 95,
                availableSpot: 6,
                unavailableSpot: 58,
                reserveSpot: 31,
              },
              {
                type: 'HADICAP',
                totalSpot: 27,
                availableSpot: 48,
                unavailableSpot: 7,
                reserveSpot: -28,
              },
              {
                type: 'LAY',
                totalSpot: 30,
                availableSpot: 8,
                unavailableSpot: 65,
                reserveSpot: -43,
              },
            ],
          },
        ],
        totalSpot: 77,
        availableSpot: 32,
        unavailableSpot: 36,
        reserveSpot: 9,
      },
      {
        id: 197494,
        createdAt: '2024-01-28T07:06:54.991Z',
        updatedAt: '2024-01-28T07:06:54.991Z',
        deletedAt: null,
        name: 'B3',
        buildingId: 4,
        zones: [
          {
            id: 13,
            createdAt: '2024-01-28T07:06:54.991Z',
            updatedAt: '2024-01-28T07:06:54.991Z',
            deletedAt: null,
            name: 'P1',
            floorId: 197494,
            totalSpot: 14,
            availableSpot: 73,
            unavailableSpot: 10,
            reserveSpot: -69,
            types: [
              {
                type: 'VIP1',
                totalSpot: 22,
                availableSpot: 76,
                unavailableSpot: 71,
                reserveSpot: -125,
              },
              {
                type: 'VIP2',
                totalSpot: 89,
                availableSpot: 47,
                unavailableSpot: 13,
                reserveSpot: 29,
              },
              {
                type: 'VIP3',
                totalSpot: 73,
                availableSpot: 20,
                unavailableSpot: 90,
                reserveSpot: -37,
              },
              {
                type: 'HADICAP',
                totalSpot: 13,
                availableSpot: 68,
                unavailableSpot: 82,
                reserveSpot: -137,
              },
              {
                type: 'LAY',
                totalSpot: 36,
                availableSpot: 73,
                unavailableSpot: 8,
                reserveSpot: -45,
              },
            ],
          },
          {
            id: 14,
            createdAt: '2024-01-28T07:06:54.991Z',
            updatedAt: '2024-01-28T07:06:54.991Z',
            deletedAt: null,
            name: 'P2',
            floorId: 197494,
            totalSpot: 52,
            availableSpot: 44,
            unavailableSpot: 2,
            reserveSpot: 6,
            types: [
              {
                type: 'VIP1',
                totalSpot: 100,
                availableSpot: 13,
                unavailableSpot: 37,
                reserveSpot: 50,
              },
              {
                type: 'VIP2',
                totalSpot: 8,
                availableSpot: 73,
                unavailableSpot: 66,
                reserveSpot: -131,
              },
              {
                type: 'VIP3',
                totalSpot: 22,
                availableSpot: 66,
                unavailableSpot: 30,
                reserveSpot: -74,
              },
              {
                type: 'HADICAP',
                totalSpot: 36,
                availableSpot: 27,
                unavailableSpot: 81,
                reserveSpot: -72,
              },
              {
                type: 'LAY',
                totalSpot: 36,
                availableSpot: 57,
                unavailableSpot: 81,
                reserveSpot: -102,
              },
            ],
          },
          {
            id: 15,
            createdAt: '2024-01-28T07:06:54.991Z',
            updatedAt: '2024-01-28T07:06:54.991Z',
            deletedAt: null,
            name: 'P3',
            floorId: 197494,
            totalSpot: 34,
            availableSpot: 20,
            unavailableSpot: 68,
            reserveSpot: -54,
            types: [
              {
                type: 'VIP1',
                totalSpot: 76,
                availableSpot: 47,
                unavailableSpot: 73,
                reserveSpot: -44,
              },
              {
                type: 'VIP2',
                totalSpot: 86,
                availableSpot: 4,
                unavailableSpot: 81,
                reserveSpot: 1,
              },
              {
                type: 'VIP3',
                totalSpot: 14,
                availableSpot: 44,
                unavailableSpot: 17,
                reserveSpot: -47,
              },
              {
                type: 'HADICAP',
                totalSpot: 9,
                availableSpot: 20,
                unavailableSpot: 99,
                reserveSpot: -110,
              },
              {
                type: 'LAY',
                totalSpot: 32,
                availableSpot: 21,
                unavailableSpot: 31,
                reserveSpot: -20,
              },
            ],
          },
          {
            id: 16,
            createdAt: '2024-01-28T07:06:54.991Z',
            updatedAt: '2024-01-28T07:06:54.991Z',
            deletedAt: null,
            name: 'P4',
            floorId: 197494,
            totalSpot: 49,
            availableSpot: 13,
            unavailableSpot: 46,
            reserveSpot: -10,
            types: [
              {
                type: 'VIP1',
                totalSpot: 79,
                availableSpot: 82,
                unavailableSpot: 34,
                reserveSpot: -37,
              },
              {
                type: 'VIP2',
                totalSpot: 77,
                availableSpot: 9,
                unavailableSpot: 52,
                reserveSpot: 16,
              },
              {
                type: 'VIP3',
                totalSpot: 72,
                availableSpot: 72,
                unavailableSpot: 85,
                reserveSpot: -85,
              },
              {
                type: 'HADICAP',
                totalSpot: 22,
                availableSpot: 10,
                unavailableSpot: 68,
                reserveSpot: -56,
              },
              {
                type: 'LAY',
                totalSpot: 39,
                availableSpot: 85,
                unavailableSpot: 13,
                reserveSpot: -59,
              },
            ],
          },
          {
            id: 17,
            createdAt: '2024-01-28T07:06:54.991Z',
            updatedAt: '2024-01-28T07:06:54.991Z',
            deletedAt: null,
            name: 'P5',
            floorId: 197494,
            totalSpot: 65,
            availableSpot: 20,
            unavailableSpot: 72,
            reserveSpot: -27,
            types: [
              {
                type: 'VIP1',
                totalSpot: 72,
                availableSpot: 83,
                unavailableSpot: 6,
                reserveSpot: -17,
              },
              {
                type: 'VIP2',
                totalSpot: 96,
                availableSpot: 65,
                unavailableSpot: 13,
                reserveSpot: 18,
              },
              {
                type: 'VIP3',
                totalSpot: 88,
                availableSpot: 61,
                unavailableSpot: 84,
                reserveSpot: -57,
              },
              {
                type: 'HADICAP',
                totalSpot: 68,
                availableSpot: 56,
                unavailableSpot: 33,
                reserveSpot: -21,
              },
              {
                type: 'LAY',
                totalSpot: 5,
                availableSpot: 52,
                unavailableSpot: 9,
                reserveSpot: -56,
              },
            ],
          },
          {
            id: 18,
            createdAt: '2024-01-28T07:06:54.991Z',
            updatedAt: '2024-01-28T07:06:54.991Z',
            deletedAt: null,
            name: 'P6',
            floorId: 197494,
            totalSpot: 7,
            availableSpot: 27,
            unavailableSpot: 93,
            reserveSpot: -113,
            types: [
              {
                type: 'VIP1',
                totalSpot: 31,
                availableSpot: 57,
                unavailableSpot: 51,
                reserveSpot: -77,
              },
              {
                type: 'VIP2',
                totalSpot: 11,
                availableSpot: 78,
                unavailableSpot: 15,
                reserveSpot: -82,
              },
              {
                type: 'VIP3',
                totalSpot: 22,
                availableSpot: 8,
                unavailableSpot: 78,
                reserveSpot: -64,
              },
              {
                type: 'HADICAP',
                totalSpot: 41,
                availableSpot: 76,
                unavailableSpot: 4,
                reserveSpot: -39,
              },
              {
                type: 'LAY',
                totalSpot: 51,
                availableSpot: 21,
                unavailableSpot: 20,
                reserveSpot: 10,
              },
            ],
          },
        ],
        totalSpot: 42,
        availableSpot: 100,
        unavailableSpot: 43,
        reserveSpot: -101,
      },
      {
        id: 197495,
        createdAt: '2024-01-28T07:06:54.990Z',
        updatedAt: '2024-01-28T07:06:54.990Z',
        deletedAt: null,
        name: 'G',
        buildingId: 4,
        zones: [
          {
            id: 20,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P1',
            floorId: 197495,
            totalSpot: 23,
            availableSpot: 56,
            unavailableSpot: 77,
            reserveSpot: -110,
            types: [
              {
                type: 'VIP1',
                totalSpot: 98,
                availableSpot: 32,
                unavailableSpot: 50,
                reserveSpot: 16,
              },
              {
                type: 'VIP2',
                totalSpot: 94,
                availableSpot: 18,
                unavailableSpot: 76,
                reserveSpot: 0,
              },
              {
                type: 'VIP3',
                totalSpot: 10,
                availableSpot: 88,
                unavailableSpot: 75,
                reserveSpot: -153,
              },
              {
                type: 'HADICAP',
                totalSpot: 55,
                availableSpot: 62,
                unavailableSpot: 20,
                reserveSpot: -27,
              },
              {
                type: 'LAY',
                totalSpot: 51,
                availableSpot: 92,
                unavailableSpot: 93,
                reserveSpot: -134,
              },
            ],
          },
          {
            id: 22,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P2',
            floorId: 197495,
            totalSpot: 25,
            availableSpot: 53,
            unavailableSpot: 16,
            reserveSpot: -44,
            types: [
              {
                type: 'VIP1',
                totalSpot: 79,
                availableSpot: 22,
                unavailableSpot: 75,
                reserveSpot: -18,
              },
              {
                type: 'VIP2',
                totalSpot: 60,
                availableSpot: 96,
                unavailableSpot: 66,
                reserveSpot: -102,
              },
              {
                type: 'VIP3',
                totalSpot: 85,
                availableSpot: 95,
                unavailableSpot: 62,
                reserveSpot: -72,
              },
              {
                type: 'HADICAP',
                totalSpot: 10,
                availableSpot: 81,
                unavailableSpot: 94,
                reserveSpot: -165,
              },
              {
                type: 'LAY',
                totalSpot: 31,
                availableSpot: 36,
                unavailableSpot: 88,
                reserveSpot: -93,
              },
            ],
          },
          {
            id: 25,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P3',
            floorId: 197495,
            totalSpot: 3,
            availableSpot: 35,
            unavailableSpot: 13,
            reserveSpot: -45,
            types: [
              {
                type: 'VIP1',
                totalSpot: 42,
                availableSpot: 33,
                unavailableSpot: 78,
                reserveSpot: -69,
              },
              {
                type: 'VIP2',
                totalSpot: 42,
                availableSpot: 43,
                unavailableSpot: 26,
                reserveSpot: -27,
              },
              {
                type: 'VIP3',
                totalSpot: 81,
                availableSpot: 37,
                unavailableSpot: 12,
                reserveSpot: 32,
              },
              {
                type: 'HADICAP',
                totalSpot: 90,
                availableSpot: 90,
                unavailableSpot: 73,
                reserveSpot: -73,
              },
              {
                type: 'LAY',
                totalSpot: 84,
                availableSpot: 16,
                unavailableSpot: 5,
                reserveSpot: 63,
              },
            ],
          },
          {
            id: 28,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P4',
            floorId: 197495,
            totalSpot: 6,
            availableSpot: 16,
            unavailableSpot: 98,
            reserveSpot: -108,
            types: [
              {
                type: 'VIP1',
                totalSpot: 38,
                availableSpot: 40,
                unavailableSpot: 87,
                reserveSpot: -89,
              },
              {
                type: 'VIP2',
                totalSpot: 42,
                availableSpot: 38,
                unavailableSpot: 53,
                reserveSpot: -49,
              },
              {
                type: 'VIP3',
                totalSpot: 89,
                availableSpot: 10,
                unavailableSpot: 81,
                reserveSpot: -2,
              },
              {
                type: 'HADICAP',
                totalSpot: 86,
                availableSpot: 16,
                unavailableSpot: 100,
                reserveSpot: -30,
              },
              {
                type: 'LAY',
                totalSpot: 63,
                availableSpot: 12,
                unavailableSpot: 53,
                reserveSpot: -2,
              },
            ],
          },
          {
            id: 30,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P5',
            floorId: 197495,
            totalSpot: 52,
            availableSpot: 3,
            unavailableSpot: 2,
            reserveSpot: 47,
            types: [
              {
                type: 'VIP1',
                totalSpot: 69,
                availableSpot: 53,
                unavailableSpot: 31,
                reserveSpot: -15,
              },
              {
                type: 'VIP2',
                totalSpot: 42,
                availableSpot: 84,
                unavailableSpot: 49,
                reserveSpot: -91,
              },
              {
                type: 'VIP3',
                totalSpot: 36,
                availableSpot: 16,
                unavailableSpot: 97,
                reserveSpot: -77,
              },
              {
                type: 'HADICAP',
                totalSpot: 95,
                availableSpot: 35,
                unavailableSpot: 7,
                reserveSpot: 53,
              },
              {
                type: 'LAY',
                totalSpot: 80,
                availableSpot: 43,
                unavailableSpot: 75,
                reserveSpot: -38,
              },
            ],
          },
          {
            id: 31,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P6',
            floorId: 197495,
            totalSpot: 54,
            availableSpot: 71,
            unavailableSpot: 17,
            reserveSpot: -34,
            types: [
              {
                type: 'VIP1',
                totalSpot: 78,
                availableSpot: 38,
                unavailableSpot: 2,
                reserveSpot: 38,
              },
              {
                type: 'VIP2',
                totalSpot: 38,
                availableSpot: 90,
                unavailableSpot: 10,
                reserveSpot: -62,
              },
              {
                type: 'VIP3',
                totalSpot: 11,
                availableSpot: 2,
                unavailableSpot: 60,
                reserveSpot: -51,
              },
              {
                type: 'HADICAP',
                totalSpot: 81,
                availableSpot: 62,
                unavailableSpot: 58,
                reserveSpot: -39,
              },
              {
                type: 'LAY',
                totalSpot: 90,
                availableSpot: 53,
                unavailableSpot: 22,
                reserveSpot: 15,
              },
            ],
          },
        ],
        totalSpot: 24,
        availableSpot: 22,
        unavailableSpot: 91,
        reserveSpot: -89,
      },
      {
        id: 197496,
        createdAt: '2024-01-28T07:06:54.990Z',
        updatedAt: '2024-01-28T07:06:54.990Z',
        deletedAt: null,
        name: 'B1',
        buildingId: 4,
        zones: [
          {
            id: 19,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P1',
            floorId: 197496,
            totalSpot: 75,
            availableSpot: 91,
            unavailableSpot: 89,
            reserveSpot: -105,
            types: [
              {
                type: 'VIP1',
                totalSpot: 69,
                availableSpot: 23,
                unavailableSpot: 71,
                reserveSpot: -25,
              },
              {
                type: 'VIP2',
                totalSpot: 95,
                availableSpot: 22,
                unavailableSpot: 66,
                reserveSpot: 7,
              },
              {
                type: 'VIP3',
                totalSpot: 57,
                availableSpot: 45,
                unavailableSpot: 18,
                reserveSpot: -6,
              },
              {
                type: 'HADICAP',
                totalSpot: 63,
                availableSpot: 55,
                unavailableSpot: 83,
                reserveSpot: -75,
              },
              {
                type: 'LAY',
                totalSpot: 72,
                availableSpot: 8,
                unavailableSpot: 52,
                reserveSpot: 12,
              },
            ],
          },
          {
            id: 23,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P2',
            floorId: 197496,
            totalSpot: 28,
            availableSpot: 9,
            unavailableSpot: 54,
            reserveSpot: -35,
            types: [
              {
                type: 'VIP1',
                totalSpot: 71,
                availableSpot: 95,
                unavailableSpot: 6,
                reserveSpot: -30,
              },
              {
                type: 'VIP2',
                totalSpot: 11,
                availableSpot: 4,
                unavailableSpot: 70,
                reserveSpot: -63,
              },
              {
                type: 'VIP3',
                totalSpot: 52,
                availableSpot: 72,
                unavailableSpot: 40,
                reserveSpot: -60,
              },
              {
                type: 'HADICAP',
                totalSpot: 48,
                availableSpot: 23,
                unavailableSpot: 98,
                reserveSpot: -73,
              },
              {
                type: 'LAY',
                totalSpot: 32,
                availableSpot: 23,
                unavailableSpot: 53,
                reserveSpot: -44,
              },
            ],
          },
          {
            id: 24,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P3',
            floorId: 197496,
            totalSpot: 68,
            availableSpot: 5,
            unavailableSpot: 33,
            reserveSpot: 30,
            types: [
              {
                type: 'VIP1',
                totalSpot: 30,
                availableSpot: 24,
                unavailableSpot: 3,
                reserveSpot: 3,
              },
              {
                type: 'VIP2',
                totalSpot: 40,
                availableSpot: 31,
                unavailableSpot: 53,
                reserveSpot: -44,
              },
              {
                type: 'VIP3',
                totalSpot: 16,
                availableSpot: 16,
                unavailableSpot: 5,
                reserveSpot: -5,
              },
              {
                type: 'HADICAP',
                totalSpot: 73,
                availableSpot: 29,
                unavailableSpot: 75,
                reserveSpot: -31,
              },
              {
                type: 'LAY',
                totalSpot: 65,
                availableSpot: 39,
                unavailableSpot: 57,
                reserveSpot: -31,
              },
            ],
          },
          {
            id: 27,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P4',
            floorId: 197496,
            totalSpot: 55,
            availableSpot: 27,
            unavailableSpot: 20,
            reserveSpot: 8,
            types: [
              {
                type: 'VIP1',
                totalSpot: 67,
                availableSpot: 53,
                unavailableSpot: 77,
                reserveSpot: -63,
              },
              {
                type: 'VIP2',
                totalSpot: 88,
                availableSpot: 89,
                unavailableSpot: 2,
                reserveSpot: -3,
              },
              {
                type: 'VIP3',
                totalSpot: 38,
                availableSpot: 54,
                unavailableSpot: 44,
                reserveSpot: -60,
              },
              {
                type: 'HADICAP',
                totalSpot: 26,
                availableSpot: 32,
                unavailableSpot: 33,
                reserveSpot: -39,
              },
              {
                type: 'LAY',
                totalSpot: 28,
                availableSpot: 67,
                unavailableSpot: 99,
                reserveSpot: -138,
              },
            ],
          },
          {
            id: 34,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P5',
            floorId: 197496,
            totalSpot: 25,
            availableSpot: 32,
            unavailableSpot: 41,
            reserveSpot: -48,
            types: [
              {
                type: 'VIP1',
                totalSpot: 79,
                availableSpot: 64,
                unavailableSpot: 57,
                reserveSpot: -42,
              },
              {
                type: 'VIP2',
                totalSpot: 3,
                availableSpot: 10,
                unavailableSpot: 61,
                reserveSpot: -68,
              },
              {
                type: 'VIP3',
                totalSpot: 92,
                availableSpot: 26,
                unavailableSpot: 36,
                reserveSpot: 30,
              },
              {
                type: 'HADICAP',
                totalSpot: 8,
                availableSpot: 68,
                unavailableSpot: 72,
                reserveSpot: -132,
              },
              {
                type: 'LAY',
                totalSpot: 1,
                availableSpot: 69,
                unavailableSpot: 11,
                reserveSpot: -79,
              },
            ],
          },
          {
            id: 36,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P6',
            floorId: 197496,
            totalSpot: 8,
            availableSpot: 41,
            unavailableSpot: 97,
            reserveSpot: -130,
            types: [
              {
                type: 'VIP1',
                totalSpot: 90,
                availableSpot: 25,
                unavailableSpot: 23,
                reserveSpot: 42,
              },
              {
                type: 'VIP2',
                totalSpot: 78,
                availableSpot: 1,
                unavailableSpot: 12,
                reserveSpot: 65,
              },
              {
                type: 'VIP3',
                totalSpot: 82,
                availableSpot: 20,
                unavailableSpot: 94,
                reserveSpot: -32,
              },
              {
                type: 'HADICAP',
                totalSpot: 34,
                availableSpot: 88,
                unavailableSpot: 75,
                reserveSpot: -129,
              },
              {
                type: 'LAY',
                totalSpot: 15,
                availableSpot: 82,
                unavailableSpot: 67,
                reserveSpot: -134,
              },
            ],
          },
        ],
        totalSpot: 10,
        availableSpot: 34,
        unavailableSpot: 76,
        reserveSpot: -100,
      },
      {
        id: 197497,
        createdAt: '2024-01-28T07:06:54.990Z',
        updatedAt: '2024-01-28T07:06:54.990Z',
        deletedAt: null,
        name: 'B2',
        buildingId: 4,
        zones: [
          {
            id: 21,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P1',
            floorId: 197497,
            totalSpot: 41,
            availableSpot: 52,
            unavailableSpot: 81,
            reserveSpot: -92,
            types: [
              {
                type: 'VIP1',
                totalSpot: 44,
                availableSpot: 13,
                unavailableSpot: 16,
                reserveSpot: 15,
              },
              {
                type: 'VIP2',
                totalSpot: 27,
                availableSpot: 74,
                unavailableSpot: 4,
                reserveSpot: -51,
              },
              {
                type: 'VIP3',
                totalSpot: 9,
                availableSpot: 88,
                unavailableSpot: 64,
                reserveSpot: -143,
              },
              {
                type: 'HADICAP',
                totalSpot: 26,
                availableSpot: 83,
                unavailableSpot: 75,
                reserveSpot: -132,
              },
              {
                type: 'LAY',
                totalSpot: 67,
                availableSpot: 60,
                unavailableSpot: 91,
                reserveSpot: -84,
              },
            ],
          },
          {
            id: 26,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P2',
            floorId: 197497,
            totalSpot: 11,
            availableSpot: 81,
            unavailableSpot: 90,
            reserveSpot: -160,
            types: [
              {
                type: 'VIP1',
                totalSpot: 49,
                availableSpot: 59,
                unavailableSpot: 10,
                reserveSpot: -20,
              },
              {
                type: 'VIP2',
                totalSpot: 36,
                availableSpot: 23,
                unavailableSpot: 1,
                reserveSpot: 12,
              },
              {
                type: 'VIP3',
                totalSpot: 83,
                availableSpot: 48,
                unavailableSpot: 31,
                reserveSpot: 4,
              },
              {
                type: 'HADICAP',
                totalSpot: 70,
                availableSpot: 82,
                unavailableSpot: 73,
                reserveSpot: -85,
              },
              {
                type: 'LAY',
                totalSpot: 13,
                availableSpot: 28,
                unavailableSpot: 21,
                reserveSpot: -36,
              },
            ],
          },
          {
            id: 29,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P3',
            floorId: 197497,
            totalSpot: 57,
            availableSpot: 71,
            unavailableSpot: 2,
            reserveSpot: -16,
            types: [
              {
                type: 'VIP1',
                totalSpot: 31,
                availableSpot: 86,
                unavailableSpot: 53,
                reserveSpot: -108,
              },
              {
                type: 'VIP2',
                totalSpot: 26,
                availableSpot: 11,
                unavailableSpot: 40,
                reserveSpot: -25,
              },
              {
                type: 'VIP3',
                totalSpot: 75,
                availableSpot: 32,
                unavailableSpot: 11,
                reserveSpot: 32,
              },
              {
                type: 'HADICAP',
                totalSpot: 36,
                availableSpot: 84,
                unavailableSpot: 35,
                reserveSpot: -83,
              },
              {
                type: 'LAY',
                totalSpot: 41,
                availableSpot: 39,
                unavailableSpot: 1,
                reserveSpot: 1,
              },
            ],
          },
          {
            id: 32,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P4',
            floorId: 197497,
            totalSpot: 41,
            availableSpot: 69,
            unavailableSpot: 83,
            reserveSpot: -111,
            types: [
              {
                type: 'VIP1',
                totalSpot: 67,
                availableSpot: 16,
                unavailableSpot: 12,
                reserveSpot: 39,
              },
              {
                type: 'VIP2',
                totalSpot: 32,
                availableSpot: 38,
                unavailableSpot: 55,
                reserveSpot: -61,
              },
              {
                type: 'VIP3',
                totalSpot: 7,
                availableSpot: 57,
                unavailableSpot: 86,
                reserveSpot: -136,
              },
              {
                type: 'HADICAP',
                totalSpot: 51,
                availableSpot: 7,
                unavailableSpot: 58,
                reserveSpot: -14,
              },
              {
                type: 'LAY',
                totalSpot: 7,
                availableSpot: 14,
                unavailableSpot: 86,
                reserveSpot: -93,
              },
            ],
          },
          {
            id: 33,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P5',
            floorId: 197497,
            totalSpot: 72,
            availableSpot: 57,
            unavailableSpot: 14,
            reserveSpot: 1,
            types: [
              {
                type: 'VIP1',
                totalSpot: 82,
                availableSpot: 23,
                unavailableSpot: 26,
                reserveSpot: 33,
              },
              {
                type: 'VIP2',
                totalSpot: 73,
                availableSpot: 68,
                unavailableSpot: 49,
                reserveSpot: -44,
              },
              {
                type: 'VIP3',
                totalSpot: 38,
                availableSpot: 16,
                unavailableSpot: 12,
                reserveSpot: 10,
              },
              {
                type: 'HADICAP',
                totalSpot: 88,
                availableSpot: 41,
                unavailableSpot: 22,
                reserveSpot: 25,
              },
              {
                type: 'LAY',
                totalSpot: 46,
                availableSpot: 44,
                unavailableSpot: 7,
                reserveSpot: -5,
              },
            ],
          },
          {
            id: 35,
            createdAt: '2024-01-28T07:06:54.990Z',
            updatedAt: '2024-01-28T07:06:54.990Z',
            deletedAt: null,
            name: 'P6',
            floorId: 197497,
            totalSpot: 48,
            availableSpot: 94,
            unavailableSpot: 65,
            reserveSpot: -111,
            types: [
              {
                type: 'VIP1',
                totalSpot: 63,
                availableSpot: 42,
                unavailableSpot: 65,
                reserveSpot: -44,
              },
              {
                type: 'VIP2',
                totalSpot: 86,
                availableSpot: 49,
                unavailableSpot: 27,
                reserveSpot: 10,
              },
              {
                type: 'VIP3',
                totalSpot: 81,
                availableSpot: 3,
                unavailableSpot: 47,
                reserveSpot: 31,
              },
              {
                type: 'HADICAP',
                totalSpot: 78,
                availableSpot: 62,
                unavailableSpot: 59,
                reserveSpot: -43,
              },
              {
                type: 'LAY',
                totalSpot: 18,
                availableSpot: 47,
                unavailableSpot: 46,
                reserveSpot: -75,
              },
            ],
          },
        ],
        totalSpot: 2,
        availableSpot: 68,
        unavailableSpot: 58,
        reserveSpot: -124,
      },
    ],
    totalSpot: 69,
    availableSpot: 31,
    unavailableSpot: 85,
    reserveSpot: -47,
  },
];

export const checkRedemptionStatusByEmailResponse = {
  message: 'Success!',
  status: 0,
  data: {
    userID: '1',
    username: 'fs',
    firstname: 'Forward',
    lastname: 'System',
    email: 'fs@email.com',
    userLevel: '1',
    tenantId: '1',
    redempType: '2',
    departmentId: '0',
  },
  count: 0,
};

export const getParkingDetailByPersonIDResponse = {
  message: 'Success!',
  status: 0,
  data: [
    {
      status: 'Success',
      message: 'คำนวณเรียบร้อยแล้ว ไม่มีการจ่ายเงินที่ตู้ KISOK หรือ จ่ายเงินทางระบบ ONLINE เข้ามา',
      exeption: null,
      logId: '2024010912303301',
      ticketNo: 'E0D53E98-AED2-4F70-826C-A10661A39F86',
      ticketUid: 'E0D53E98-AED2-4F70-826C-A10661A39F86',
      plateNo: ' 0000000',
      entryDateTime: '2024-01-05 08:57:38',
      logDateTime: '2024-02-05 15:09:52',
      exitStatus: 0,
      terminalInId: 3,
      terminalInName: 'ENT03',
      memberTypeId: 0,
      memberTypeName: 'VISITOR',
      vehicleTypeId: 1,
      vehicleTypeName: 'MOTORCYCLE',
      rateCode: '0',
      rateDetailTH: 'สิทธิจอดรถฟรี 30 นาทีแรก.,ส่วนเกินคิดชั่วโมงละ 30 บาท',
      rateDetailEN: 'Free 30 Minute.,After 30 Baht/Hour',
      tenantId: '0',
      tenantName: 'ไม่ระบุผู้เช่า',
      isCardLost: false,
      parkHH: 750,
      parkMM: 12,
      rateHH: 751,
      freeHH: 0,
      subTotal: 22530,
      discount: 30,
      parkFee: 22500,
      cardLostFine: 0,
      overNightFine: 0,
      total: 22500,
      isInv: false,
      invRateHH: 0,
      invFee: 0,
      isPayAtKiosk: false,
      lastDateTimePaymentAtKiosk: null,
      payAtKioskAll: 0,
      durationInMinute: 30,
      timeUsedInMinute: 0,
      remainInMinute: 0,
    },
  ],
  count: 0,
};

export const getDataRateCodeResponse = {
  message: 'Success!',
  status: 0,
  data: [
    {
      rateCode: 1001,
      rateDetail: 'สิทธิจอดรถฟรี 1 ชม.,ส่วนเกินคิดชั่วโมงละ 30 บาท',
      rateDetailEng: 'Free 1 Hrs.',
    },
    {
      rateCode: 1004,
      rateDetail: 'สิทธิจอดรถฟรี 4 ชม.,ส่วนเกินคิดชั่วโมงละ 30 บาท',
      rateDetailEng: 'Free 4 Hrs.',
    },
    {
      rateCode: 1008,
      rateDetail: 'สิทธิจอดรถฟรี 8 ชม.,ส่วนเกินคิดชั่วโมงละ 30 บาท',
      rateDetailEng: 'Free 8 Hrs.',
    },
    {
      rateCode: 1012,
      rateDetail: 'สิทธิจอดรถฟรี 12 ชม.,ส่วนเกินคิดชั่วโมงละ 30 บาท  ',
      rateDetailEng: 'Free 12 Hrs.',
    },
    {
      rateCode: 1024,
      rateDetail: 'สิทธิจอดรถฟรี 24 ชม.,ส่วนเกินคิดชั่วโมงละ 30 บาท',
      rateDetailEng: 'Free 24 Hrs.',
    },
  ],
  count: 0,
};

export const redeemParkingResponse = {
  message: 'Success!',
  status: 0,
  data: [
    {
      status: 'Success',
      message: 'คำนวณเรียบร้อยแล้ว ไม่มีการจ่ายเงินที่ตู้ KISOK หรือ จ่ายเงินทางระบบ ONLINE เข้ามา',
      exeption: null,
      logId: '2023120817414402',
      ticketNo: '2000000005',
      ticketUid: '0000002000000005',
      plateNo: ' 3ขฆ1502',
      entryDateTime: '2023-12-08 17:41:44',
      logDateTime: '2024-02-05 15:46:01',
      exitStatus: 0,
      terminalInId: 2,
      terminalInName: 'ENT02',
      memberTypeId: 0,
      memberTypeName: 'VISITOR',
      vehicleTypeId: 0,
      vehicleTypeName: 'CAR',
      rateCode: '0',
      rateDetailTH: 'สิทธิจอดรถฟรี 30 นาทีแรก.,ส่วนเกินคิดชั่วโมงละ 100 บาท',
      rateDetailEN: 'Free 30 Minute.,After 100 Baht/Hour',
      tenantId: '0',
      tenantName: 'ไม่ระบุผู้เช่า',
      isCardLost: false,
      parkHH: 1414,
      parkMM: 4,
      rateHH: 1415,
      freeHH: 0,
      subTotal: 141500,
      discount: 100,
      parkFee: 141400,
      cardLostFine: 0,
      overNightFine: 0,
      total: 141400,
      isInv: false,
      invRateHH: 0,
      invFee: 0,
      isPayAtKiosk: false,
      lastDateTimePaymentAtKiosk: null,
      payAtKioskAll: 0,
      durationInMinute: 30,
      timeUsedInMinute: 0,
      remainInMinute: 0,
    },
  ],
  count: 0,
};

export const parkingQueryResponse = {
  msg: 'success!',
  code: '0',
  data: {
    total: 1,
    pageNo: 1,
    pageSize: 10,
    totalPage: 1,
    list: [
      {
        recordSyscode: '1',
        spaceSyscode: '1',
        spaceNo: '1',
        spacePicUri: 'image.url',
        parkingTime: '2024-01-05T01:57:38.000Z',
        parkSyscode: '1',
        parkName: 'park',
        floorSyscode: '1',
        floorName: 'floor',
        plateNoPicUri: 'image.url',
        aswSyscode: '1',
        plateNo: '0000000',
        spacePicUrl: 'image.url',
        plateNoPicUrl: 'image.url',
        spacePicBinary: 'image',
        ibeaconIpcUuid: 'uuid',
        ibeaconIpcMajor: 'major',
        ibeaconIpcMinor: 'minor',
      },
    ],
  },
};

export const parkingSpaceNoResponse = [
  {
    _id: '1',
    spaceSyscode: '1',
    __v: 0,
    alarmPlateNos: null,
    aswSyscode: null,
    floorName: 'B4',
    floorSyscode: '1',
    getTime: 1726217951976,
    ibeaconIpcMajor: null,
    ibeaconIpcMinor: null,
    ibeaconIpcUuid: null,
    latitude: '13.7841676500015',
    longitude: '100.751306737775',
    parkName: 'One Bangkok',
    parkSyscode: '1',
    parkingTime: '1',
    parkingTimeUTC: 1726195950000,
    plateNo: null,
    plateNoPicUri: null,
    plateNoPicUrl: null,
    plateNos: null,
    spaceNo: '1',
    spacePicUri: null,
    spacePicUrl: null,
    spaceType: 'Common Parking Space',
    spaceTypeKey: '0',
    state: 0,
    zoneId: '1',
    zoneName: 'A',
    carblockerDevice: {
      _id: '1',
      device_id: '1',
      status: 1,
      rssi: -67,
      time: '2024-09-13T08:33:12.153Z',
      createdAt: '2024-09-13T08:33:12.154Z',
      updatedAt: '2024-09-13T08:33:12.154Z',
    },
  },
];

describe('FS Parking Client Service', () => {
  describe('getParkingAvailabilityData', () => {
    it('should return parking data', async () => {
      spy = jest.spyOn(FSParkingClient.httpClient, 'get').mockResolvedValue({ data: MOCK_PARKING_DATA_RESPONSE });
      const response = await FSParkingClient.getParkingAvailabilityData();

      expect(response.data).toEqual(MOCK_PARKING_DATA_RESPONSE);
    });
  });

  describe('checkRedemptionStatusByEmail', () => {
    it('should return tenant data', async () => {
      spy = jest
        .spyOn(FSParkingClient.httpClient, 'post')
        .mockResolvedValue({ data: checkRedemptionStatusByEmailResponse });
      const response = await FSParkingClient.checkRedemptionStatusByEmail(['fs@email.com']);

      expect(response.data).toEqual(checkRedemptionStatusByEmailResponse);
    });
  });

  describe('getParkingDetailByPersonID', () => {
    it('should return parking detail data', async () => {
      spy = jest
        .spyOn(FSParkingClient.httpClient, 'post')
        .mockResolvedValue({ data: getParkingDetailByPersonIDResponse });
      const response = await FSParkingClient.getParkingDetailByPersonID('3fa85f64-5717-4562-b3fc-2c963f66afa6');

      expect(response.data).toEqual(getParkingDetailByPersonIDResponse);
    });
  });

  describe('getParkingDetailByQRCode', () => {
    it('should return parking detail data', async () => {
      spy = jest
        .spyOn(FSParkingClient.httpClient, 'post')
        .mockResolvedValue({ data: getParkingDetailByPersonIDResponse });
      const response = await FSParkingClient.getParkingDetailByQRCode('3fa85f64-5717-4562-b3fc-2c963f66afa6');

      expect(response.data).toEqual(getParkingDetailByPersonIDResponse);
    });
  });

  describe('getDataRateCode', () => {
    it('should return redemption data', async () => {
      spy = jest.spyOn(FSParkingClient.httpClient, 'post').mockResolvedValue({ data: getDataRateCodeResponse });
      const response = await FSParkingClient.getDataRateCode({
        tenantID: 1,
        departmentID: 0,
        memberType: 0,
        vehicleType: 0,
      });
      expect(response.data).toEqual(getDataRateCodeResponse);
    });
  });

  describe('redeemParking', () => {
    it('should return rate data', async () => {
      spy = jest.spyOn(FSParkingClient.httpClient, 'post').mockResolvedValue({ data: redeemParkingResponse });
      const response = await FSParkingClient.redeemParking({
        logCarparkID: '2023120817414402',
        terminalID: 2,
        datetimeIn: '2023-12-08 17:41:44',
        runningNumber: '2000000005',
        plateNumber: '3ขฆ1502',
        memberType: 0,
        carType: 0,
        tenantID: 1,
        spendingValue: '0',
        posValue: '0',
        couponValue: '0',
        rateCode: '1001',
        userID: '1',
        remark: 'string',
      });

      expect(response.data).toEqual(redeemParkingResponse);
    });
  });
});
