apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

configMapGenerator:
  - literals:
      - NODE_ENV=sit
    name: configmap

patches:
  - patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: https://github.com/mtel-thailand/ob-document
      - op: replace
        path: /spec/source/targetRevision
        value: sit
      - op: replace
        path: /spec/source/path
        value: k8s/sit
    target:
      kind: Application
  - patch: |-
      - op: replace
        path: /stringData/url
        value: https://github.com/mtel-thailand/ob-document
    target:
      kind: Secret
