build-docker-image:
  stage: build-image
  rules:
    - if: $CI_COMMIT_BRANCH == "uat" || ($CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "uat")
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  variables:
    ECR_REGISTRY: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    CI_REGISTRY_IMAGE: $ECR_REGISTRY/$ECR_REPOSITORY
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
    - echo "Building and push Docker image..."
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/dockerfile"
      --build-arg=NODE_ENV=uat
      --destination $ECR_REGISTRY/$ECR_REPOSITORY:latest
    - BUILD_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:latest > vars.env
    - echo "Docker image pushed successfully."
  artifacts:
    reports:
      dotenv: vars.env


deploy-uat:
  stage: deploy
  # needs: [build-docker-image]
  image: alpine:3.8
  before_script:
    - apk add --no-cache gettext
    - echo "Installing curl and bash..."
    - apk add --no-cache git curl bash coreutils
    - echo "Install Kustomize"
    - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
    - mv kustomize /usr/local/bin/
    - echo "Kustomize installed"
    - echo "Setting up environment.."
    - export IMAGE_URL="730335418784.dkr.ecr.ap-southeast-1.amazonaws.com/ob-iam/uat:latest"
    - envsubst < ./k8s/uat/gen > ./k8s/uat/kustomization.yaml
    - echo "Environment setup complete"
    - cd ./k8s/uat
    - TIMESTAMP=$(date +%s)
    - kustomize edit add annotation "deploy-timestamp":$TIMESTAMP -f
    - kustomize edit set image 730335418784.dkr.ecr.ap-southeast-1.amazonaws.com/ob-iam/uat:latest
    - kustomize build
    - echo "Deploy timestamp set to $TIMESTAMP"
    - echo "Kustomize configuration completed"
  script:
    - echo "Deploy to ArgoCD"
    - git config --global user.email "gitlab@gitlab.com"
    - git config --global user.name "GitLab CI/CD"
    - git checkout -B uat
    - git pull origin uat
    - echo "Current branch $CI_COMMIT_BRANCH"
    - echo "Git status before commit:"
    - git status
    - git remote set-url origin https://piya.ph:glpat-xkduQyGC1joKkNEmNKmT@git.lab.tcctech.app/obk/obk-mtel-iam.git
    - git add kustomization.yaml
    - git commit -m "[skip ci] deploy argoCD"
    - git push -u origin uat
    # - git push --no-verify
    - echo "Changes pushed to repository"
  only:
    refs:
      - uat
