apiVersion: v1
kind: Service
metadata:
  name: ob-notification
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: https
      port: 443
      targetPort: 3000
  selector:
    name: ob-notification
