export enum EventEmitterEventNames {
  SIGN_IN__OTP_VERIFIED = 'SIGN_IN__OTP_VERIFIED',
  ACCOUNT__ADDING_EVENT = 'ACCOUNT__ADDING_EVENT',
  CONFIRM_IDENTITY__EVENT = 'CONFIRM_IDENTITY__EVENT',
  SIGNUP__EVENT = 'SIGNUP__EVENT',
  SIGNUP_CONFIRM_PASSWORD__EVENT = 'SIGNUP_CONFIRM_PASSWORD__EVENT',
  FORGOTTEN_PASSWORD__OTP_VERIFIED = 'FORGOTTEN_PASSWORD__OTP_VERIFIED',
  TWO_FACTOR_AUTHENTICATION__OTP_REQUESTED = 'TWO_FACTOR_AUTHENTICATION__OTP_REQUESTED',
  REGISTER_FAILED = 'REGISTER_FAILED',
  SIGNIN_2FA_EVENT = 'SIGNIN_2FA_EVENT',
  SIGNIN_FAILED = 'SIGNIN_FAILED',
  SETUP_2FA_COMPLETED = 'SETUP_2FA_COMPLETED',
}

export const enum EventName {
  RESET_STATE = 0,
  CHANGE_IDENTIFIER,
  OTP_VERIFIED,
  HANDLE_ERROR,
  SIGNIN_FAILED,
  SUCCESS,
  OTP_ABORTED,
}

interface eventData {
  [key: string]: any;
}
export interface handleEventParams {
  eventName: EventName;
  data: eventData;
}
