PUT http://localhost:8080/api/faqs/2?locale=th
content-type: application/json

{
    "question": "What do we do 2 TH ????",
    "answer": "What is Artloop? of artworks created by both local and international artists to suit One Bangkok's public space, either indoor or accessible to specified target audiences.What is Artloop? of artworks created by both local and international artists to suit One Bangkok's public space, either indoor orWhat is Artloop? of artworks created by both local and international artists to suit One Bangkok's public space, either indoo"
}
