POST http://localhost:8080/api/programs?locale=th
content-type: application/json

{
    "category": "art-gallery",
    "title": "The Mastaba AR by Christo and Jeanne-Claude 2 th !!",
    "description": "Planned before Christo's death in May 2020, this is an opportunity to share the last public work realised in Christo's lifetime with a global audience and celebrate the memory of his and Jeanne-Claude’s visionary projects.",
    "thumbnail": "https://www.bkkmenu.com/files/2018/09/PenthouseDinner__00012.jpg",
    "coverImage": "https://www.bkkmenu.com/files/2018/09/PenthouseDinner__00012.jpg",
    "location": "Post28 Floor8, One Bangkok",
    "openingHours": ["Everyday 10:00-21:00"],
    "enterFee": 450,
    "externalLink": "https://www.onebangkokartgallery.com",
    "partners": [ 
        {
            "id": 4
        },
        {
            "id": 6
        },
        {
            "id": 7
        }
     ]
}