apiVersion: v1
kind: Secret
metadata:
  name: app
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: ${REPO_URL}
  password: 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
  username: billy-wong-mtelhk