namespace TCCT.ServiceAbstraction.Application.Features.Certis.Transaction.CWO.Master;
public class CWOMasterResult
{
	public int Id { get; set; }
	public string Name { get; set; }
	public int CwoTypeId { get; set; }
	public int ProblemTypeId { get; set; }
	public int PriorityId { get; set; }
	public int ServiceCategoryId { get; set; }
	public int LocationId { get; set; }
	public string Description { get; set; }
	public string CreatedBy { get; set; }
	public DateTime CreatedOn { get; set; }
	public string ModifiedBy { get; set; }
	public DateTime ModifiedOn { get; set; }
	public int RequesterId { get; set; }
	public DateTime RequestedOn { get; set; }
	public bool IsActive { get; set; }
	public int StatusId { get; set; }
	public int AssetId { get; set; }
	public DateTime AckedOn { get; set; }
	public string AckedBy { get; set; }
	public DateTime SlaStartDateTime { get; set; }
	public DateTime SlatoResolve { get; set; }
	public DateTime SlatoRespond { get; set; }
	public int EstimatedTotalDuration { get; set; }
	public DateTime EstimatedCompletion { get; set; }
	public string SupervisorId { get; set; }
	public DateTime SupervisorAssignedOn { get; set; }
	public string SupervisorAssignedBy { get; set; }
	public string TechnicianId { get; set; }
	public DateTime TechnicianAssignedOn { get; set; }
	public string TechnicianAssignedBy { get; set; }
	public string OperatorNote { get; set; }
	public DateTime ActualStartDateTime { get; set; }
	public DateTime ActualCompletionDateTime { get; set; }
	public string CompletedBy { get; set; }
	public DateTime ClosedOn { get; set; }
	public string ClosedBy { get; set; }
	public bool IsTaskCompletionConfirmed { get; set; }
	public string TaskCompletionConfirmedBy { get; set; }
	public DateTime TaskCompletionConfirmedOn { get; set; }
	public bool IsCancelled { get; set; }
	public int ServiceProviderId { get; set; }
	public string CompletionComment { get; set; }
	public string ClosureComment { get; set; }
	public int SlaTriggerPoint { get; set; }
	public bool IsReworkRequested { get; set; }
	public string ReworkRequestedBy { get; set; }
	public DateTime ReworkRequestedOn { get; set; }
	public string ReasonToRework { get; set; }
	public bool IsPrevSupervisorRejected { get; set; }
	public string PrevRejectedSupervisorId { get; set; }
	public bool IsPrevTechnicianRejected { get; set; }
	public string PrevRejectedTechnicianId { get; set; }
	public string AcknowledgementVerifiedBy { get; set; }
	public string CompletionAckedBy { get; set; }
	public string CompletionVerifiedBy { get; set; }
	public string ClientVerificationSubmittedBy { get; set; }
	public DateTime ClientVerificationSubmittedOn { get; set; }
	public string ClientVerificationComment { get; set; }
	public string ClientVerifiedUser { get; set; }
	public bool IsWorkingOffline { get; set; }
	public DateTime WorkOfflineOn { get; set; }
	public string WorkOfflineBy { get; set; }
	public bool IsPaused { get; set; }
	public string PausedBy { get; set; }
	public DateTime PausedOn { get; set; }
	public string PausedReason { get; set; }
	public string ResumedBy { get; set; }
	public DateTime ResumedOn { get; set; }
	public string AcknowledgementSignature { get; set; }
	public string CompletionSignature { get; set; }
	public string ClosureSignature { get; set; }
	public string ClientVerificationSignature { get; set; }
	public bool IsSynced { get; set; }
	public int ParentId { get; set; }
}
