apiVersion: apps/v1
kind: Deployment
metadata:
  name: ob-iam
spec:
  selector:
    matchLabels:
      name: ob-iam
  template:
    metadata:
      labels:
        name: ob-iam
    spec:
      containers:
        - name: ob-iam
          image: 479397374389.dkr.ecr.ap-southeast-1.amazonaws.com/ob-iam/uat:ob-iam_latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:2a843c492f23fdbd6d586d0911d275fc@ob-uat-ob-iam.cu8h89u4zzko.ap-southeast-1.rds.amazonaws.com/ob-uat-ob-iam
            - name: AWS_REGION
              value: ap-southeast-1
            - name: AWS_ACCESS_KEY_ID
              value: AKIAW7HSPNG26XNINRPP
            - name: AWS_SECRET_ACCESS_KEY
              value: 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
            - name: EMAIL_SENDER_PROVIDER
              value: MOCK
            - name: SMS_SENDER_PROVIDER
              value: MOCK
            - name: SLACK_OAUTH_TOKEN
              value: xoxb-2523263893682-5967783408147-KauLenA2D3yOFnvjRtlYPFPf
            - name: OTP_SLACK_CHANNEL_ID
              value: C05UCUQE0LD
            - name: JWT_SECRET_KEY
              value: '-----BEGIN OPENSSH PRIVATE KEY----- b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW QyNTUxOQAAACDrkLDew441tWN/byoGGnBXXYZ6+8lWhO3Z2+9D/BK8lAAAAKD4p+dF+Kfn RQAAAAtzc2gtZWQyNTUxOQAAACDrkLDew441tWN/byoGGnBXXYZ6+8lWhO3Z2+9D/BK8lA AAAEC6Cjjwi3vzArlO0C2HkQR9KyLBM1MCBxwGGRyPAtKuo+uQsN7DjjW1Y39vKgYacFdd hnr7yVaE7dnb70P8EryUAAAAF3BhbmlzYXJhLnNvckBtdGVsLmNvLnRoAQIDBAUG -----END OPENSSH PRIVATE KEY-----'
            - name: OB_EVENT_CONFIG_PATH
              value: event.config.uat.json
            - name: ENABLE_DEVICE_STORING
              value: 'true'
            - name: OB_BMS_URL
              value: https://uat.glorymtel.xyz/ob-bms
