START TRANSACTION;

CREATE TABLE "trCases" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ShortDesc" text,
    "CaseNo" character varying(100),
    "EventTypeId" integer NOT NULL,
    "EventTypeCode" character varying(100),
    "LocationId" integer NOT NULL,
    "LocationCode" character varying(100),
    "LocationName" character varying(100),
    "PriorityLevelId" integer NOT NULL,
    "SiteHandler" integer,
    "StatusCode" integer,
    "Timestamp" character varying(100) NOT NULL,
    "CreatedOn" timestamp without time zone,
    "SlaConfigId" integer,
    "CaseTypeId" integer,
    "CreatedBy" character varying(100),
    "SlaFailed" boolean,
    "SlaDate" timestamp without time zone,
    "Description" text,
    "EquipmentTag" character varying(100),
    "ExternalRefNo" character varying(100),
    "IsCritical" boolean,
    "PriorityText" text,
    "SyncStatus" integer NOT NULL,
    "SyncUtcTs" integer NOT NULL,
    CONSTRAINT "PK_trCases" PRIMARY KEY ("Id")
);

CREATE TABLE "trCaseMedias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CaseId" integer NOT NULL,
    "FileName" text NOT NULL,
    "Data" text NOT NULL,
    "MimeType" text NOT NULL,
    CONSTRAINT "PK_trCaseMedias" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_trCaseMedias_trCases_CaseId" FOREIGN KEY ("CaseId") REFERENCES "trCases" ("Id") ON DELETE CASCADE
);

CREATE TABLE "trCaseTasks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "CaseId" integer NOT NULL,
    "StatusCode" integer NOT NULL,
    "Sequence" integer NOT NULL,
    "CreatedBy" text,
    "CreatedOn" timestamp without time zone NOT NULL,
    "ModifiedBy" text,
    "ModifiedOn" timestamp without time zone NOT NULL,
    "AssignedStaffId" integer,
    "AssignedStaffDisplayName" text,
    "IsCritical" boolean NOT NULL,
    "TaskCategoryId" integer NOT NULL,
    CONSTRAINT "PK_trCaseTasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_trCaseTasks_trCases_CaseId" FOREIGN KEY ("CaseId") REFERENCES "trCases" ("Id") ON DELETE CASCADE
);

UPDATE "Location" SET "CreatedDate" = TIMESTAMP '2024-11-25T18:41:35.859169', "UpdatedDate" = TIMESTAMP '2024-11-25T18:41:35.859169'
WHERE "LID" = '2c055101-2271-44e0-95fe-bcf2c59a459a';

UPDATE "Tenant" SET "CreatedDate" = TIMESTAMP '2024-11-25T18:41:35.85363', "UpdatedDate" = TIMESTAMP '2024-11-25T18:41:35.854094'
WHERE "TID" = '4199e4de-bdf8-48f8-a8a8-a5b31756a748';

UPDATE "Tenant" SET "CreatedDate" = TIMESTAMP '2024-11-25T18:41:35.854158', "UpdatedDate" = TIMESTAMP '2024-11-25T18:41:35.854159'
WHERE "TID" = 'caa4ebec-15c8-4d6b-9985-6d6b66f94e63';

UPDATE "mtActionType" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858119', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858127'
WHERE "Id" = 'e8eb7171-de01-4a85-a955-711b211eecc2';

UPDATE "mtActionType" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858129', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858129'
WHERE "Id" = 'e8eb7171-de01-4a85-a955-711b211eecc3';

UPDATE "mtActionType" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.85813', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858131'
WHERE "Id" = 'e8eb7171-de01-4a85-a955-711b211eecc4';

UPDATE "mtActionType" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858132', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858132'
WHERE "Id" = 'e8eb7171-de01-4a85-a955-711b211eecc5';

UPDATE "mtShiftManPowerRequest" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.860389', "StartDateTime" = TIMESTAMP '2024-10-25T18:41:35.860353', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.860389'
WHERE "Id" = 1;

UPDATE "mtShiftManPowerRequest" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.860391', "StartDateTime" = TIMESTAMP '2024-10-25T18:41:35.860391', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.860391'
WHERE "Id" = 2;

UPDATE "mtShiftManPowerRequest" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.860392', "StartDateTime" = TIMESTAMP '2024-10-25T18:41:35.860392', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.860392'
WHERE "Id" = 3;

UPDATE "mtShiftManPowerRequest" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.860392', "StartDateTime" = TIMESTAMP '2024-10-25T18:41:35.860392', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.860392'
WHERE "Id" = 4;

UPDATE "trAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858298', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858298'
WHERE "Id" = '2aa84ed4-a495-47c8-913f-fa5928c1b4b8';

UPDATE "trAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.8583', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.8583'
WHERE "Id" = '3ff4f468-53ef-48a3-8781-61a8a053fa99';

UPDATE "trAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.8583', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.8583'
WHERE "Id" = '564d0272-92c8-4108-82b2-0f98882058d4';

UPDATE "trAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858301', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858301'
WHERE "Id" = '6d174fd6-b597-4b16-a117-08b7a84be839';

UPDATE "trAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858301', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858301'
WHERE "Id" = 'c1cb273c-570a-42f5-b563-66bac08911cc';

UPDATE "trAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858304', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858304'
WHERE "Id" = 'c1cb273c-570a-42f5-b563-66bac08911cd';

UPDATE "trAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858304', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858304'
WHERE "Id" = 'e8eb7171-de01-4a85-a955-711b211eecc1';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2024-11-25T18:41:35.861595', "UpdatedDate" = TIMESTAMP '2024-11-25T18:41:35.861595'
WHERE "RID" = '18a79217-9fa7-460d-bccc-e74285b07531';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2024-11-25T18:41:35.861596', "UpdatedDate" = TIMESTAMP '2024-11-25T18:41:35.861596'
WHERE "RID" = 'bd69a88e-d6c1-42a1-8a3a-628843459909';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2024-11-25T18:41:35.861596', "UpdatedDate" = TIMESTAMP '2024-11-25T18:41:35.861596'
WHERE "RID" = 'c01c5086-cfa5-44ca-89d7-baa2c1accea6';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2024-11-25T18:41:35.861596', "UpdatedDate" = TIMESTAMP '2024-11-25T18:41:35.861596'
WHERE "RID" = 'd6016437-8b0f-4b0e-8175-5a11ffc480f5';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2024-11-25T18:41:35.861595', "UpdatedDate" = TIMESTAMP '2024-11-25T18:41:35.861595'
WHERE "RID" = 'f2cf879b-34f3-41da-9445-ee3bc590f224';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2024-11-25T18:41:35.861593', "UpdatedDate" = TIMESTAMP '2024-11-25T18:41:35.861594'
WHERE "RID" = 'fcddbf6b-88b8-4fae-ade7-63150ce1f1ec';

UPDATE "trSubtask" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858451', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858451'
WHERE "Id" = '1a157bf0-4748-4589-91cc-1450e0c06596';

UPDATE "trSubtask" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858452', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858452'
WHERE "Id" = '35d4cfa7-04ea-473a-9b50-c9751843ead5';

UPDATE "trSubtask" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858451', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858451'
WHERE "Id" = '3fa85f64-5717-4562-b3fc-2c963f66afa6';

UPDATE "trSubtask" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858444', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858445'
WHERE "Id" = '77e2f48c-8178-4df5-9b84-48bfd253a496';

UPDATE "trSubtask" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858451', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858451'
WHERE "Id" = 'eaab304c-89e1-484c-aefe-0e4e3e27e911';

UPDATE "trSubtaskAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858875', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858875'
WHERE "Action" = '3ff4f468-53ef-48a3-8781-61a8a053fa99' AND "Subtask" = '1a157bf0-4748-4589-91cc-1450e0c06596';

UPDATE "trSubtaskAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858877', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858877'
WHERE "Action" = '564d0272-92c8-4108-82b2-0f98882058d4' AND "Subtask" = '1a157bf0-4748-4589-91cc-1450e0c06596';

UPDATE "trSubtaskAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858879', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858879'
WHERE "Action" = '6d174fd6-b597-4b16-a117-08b7a84be839' AND "Subtask" = '1a157bf0-4748-4589-91cc-1450e0c06596';

UPDATE "trSubtaskAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858879', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858879'
WHERE "Action" = '564d0272-92c8-4108-82b2-0f98882058d4' AND "Subtask" = '35d4cfa7-04ea-473a-9b50-c9751843ead5';

UPDATE "trSubtaskAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858879', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.85888'
WHERE "Action" = '6d174fd6-b597-4b16-a117-08b7a84be839' AND "Subtask" = '35d4cfa7-04ea-473a-9b50-c9751843ead5';

UPDATE "trSubtaskAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.85888', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.85888'
WHERE "Action" = 'e8eb7171-de01-4a85-a955-711b211eecc1' AND "Subtask" = '35d4cfa7-04ea-473a-9b50-c9751843ead5';

UPDATE "trSubtaskAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858883', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858883'
WHERE "Action" = 'c1cb273c-570a-42f5-b563-66bac08911cc' AND "Subtask" = '77e2f48c-8178-4df5-9b84-48bfd253a496';

UPDATE "trSubtaskAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858883', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858883'
WHERE "Action" = 'c1cb273c-570a-42f5-b563-66bac08911cd' AND "Subtask" = '77e2f48c-8178-4df5-9b84-48bfd253a496';

UPDATE "trSubtaskAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.85888', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858881'
WHERE "Action" = '2aa84ed4-a495-47c8-913f-fa5928c1b4b8' AND "Subtask" = 'eaab304c-89e1-484c-aefe-0e4e3e27e911';

UPDATE "trSubtaskAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858881', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858881'
WHERE "Action" = '564d0272-92c8-4108-82b2-0f98882058d4' AND "Subtask" = 'eaab304c-89e1-484c-aefe-0e4e3e27e911';

UPDATE "trSubtaskAction" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858881', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858881'
WHERE "Action" = '6d174fd6-b597-4b16-a117-08b7a84be839' AND "Subtask" = 'eaab304c-89e1-484c-aefe-0e4e3e27e911';

UPDATE "trTask" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858666', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858667'
WHERE "Id" = '2c055101-2271-44e0-95fe-bcf2c59a459b';

UPDATE "trTask" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858671', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858671'
WHERE "Id" = '4422cc3c-0ea5-4d73-a31e-a42485a81003';

UPDATE "trTaskSubtask" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858756', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858757'
WHERE "Subtask" = '1a157bf0-4748-4589-91cc-1450e0c06596' AND "Task" = '2c055101-2271-44e0-95fe-bcf2c59a459b';

UPDATE "trTaskSubtask" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858759', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858759'
WHERE "Subtask" = '35d4cfa7-04ea-473a-9b50-c9751843ead5' AND "Task" = '2c055101-2271-44e0-95fe-bcf2c59a459b';

UPDATE "trTaskSubtask" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858759', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858759'
WHERE "Subtask" = 'eaab304c-89e1-484c-aefe-0e4e3e27e911' AND "Task" = '2c055101-2271-44e0-95fe-bcf2c59a459b';

UPDATE "trTaskSubtask" SET "CreatedDate" = TIMESTAMP '2024-10-25T18:41:35.858759', "UpdatedDate" = TIMESTAMP '2024-10-25T18:41:35.858759'
WHERE "Subtask" = '77e2f48c-8178-4df5-9b84-48bfd253a496' AND "Task" = '4422cc3c-0ea5-4d73-a31e-a42485a81003';

CREATE INDEX "IX_trCaseMedias_CaseId" ON "trCaseMedias" ("CaseId");

CREATE INDEX "IX_trCaseTasks_CaseId" ON "trCaseTasks" ("CaseId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241125114137_CaseMozart', '8.0.4');

COMMIT;

