START TRANSACTION;

CREATE TABLE "EventsLog" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Type" character varying NOT NULL,
    "Time" timestamp without time zone NOT NULL,
    "IpAddress" text NOT NULL,
    "AuthMethod" text NOT NULL,
    "TokenId" uuid NOT NULL,
    "GrantType" text NOT NULL,
    "RefreshTokenType" text NOT NULL,
    "Scope" text NOT NULL,
    "RefreshTokenId" uuid NOT NULL,
    "ClientAuthMethod" text NOT NULL,
    "Username" uuid NOT NULL,
    CONSTRAINT "PK_EventsLog" PRIMARY KEY ("Id")
);

CREATE TABLE "mtStaff" (
    "Sfid" uuid NOT NULL,
    "StaffName" character varying,
    "Email" character varying NOT NULL,
    "Component" character varying,
    "Position" character varying,
    "Company" character varying,
    "Location" character varying,
    "MustUseOpsApp" boolean NOT NULL,
    "isDelete" integer NOT NULL,
    "UpdatedDate" timestamp without time zone,
    "KeyCloakUserId" character varying,
    CONSTRAINT "PK_mtStaff" PRIMARY KEY ("Sfid")
);

CREATE TABLE "trRoster" (
    "Id" uuid NOT NULL,
    "Component" character varying NOT NULL,
    "WeekDay" integer,
    "WeekEnd" integer,
    "StartDateTime" timestamp without time zone NOT NULL,
    "EndDateTime" timestamp without time zone,
    CONSTRAINT "PK_trRoster" PRIMARY KEY ("Id")
);

UPDATE "Tenant" SET "CreatedDate" = TIMESTAMP '2025-01-20T18:07:42.973008', "UpdatedDate" = TIMESTAMP '2025-01-20T18:07:42.981392'
WHERE "TID" = '4199e4de-bdf8-48f8-a8a8-a5b31756a748';

UPDATE "Tenant" SET "CreatedDate" = TIMESTAMP '2025-01-20T18:07:42.981414', "UpdatedDate" = TIMESTAMP '2025-01-20T18:07:42.981414'
WHERE "TID" = 'caa4ebec-15c8-4d6b-9985-6d6b66f94e63';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2025-01-20T18:07:42.982353', "UpdatedDate" = TIMESTAMP '2025-01-20T18:07:42.982353'
WHERE "RID" = '18a79217-9fa7-460d-bccc-e74285b07531';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2025-01-20T18:07:42.982354', "UpdatedDate" = TIMESTAMP '2025-01-20T18:07:42.982355'
WHERE "RID" = 'bd69a88e-d6c1-42a1-8a3a-628843459909';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2025-01-20T18:07:42.982354', "UpdatedDate" = TIMESTAMP '2025-01-20T18:07:42.982354'
WHERE "RID" = 'c01c5086-cfa5-44ca-89d7-baa2c1accea6';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2025-01-20T18:07:42.982354', "UpdatedDate" = TIMESTAMP '2025-01-20T18:07:42.982354'
WHERE "RID" = 'd6016437-8b0f-4b0e-8175-5a11ffc480f5';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2025-01-20T18:07:42.982354', "UpdatedDate" = TIMESTAMP '2025-01-20T18:07:42.982354'
WHERE "RID" = 'f2cf879b-34f3-41da-9445-ee3bc590f224';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2025-01-20T18:07:42.982353', "UpdatedDate" = TIMESTAMP '2025-01-20T18:07:42.982353'
WHERE "RID" = 'fcddbf6b-88b8-4fae-ade7-63150ce1f1ec';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250120110743_CreateStaffEventlogRoster', '8.0.4');

COMMIT;

