START TRANSACTION;

ALTER TABLE "trCWOs" DROP CONSTRAINT "PK_trCWOs";

UPDATE "trCWOs" SET "CSID" = '3075169a-bb4c-463f-a602-dac99228ceac' WHERE "CSID" IS NULL;
ALTER TABLE "trCWOs" ALTER COLUMN "CSID" SET NOT NULL;

ALTER TABLE "trCWOs" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "trCWOs" ADD CONSTRAINT "PK_trCWOs" PRIMARY KEY ("CSID", "Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250305030713_CwoFix', '8.0.4');

COMMIT;

