START TRANSACTION;

ALTER TABLE "trCases" ADD "ModifiedBy" text;

ALTER TABLE "trCases" ADD "ModifiedOn" timestamp without time zone;

ALTER TABLE "trCases" ADD "Requester" text;

CREATE TABLE "trCWOs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "CwoTypeId" integer NOT NULL,
    "ProblemTypeId" integer NOT NULL,
    "PriorityId" integer NOT NULL,
    "ServiceCategoryId" integer NOT NULL,
    "LocationId" integer NOT NULL,
    "Description" text,
    "CreatedBy" text,
    "CreatedOn" timestamp without time zone,
    "ModifiedBy" text,
    "ModifiedOn" timestamp without time zone,
    "RequesterId" integer,
    "RequestedOn" timestamp without time zone,
    "IsActive" boolean,
    "StatusId" integer,
    "AssetId" integer,
    "AckedOn" timestamp without time zone,
    "AckedBy" text,
    "SlaStartDateTime" timestamp without time zone,
    "SlatoResolve" timestamp without time zone,
    "SlatoRespond" timestamp without time zone,
    "EstimatedTotalDuration" integer,
    "EstimatedCompletion" timestamp without time zone,
    "SupervisorId" text,
    "SupervisorAssignedOn" timestamp without time zone,
    "SupervisorAssignedBy" text,
    "TechnicianId" text,
    "TechnicianAssignedOn" timestamp without time zone,
    "TechnicianAssignedBy" text,
    "OperatorNote" text,
    "ActualStartDateTime" timestamp without time zone,
    "ActualCompletionDateTime" timestamp without time zone,
    "CompletedBy" text,
    "ClosedOn" timestamp without time zone,
    "ClosedBy" text,
    "IsTaskCompletionConfirmed" boolean,
    "TaskCompletionConfirmedBy" text,
    "TaskCompletionConfirmedOn" timestamp without time zone,
    "IsCancelled" boolean,
    "ServiceProviderId" integer,
    "CompletionComment" text,
    "ClosureComment" text,
    "SlaTriggerPoint" integer,
    "IsReworkRequested" boolean,
    "ReworkRequestedBy" text,
    "ReworkRequestedOn" timestamp without time zone,
    "ReasonToRework" text,
    "IsPrevSupervisorRejected" boolean,
    "PrevRejectedSupervisorId" text,
    "IsPrevTechnicianRejected" boolean,
    "PrevRejectedTechnicianId" text,
    "AcknowledgementVerifiedBy" text,
    "CompletionAckedBy" text,
    "CompletionVerifiedBy" text,
    "ClientVerificationSubmittedBy" text,
    "ClientVerificationSubmittedOn" timestamp without time zone,
    "ClientVerificationComment" text,
    "ClientVerifiedUser" text,
    "IsWorkingOffline" boolean,
    "WorkOfflineOn" timestamp without time zone,
    "WorkOfflineBy" text,
    "IsPaused" boolean,
    "PausedBy" text,
    "PausedOn" timestamp without time zone,
    "PausedReason" text,
    "ResumedBy" text,
    "ResumedOn" timestamp without time zone,
    "AcknowledgementSignature" text,
    "CompletionSignature" text,
    "ClosureSignature" text,
    "ClientVerificationSignature" text,
    "IsSynced" boolean,
    "ParentId" integer,
    "SyncStatus" integer NOT NULL,
    "SyncUtcTs" integer NOT NULL,
    CONSTRAINT "PK_trCWOs" PRIMARY KEY ("Id")
);

UPDATE "Tenant" SET "CreatedDate" = TIMESTAMP '2025-01-28T09:54:55.50618', "UpdatedDate" = TIMESTAMP '2025-01-28T09:54:55.507106'
WHERE "TID" = '4199e4de-bdf8-48f8-a8a8-a5b31756a748';

UPDATE "Tenant" SET "CreatedDate" = TIMESTAMP '2025-01-28T09:54:55.507156', "UpdatedDate" = TIMESTAMP '2025-01-28T09:54:55.507156'
WHERE "TID" = 'caa4ebec-15c8-4d6b-9985-6d6b66f94e63';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2025-01-28T09:54:55.509243', "UpdatedDate" = TIMESTAMP '2025-01-28T09:54:55.509243'
WHERE "RID" = '18a79217-9fa7-460d-bccc-e74285b07531';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2025-01-28T09:54:55.509247', "UpdatedDate" = TIMESTAMP '2025-01-28T09:54:55.509247'
WHERE "RID" = 'bd69a88e-d6c1-42a1-8a3a-628843459909';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2025-01-28T09:54:55.509247', "UpdatedDate" = TIMESTAMP '2025-01-28T09:54:55.509247'
WHERE "RID" = 'c01c5086-cfa5-44ca-89d7-baa2c1accea6';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2025-01-28T09:54:55.509243', "UpdatedDate" = TIMESTAMP '2025-01-28T09:54:55.509244'
WHERE "RID" = 'd6016437-8b0f-4b0e-8175-5a11ffc480f5';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2025-01-28T09:54:55.509243', "UpdatedDate" = TIMESTAMP '2025-01-28T09:54:55.509243'
WHERE "RID" = 'f2cf879b-34f3-41da-9445-ee3bc590f224';

UPDATE "trRole" SET "CreatedDate" = TIMESTAMP '2025-01-28T09:54:55.50924', "UpdatedDate" = TIMESTAMP '2025-01-28T09:54:55.509242'
WHERE "RID" = 'fcddbf6b-88b8-4fae-ade7-63150ce1f1ec';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250128025457_createtrCwosAndAlterCase', '8.0.4');

COMMIT;

