apiVersion: apps/v1
kind: Deployment
metadata:
  name: ob-document
spec:
  selector:
    matchLabels:
      name: ob-document
  template:
    metadata:
      labels:
        name: ob-document
    spec:
      containers:
        - name: ob-document
          image: 479397374389.dkr.ecr.ap-southeast-1.amazonaws.com/ob-document/uat:ob-document_latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: uat
            - name: DATABASE_URL
              value: postgresql://postgres:2a843c492f23fdbd6d586d0911d275fc@ob-uat-ob-document.cu8h89u4zzko.ap-southeast-1.rds.amazonaws.com/ob-uat-ob-document
            - name: AWS_ACCESS_KEY_ID
              value: AKIAW7HSPNG26XNINRPP
            - name: AWS_SECRET_ACCESS_KEY
              value: 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
            - name: AWS_S3_BUCKET_NAME
              value: bucket-ob-document-uat
            - name: ENABLE_S3_DOWNLOAD
              value: 'true'
            - name: OB_EVENT_CONFIG_PATH
              value: event.config.uat.json
