apiVersion: v1
kind: Service
metadata:
  name: service-upload
  namespace: default
spec:
  selector:
    app: service-upload
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
