POST http://localhost:8080/api/landing
content-type: application/json

{
    "sectionOrder": [
        "highlights",
        "actC",
        "program",
        "faqs"
    ],
    "programs": [
        {
            "id": 1
        },
        {
            "id": 2
        }
    ]
}
