using TCCTOBK.OperationBackend.Domain.Entities;

namespace TCCTOBK.OperationBackend.Infrastructure.SeedData.Menu;
internal static class ArtCMenu
{
	public static mtMenu Group = new()
	{
		Id = new Guid("7f7eb8ad-18aa-49f7-9f0d-5f272cb26cb1"),
		Label = "",
		Type = MenuType.GROUP,
		DisplayOrder = 900
	};

	public static mtMenu ArtCGroup         		= new() { Id = new Guid("2c43fd62-d1d1-4100-a04e-7f08b0046809"), PTID = PrivilegeSeedData.AC000.PTID, Label = "Art & Culture",   	ParentId = Group.Id, IconName = "SvgPaint", Header = "Art & Culture",  		Visible = true,  Type = MenuType.GROUP,  DisplayOrder = 901 };
	public static mtMenu ArtCLandingPage   		= new() { Id = new Guid("d8f12f83-60d0-4d81-ab79-39edd94cad82"), PTID = PrivilegeSeedData.AC001.PTID, Label = "Landing Page",    	ParentId = ArtCGroup.Id,   		To = "/art-and-culture/landing",           	Visible = true,  Type = MenuType.LIST,   DisplayOrder = 902, Breadcrumb = "[\"Art & Culture\"]" };
	
	public static mtMenu ArtC              		= new() { Id = new Guid("efe3a53a-92a7-452e-a541-793782a805c2"), PTID = PrivilegeSeedData.AC002.PTID, Label = "Art & Culture Category",        ParentId = ArtCGroup.Id, To = "/art-and-culture/art-c",             	Visible = true,  Type = MenuType.LIST,   DisplayOrder = 903, Breadcrumb = "[\"Art & Culture\"]" };
	public static mtMenu ArtCCreateArtC        	= new() { Id = new Guid("482f7f4d-aac8-4ef2-90a3-c7178852499f"), PTID = PrivilegeSeedData.AC003.PTID, Label = "Create Art & Culture Category", ParentId = ArtC.Id,  	To = "/art-and-culture/art-c/create",	   	Visible = false, Type = MenuType.CREATE, DisplayOrder = 904, Breadcrumb = "[\"Art & Culture\", \"Art+C\"]" };
	public static mtMenu ArtCEditArtC          	= new() { Id = new Guid("15aaa462-e484-4ca4-b355-5b5440f5eef8"), PTID = PrivilegeSeedData.AC004.PTID, Label = "Edit Art & Culture Category",   ParentId = ArtC.Id,      To = "/art-and-culture/art-c/edit/:id",    	Visible = false, Type = MenuType.EDIT,   DisplayOrder = 905, Breadcrumb = "[\"Art & Culture\", \"Art+C\"]" };
	
	public static mtMenu ArtCProgram           	= new() { Id = new Guid("3d147124-ac5d-42a1-b1e0-7e3a531bbe8b"), PTID = PrivilegeSeedData.AC005.PTID, Label = "Program",			ParentId = ArtCGroup.Id,   		To = "/art-and-culture/programs",          	Visible = true,  Type = MenuType.LIST,   DisplayOrder = 906, Breadcrumb = "[\"Art & Culture\"]" };
	public static mtMenu ArtCCreateProgram     	= new() { Id = new Guid("345719dc-c6df-4d65-8a82-752273b9864b"), PTID = PrivilegeSeedData.AC006.PTID, Label = "Create Program",		ParentId = ArtCProgram.Id,  	To = "/art-and-culture/programs/create",   	Visible = false, Type = MenuType.CREATE, DisplayOrder = 907, Breadcrumb = "[\"Art & Culture\", \"Program\"]" };
	public static mtMenu ArtCEditProgram       	= new() { Id = new Guid("7bfa25e4-7d0f-4fa2-81f4-d464e0888cae"), PTID = PrivilegeSeedData.AC007.PTID, Label = "Edit Program",      	ParentId = ArtCProgram.Id,  	To = "/art-and-culture/programs/edit/:id", 	Visible = false, Type = MenuType.EDIT,   DisplayOrder = 908, Breadcrumb = "[\"Art & Culture\", \"Program\"]" };
	
	public static mtMenu ArtCAddOn             	= new() { Id = new Guid("e63e87c3-9ab2-4d21-9b0b-435ce7ca3206"), PTID = PrivilegeSeedData.AC008.PTID, Label = "Add-On",				ParentId = ArtCGroup.Id,   		To = "/art-and-culture/add-on",            	Visible = true,  Type = MenuType.LIST,   DisplayOrder = 909, Breadcrumb = "[\"Art & Culture\"]" };
	public static mtMenu ArtCCreateAddOn       	= new() { Id = new Guid("b28c71e1-ac54-4706-8b9e-e435139a8ea3"), PTID = PrivilegeSeedData.AC009.PTID, Label = "Create Add-On",		ParentId = ArtCAddOn.Id,  	   	To = "/art-and-culture/add-on/create",	   	Visible = false, Type = MenuType.CREATE, DisplayOrder = 910, Breadcrumb = "[\"Art & Culture\", \"Add-On\"]" };
	public static mtMenu ArtCEditAddOn         	= new() { Id = new Guid("4411d520-34ac-4f32-9275-5158b3d14d3f"), PTID = PrivilegeSeedData.AC010.PTID, Label = "Edit Add-On",      	ParentId = ArtCAddOn.Id,        To = "/art-and-culture/add-on/edit/:id",   	Visible = false, Type = MenuType.EDIT,   DisplayOrder = 911, Breadcrumb = "[\"Art & Culture\", \"Add-On\"]" };
	
	public static mtMenu ArtCPlaylist          	= new() { Id = new Guid("ffd40f99-f1c4-4e6e-b2b8-5cd9d6c6fccc"), PTID = PrivilegeSeedData.AC011.PTID, Label = "Playlist",			ParentId = ArtCGroup.Id,   		To = "/art-and-culture/playlist",          	Visible = true,  Type = MenuType.LIST,   DisplayOrder = 912, Breadcrumb = "[\"Art & Culture\"]" };
	public static mtMenu ArtCCreatePlaylist    	= new() { Id = new Guid("de9a81e1-3454-4570-aa6b-ca9cae6545d1"), PTID = PrivilegeSeedData.AC012.PTID, Label = "Create Playlist",	ParentId = ArtCPlaylist.Id,  	To = "/art-and-culture/playlist/create",   	Visible = false, Type = MenuType.CREATE, DisplayOrder = 913, Breadcrumb = "[\"Art & Culture\", \"Playlist\"]" };
	public static mtMenu ArtCEditPlaylist      	= new() { Id = new Guid("f270445f-018e-4f68-b9f9-b8b10e7350fe"), PTID = PrivilegeSeedData.AC013.PTID, Label = "Edit Playlist",      ParentId = ArtCPlaylist.Id,     To = "/art-and-culture/playlist/edit/:id", 	Visible = false, Type = MenuType.EDIT,   DisplayOrder = 914, Breadcrumb = "[\"Art & Culture\", \"Playlist\"]" };

	public static mtMenu ArtCPartner       		= new() { Id = new Guid("4d163844-5319-4a18-ab91-3538c6bbcb29"), PTID = PrivilegeSeedData.AC018.PTID, Label = "Partners",        	ParentId = ArtCGroup.Id,   		To = "/art-and-culture/partners",          	Visible = true,  Type = MenuType.LIST,   DisplayOrder = 915, Breadcrumb = "[\"Art & Culture\"]" };
	public static mtMenu ArtCCreatePartner 		= new() { Id = new Guid("cb77ab47-4d4f-453a-91e1-a42fb2d9a20e"), PTID = PrivilegeSeedData.AC019.PTID, Label = "Create Partners", 	ParentId = ArtCPartner.Id, 		To = "/art-and-culture/partners/create",   	Visible = false, Type = MenuType.CREATE, DisplayOrder = 916, Breadcrumb = "[\"Art & Culture\", \"Partners\"]" };
	public static mtMenu ArtCEditPartner   		= new() { Id = new Guid("8e3379a0-fa55-48a0-a873-19726a50f003"), PTID = PrivilegeSeedData.AC020.PTID, Label = "Edit Partners",   	ParentId = ArtCPartner.Id, 		To = "/art-and-culture/partners/edit/:id", 	Visible = false, Type = MenuType.EDIT,   DisplayOrder = 917, Breadcrumb = "[\"Art & Culture\", \"Partners\"]" };

	public static mtMenu ArtCFaq           		= new() { Id = new Guid("a74ad063-a576-4834-bf3b-f7fba194dd81"), PTID = PrivilegeSeedData.AC014.PTID, Label = "Faqs",            	ParentId = ArtCGroup.Id,   		To = "/art-and-culture/faqs",              	Visible = true,  Type = MenuType.LIST,   DisplayOrder = 918, Breadcrumb = "[\"Art & Culture\"]" };
	public static mtMenu ArtCCreateFaq     		= new() { Id = new Guid("9f66e2a4-fe19-42a9-a98f-65b2ebce2856"), PTID = PrivilegeSeedData.AC015.PTID, Label = "Create Faqs",     	ParentId = ArtCFaq.Id,     		To = "/art-and-culture/faqs/create",       	Visible = false, Type = MenuType.CREATE, DisplayOrder = 919, Breadcrumb = "[\"Art & Culture\", \"Faqs\"]" };
	public static mtMenu ArtCEditFaq       		= new() { Id = new Guid("d5ffc30d-aeb4-4b08-bb4b-4b8e29b7a4a9"), PTID = PrivilegeSeedData.AC016.PTID, Label = "Edit Faqs",       	ParentId = ArtCFaq.Id,     		To = "/art-and-culture/faqs/edit/:id",     	Visible = false, Type = MenuType.EDIT,   DisplayOrder = 920, Breadcrumb = "[\"Art & Culture\", \"Faqs\"]" };
	public static mtMenu ArtCOrderFaq      		= new() { Id = new Guid("291f47ff-2783-48cc-a7e1-6242bcb26d2a"), PTID = PrivilegeSeedData.AC017.PTID, Label = "Order Faqs",      	ParentId = ArtCFaq.Id,     		To = "/art-and-culture/faqs/order",        	Visible = false, Type = MenuType.EDIT,   DisplayOrder = 921, Breadcrumb = "[\"Art & Culture\"]" };
	
	public static mtMenu ArtCCreateBookingSetting = new() { Id = new Guid("2e8b45cb-6288-4744-9231-f92527bfb476"), PTID = PrivilegeSeedData.AC021.PTID, Label = "Create Booking Setting", ParentId = ArtCGroup.Id,  		To = "/art-and-culture/booking/create-setting", 	Visible = false,  Type = MenuType.CREATE, DisplayOrder = 922, Breadcrumb = "[\"Art & Culture\", \"Booking Settings\"]" };
	public static mtMenu ArtCEditBookingSetting   = new() { Id = new Guid("a3cec3e0-5e22-48d4-b149-bd6a50d6ce58"), PTID = PrivilegeSeedData.AC022.PTID, Label = "Edit Booking Setting",   ParentId = ArtCGroup.Id,  		To = "/art-and-culture/booking/edit-setting",   	Visible = false,  Type = MenuType.EDIT,   DisplayOrder = 923, Breadcrumb = "[\"Art & Culture\", \"Booking Settings\"]" };
	public static mtMenu ArtCBookingHistory       = new() { Id = new Guid("65de772d-7c34-4855-83c3-2b29786ed9ba"), PTID = PrivilegeSeedData.AC023.PTID, Label = "Booking History",        ParentId = ArtCGroup.Id,  		To = "/art-and-culture/booking/show-history",   	Visible = false,  Type = MenuType.LIST,   DisplayOrder = 924, Breadcrumb = "[\"Art & Culture\", \"Booking History\"]" };
	public static mtMenu ArtCBookingStatus        = new() { Id = new Guid("a7e4303b-40bc-492b-8cfd-951db9403628"), PTID = PrivilegeSeedData.AC024.PTID, Label = "Booking Status",         ParentId = ArtCGroup.Id,  		To = "/art-and-culture/booking/manage-status",  	Visible = true,   Type = MenuType.LIST,   DisplayOrder = 925, Breadcrumb = "[\"Art & Culture\", \"Booking Status\"]" };
	public static mtMenu ArtCEditBookingStatus    = new() { Id = new Guid("5622623f-e8b2-4d5f-9d8d-0e9413ada6d4"), PTID = PrivilegeSeedData.AC025.PTID, Label = "Edit Booking Status",    ParentId = ArtCBookingStatus.Id,  To = "/art-and-culture/booking/manage-status/:id",  Visible = false,  Type = MenuType.EDIT,   DisplayOrder = 926, Breadcrumb = "[\"Art & Culture\", \"Booking Status\"]" };
	public static mtMenu ArtCTicketScanner        = new() { Id = new Guid("9a2da925-5c65-4d18-a60d-371d8f712b9d"), PTID = PrivilegeSeedData.AC026.PTID, Label = "Ticket Scanner",         ParentId = ArtCGroup.Id,          To = "/art-and-culture/booking/ticket-scanner", 	Visible = true,   Type = MenuType.EDIT,   DisplayOrder = 927, Breadcrumb = "[\"Art & Culture\", \"Ticket Scanner\"]" };
	public static mtMenu ArtCResetTicket          = new() { Id = new Guid("3fab705d-2e74-47d3-8f20-70378dcb1f38"), PTID = PrivilegeSeedData.AC027.PTID, Label = "Reset Ticket",           ParentId = ArtCTicketScanner.Id,  To = "/art-and-culture/booking/reset-ticket/:id",   Visible = false,  Type = MenuType.EDIT,   DisplayOrder = 928, Breadcrumb = "[\"Art & Culture\", \"Reset Ticket\"]" };
}
