apiVersion: apps/v1
kind: Deployment
metadata:
  name: ob-bms
spec:
  selector:
    matchLabels:
      name: ob-bms
  template:
    metadata:
      labels:
        name: ob-bms
    spec:
      containers:
        - name: ob-bms
          image: 418772626632.dkr.ecr.ap-southeast-1.amazonaws.com/one-bangkok-sit:ob-bms_latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: dev
            - name: DATABASE_URL
              value: postgresql://postgres:2a843c492f23fdbd6d586d0911d275fc@ob-bms-sit.caktmhpgapyr.ap-southeast-1.rds.amazonaws.com/ob_bms_development
            - name: AWS_ACCESS_KEY_ID
              value: AKIAWDAGLFTEC3EVLYNN
            - name: AWS_SECRET_ACCESS_KEY
              value: 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
            - name: AWS_S3_BUCKET_NAME
              value: bucket-ob-bms-sit
            - name: ENABLE_S3_DOWNLOAD
              value: 'true'
            - name: OB_EVENT_CONFIG_PATH
              value: event.config.sit.json
            - name: OB_WEB_SOCKET_URL
              value: 'https://ws-sit.glorymtel.xyz'
