# This file defines the CI/CD pipeline for the Flutter application.
# It includes stages for linting, testing, building, and deployment.

# Define CI/CD stages
stages:
  - build
  - deploy

# Define variables used throughout the pipeline
variables:
  FLUTTER_VERSION: "3.22.3"
  ANDROID_PACKAGE_NAME: "com.onebangkok.mobileop"

### Development Scope 

# Define Android development build job (android_dev)
android_dev:
  stage: build
  image: "ghcr.io/cirruslabs/flutter:$FLUTTER_VERSION"
  environment:
    name: dev
  script:
    - export APP_VERSION=$(echo "$CI_COMMIT_TAG" | grep -oP '\d+.\d+.\d+')
    - flutter build apk --target lib/main.dart --release --build-name $APP_VERSION # Build release apk
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
  rules:
    - if: '$CI_COMMIT_TAG =~ /^dev_[0-9]+(?:.[0-9]+)+$/' 


app_distribution_dev:
  dependencies: ["android_dev"]
  stage: deploy
  image: ruby:3.1
  environment:
    name: dev
  before_script:
    - cd android
    - gem install bundler
    - bundle install
  script:
    - export APK_PATH="../build/app/outputs/flutter-apk/app-release.apk"
    - bundle exec fastlane beta # Run beta lane to Deploy on firebase app distribution
  rules:
    - if: '$CI_COMMIT_TAG =~ /^dev_[0-9]+(?:.[0-9]+)+$/' 
