{
  "openapi": "3.0.0",
  "info": {
    "title": "obk-operation-app-trunk API",
    "version": "1.0.0",
    "description": "API documentation for obk-operation-app-trunk service (unknown)",
    "contact": {
      "name": "API Documentation Generator"
    }
  },
  "servers": [
    {
      "url": "http://localhost:8000",
      "description": "Development server"
    }
  ],
  "paths": {},
  "components": {
    "schemas": {}
  }
}