apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base

commonLabels:
  app: ob-bms
  
namePrefix: ob-bms-

patches:
- patch: |-
    - op: replace
      path: /stringData/url
      value: https://github.com/mtel-thailand/ob-bms
  target:
    kind: Secret
