using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.AddVisitor;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.AddVisitorCarParkingLog;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.AuthorizeTenant;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.CaseUpdates;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.CreateFeedback;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.CreateMaintainanceRepair;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.CreateServiceRequest;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.DeactivateVisitorPass;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.GenerateNewPresigned;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.GeneratePromptPayQr;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.GetBillingHistory;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.GetCallBackPayment;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.GetEventTypes;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.GetFeedbackEventTypes;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.GetFeedbackList;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.GetInvoiceHistory;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.GetLatestMeterReading;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.GetMaintainanceRepairList;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.GetPaymentInquiry;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.GetPaymentTransaction;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.GetServiceRequestEventTypes;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.GetServiceRequestList;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.OnboardingSyncUpdates;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.RegisterNewTenant;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.SaveLogs;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.SubmitQuestionnaire;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.UpdateDefaultProperty;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.UpdateParcelReadStatus;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.UpdateVisitorStatus;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.UploadImageUrl;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetAnnouncementDetails;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetAnnouncements;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetCarParkingQuota;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetCarParkingQuotaUnitWise;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetCommonAreas;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetDefaultProperty;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetDirectoryContacts;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetFeedbackStatusCodes;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetHome;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetHouseRules;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetHouseRulesCategories;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetInvoiceDetails;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetParcels;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetParcelStatusList;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetProfile;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetPropertieDetails;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetPropertiesList;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetQuestionnaireDetail;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetQuestionnaireHistory;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetQuestionnaires;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetReceiptDetails;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetRegisteredVehicles;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetServiceRequestStatusCodes;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetStatusCodes;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetTenantDetailsParcel;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetTermsAndConditions;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetVisitorDetails;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.GetVisitorList;
using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Query.NotifyLiftArrival;

namespace TCCT.ServiceAbstraction.Application.Contracts.ServiceMindResidential;

public interface IServiceMindResidential
{
    Task<AuthorizeTenantResult> AuthorizeTenant(AuthorizeTenantCommand data);
    Task<GetHouseRulesResult> GetHouseRules(GetHouseRulesQuery data);
    Task<GetHomeResultServiceMind> GetHome(GetHomeQuery data);
    Task<List<GetDirectoryContactsResultServiceMind>> GetDirectoryContacts(GetDirectoryContactsQuery data);
    Task<GetPropertiesListResultServiceMind> GetPropertiesList(GetPropertiesListQuery data);
    Task<GetPropertieDetailsResultServiceMind> GetPropertieDetails(GetPropertieDetailsQuery data);
    Task<GetProfileResultServiceMind> GetProfile(GetProfileQuery data);
    Task<GetDefaultPropertyResult> GetDefaultProperty(GetDefaultPropertyQuery data);
    Task<UpdateDefaultPropertyResult> UpdateDefaultProperty(UpdateDefaultPropertyCommand data);
    Task<GetAnnouncementsResult> GetAnnouncements(GetAnnouncementsQuery data);
    Task<GetAnnouncementDetailsResult> GetAnnouncementDetails(GetAnnouncementDetailsQuery data);
    Task<RegisterNewTenantResult> RegisterNewTenant(RegisterNewTenantCommand data);
    Task<GetRegisteredVehiclesResult> GetRegisteredVehicles(GetRegisteredVehiclesQuery data);
    Task<GetCarParkingQuotaUnitWiseResult> GetCarParkingQuotaUnitWise(GetCarParkingQuotaUnitWiseQuery data);
    Task<GetCarParkingQuotaResult> GetCarParkingQuota(GetCarParkingQuotaQuery data);
    Task<AddVisitorResult> AddVisitor(AddVisitorCommand data);
    Task<UpdateVisitorStatusResult> UpdateVisitorStatus(UpdateVisitorStatusCommand data);
    Task<GetVisitorListResult> GetVisitorList(GetVisitorListQuery data);
    Task<GetVisitorDetailsResult> GetVisitorDetails(GetVisitorDetailsQuery data);
    Task<GetParcelsResult> GetParcels(GetParcelsQuery data);
    Task<GetParcelStatusListResult> GetParcelStatusList(GetParcelStatusListQuery data);
    Task<UpdateParcelReadStatusResult> UpdateParcelReadStatus(UpdateParcelReadStatusCommand data);
    Task<GetTenantDetailsParcelResult> GetTenantDetailsParcel(GetTenantDetailsParcelQuery data);
    Task<GenerateNewPresignedResult> GenerateNewPresigned(GenerateNewPresignedCommand data);
    Task<UploadImageUrlResult> UploadImageUrl(UploadImageUrlCommand data);
    Task<GetHouseRulesCategoriesResult> GetHouseRulesCategories(GetHouseRulesCategoriesQuery data);
    Task<SaveLogsResult> SaveLogs(SaveLogsCommand data);
    Task<GetTermsAndConditionsResult> GetTermsAndConditions(GetTermsAndConditionsQuery data);
    Task<AddVisitorCarParkingLogResult> AddVisitorCarParkingLog(AddVisitorCarParkingLogCommand data);
    Task<NotifyLiftArrivalResult> NotifyLiftArrival(NotifyLiftArrivalQuery data);
    Task<GetCommonAreasResult> GetCommonAreas(GetCommonAreasQuery data);
    Task<GetEventTypesResult> GetEventTypes(GetEventTypesCommand data);
    Task<List<GetStatusCodesResult>> GetStatusCodes(GetStatusCodesQuery data);
    Task<GetMaintainanceRepairListResult> GetMaintainanceRepairList(GetMaintainanceRepairListCommand data);
    Task<CreateMaintainanceRepairResult> CreateMaintainanceRepair(CreateMaintainanceRepairCommand data);
    Task<GetServiceRequestEventTypesResult> GetServiceRequestEventTypes(GetServiceRequestEventTypesCommand data);
    Task<List<GetServiceRequestStatusCodesResult>> GetServiceRequestStatusCodes(GetServiceRequestStatusCodesQuery data);
    Task<GetServiceRequestListResult> GetServiceRequestList(GetServiceRequestListCommand data);
    Task<CreateServiceRequestResult> CreateServiceRequest(CreateServiceRequestCommand data);
    Task<GetFeedbackEventTypesResult> GetFeedbackEventTypes(GetFeedbackEventTypesCommand data);
    Task<List<GetFeedbackStatusCodesResult>> GetFeedbackStatusCodes(GetFeedbackStatusCodesQuery data);
    Task<GetFeedbackListResult> GetFeedbackList(GetFeedbackListCommand data);
    Task<CreateFeedbackResult> CreateFeedback(CreateFeedbackCommand data);
    Task<CaseUpdatesResult> CaseUpdates(CaseUpdatesCommand data);
    Task<DeactivateVisitorPassResult> DeactivateVisitorPass(DeactivateVisitorPassCommand data);
    Task<GetQuestionnairesResult> GetQuestionnaires(GetQuestionnairesQuery data);
    Task<GetQuestionnaireDetailResult> GetQuestionnaireDetails(GetQuestionnaireDetailQuery data);
    Task<GetQuestionnaireHistoryResult> GetQuestionnaireHistory(GetQuestionnaireHistoryQuery data);
    Task<SubmitQuestionnaireResult> SubmitQuestionnaire(SubmitQuestionnaireCommand data);
    Task<OnboardingSyncUpdatesResult> OnboardingSyncUpdates(OnboardingSyncUpdatesCommand data);
    Task<GeneratePromptPayQrResult> GeneratePromptPayQr(GeneratePromptPayQrCommand data);
    Task<GetCallBackPaymentResult> GetCallBackPayment(GetCallBackPaymentCommand data);
    Task<GetPaymentTransactionResult> GetPaymentTransaction(GetPaymentTransactionCommand data);
    Task<GetPaymentInquiryResult> GetPaymentInquiry(GetPaymentInquiryCommand data);
    Task<GetLatestMeterReadingResult> GetLatestMeterReading(GetLatestMeterReadingCommand data);
    Task<GetBillingHistoryResult> GetBillingHistory(GetBillingHistoryCommand data);
    Task<GetInvoiceHistoryResult> GetInvoiceHistory(GetInvoiceHistoryCommand data);
    Task<GetInvoiceDetailsResult> GetInvoiceDetails(GetInvoiceDetailsQuery data);
    Task<GetReceiptDetailsResult> GetReceiptDetails(GetReceiptDetailsQuery data);


}