using TCCT.ServiceAbstraction.Application.Features.ServiceMindResidential.Command.AuthorizeTenant;
namespace TCCT.ServiceAbstraction.Application.Contracts.ServiceMindResidential;

public interface IServiceMindResidentialEndpointProvider
{
	HttpClient GetClientFromFactory();
	Task<AuthorizeTenantResult> AuthorizeTenant(string? tenantId);
	Task<HttpClient> GetClientFromFactoryWithBearer(string? tenantId);
	string GetHouseRulesUrl();
	string GetHomeUrl();
	string GetDirectoryContactsUrl();
	string GetPropertiesUrl();
	string GetDefaultPropertyUrl();
	string GetProfileUrl();
	string UpdateDefaultPropertyUrl();
	string GetAnnouncementsUrl();
	string RegisterNewTenantUrl();
	string GetRegisteredVehiclesUrl();
	string GetCarParkingQuotaUnitWiseUrl();
	string GetCarParkingQuotaUrl();
	string GetClientSecret();
	string AddVisitorUrl();
	string GetVisitorListUrl();
	string GetVisitorDetailsUrl();
	string UpdateVisitorStatusUrl();
	string GetParcelsUrl();
	string GetParcelStatusListUrl();
	string UpdateParcelReadStatusUrl();
	string GetTenantDetailsParcelUrl();
	string GenerateNewPresignedUrl();
	string UploadImageUrl();
	string GetHouseRulesCategoriesUrl();
	string SaveLogsUrl();
	string GetTermsAndConditionsUrl();
	string AddVisitorCarParkingLogUrl();
	string NotifyLiftArrivalUrl();
	string GetStatusCodesUrl();
	string GetEventTypesUrl();
	string GetMaintainanceRepairListUrl();
	string GetCommonAreasUrl();
	string CreateMaintainanceRepairUrl();
	string GetServiceRequestStatusCodesUrl();
	string GetServiceRequestEventTypesUrl();
	string GetServiceRequestListUrl();
	string CreateServiceRequestUrl();
	string GetFeedbackStatusCodesUrl();
	string GetFeedbackEventTypesUrl();
	string GetFeedbackListUrl();
	string CreateFeedbackUrl();
	string CaseUpdatesUrl();
	string DeactivateVisitorPassUrl();
	string GetQuestionnairesUrl();
	string GetQuestionnaireDetailsUrl();
	string GetQuestionnaireHistoryUrl();
	string SubmitQuestionnaireUrl();
	string OnboardingSyncUpdatesUrl();
	string GeneratePromptPayQrUrl();
	string GetCallBackPaymentUrl();
	string GetPaymentTransactionUrl();
	string GetPaymentInquiryUrl();
	string GetLatestMeterReadingUrl();
	string GetBillingHistoryUrl();
	string GetInvoiceHistoryUrl();
	string GetInvoiceDetailsUrl();
	string GetReceiptDetailsUrl();
}