version: '3.4'

services:

  tcct.serviceabstraction.api:
    container_name: staging-tcct-serviceabstraction-api
    image: registry.lab.tcctech.app/obk/tcct-serviceabstraction/tcct.serviceabstraction.api:staging
    environment:
      - WEBSITE_TIME_ZONE=Asia/Bangkok
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - SERILOG_SEQ_ENDPOINT=x
      - SERILOG_SEQ_APIKEY=x
      - CUSTOMER_KC_VERSION=x
      - CUSTOMER_KC_ENDPOINT=x
      - CUSTOMER_KC_REALMS=x
      - CUSTOMER_KC_REALMSAUTHATTRIBUTE=x
      - CUSTOMER_KC_CLIENTID=x
      - CUSTOMER_KC_CLIENTSECRET=x
      - OPERATION_KC_VERSION=x
      - OPERATION_KC_ENDPOINT=x
      - OPERATION_KC_REALMS=x
      - OPERATION_KC_REALMSAUTHATTRIBUTE=x
      - OPERATION_KC_CLIENTID=x
      - OPERATION_KC_CLIENTSECRET=x
      - AIRQUALITY_SITEID={}
      - AIRQUALITY_ENDPOINT=x
      - CERTIS_ENDPOINT=x
      - CERTIS_DMS=x
      - CERTIS_CORE=x
      - CERTIS_CMS=x
      - CERTIS_APIKEY=x
      - FINEDAYIVIVA_ENDPOINT=x
      - FINEDAYIVIVA_USERNAME=x
      - FINEDAYIVIVA_PASSWORD=x
      - FINEDAYRESIDENCE_ENDPOINT=x
      - FINEDAYRESIDENCE_USERNAME=x
      - FINEDAYRESIDENCE_PASSWORD=x
      - NETATMO_ENDPOINT=x
      - NETATMO_DB_HOST=x
      - NETATMO_DB_PORT=x
      - NETATMO_DB_USERNAME=x
      - NETATMO_DB_PASSWORD=x
      - NETATMO_DB_DATABASE=x
      - CARPARKPAYMENT_ENDPOINT=x
      - CARPARKPAYMENT_ARGENTOENDPOINT=x
      - CARPARKPAYMENT_ARGENTOMERCHANTID=x
      - CARPARKPAYMENT_ARGENTOPRIVATEKEY=x
      - SERVICEMIND_ENDPOINT=x
      - SERVICEMIND_CLIENTSECRET=x
      - SERVICEMIND_DEFAULTTENANT=x
      - LBS_DB_DATABASE=x
      - LBS_DB_HOST=x
      - LBS_DB_PASSWORD=x
      - LBS_DB_PORT=x
      - LBS_DB_USERNAME=x
      - MT_SERVICE_ENDPOINT=x
      - MT_SERVICE_APIKEY=x
      - FINEDAYRESIDENCE_ENDPOINTBOOKING=x
      - REDIS_URL=x
      - REDIS_PORT=x
      - REDIS_DATABASE=x
      - CERTIS_MAINENDPOINT=x
      - CERTIS_CLIENTID=x
      - CERTIS_CLIENTSECRET=x
      - CERTIS_TENANTHEADERS=x
      - INNOFLEX_ENDPOINT_ONBOARD=x
      - CERTIS_EXTERNAL_ENDPOINT=x
      - CERTIS_EXTERNAL_CLIENT=x
      - MT_SERVICE_ENDPOINT_CARPARK=x
      - CERTIS_WFM=x
      - EV_ENDPOINT=x
      - EV_PUBLIC_KEY=x
      - EV_PRIVATE_KEY=x
      - CARPARKPAYMENT_ARGENTO_MERCHANTID_ONE89CARPARK=x
      - CARPARKPAYMENT_ARGENTO_PRIVATEKEY_ONE89CARPARK=x
      - SUBCODE_ONE89_CARPARK=x
      - PAYMENT_ARGENTO_MERCHANTID_ONE89EV=x
      - PAYMENT_ARGENTO_PRIVATEKEY_ONE89EV=x
      - SUBCODE_ONE89_EV=x
      - PAYMENT_REF2_ONE89_EV=x
      - PAYMENT_ARGENTO_MERCHANTID_ONE89ELECTRIC=x
      - PAYMENT_ARGENTO_PRIVATEKEY_ONE89ELECTRIC=x
      - SUBCODE_ONE89_ELECTRIC=x
      - PAYMENT_REF2_ONE89_ELECTRIC=x
      - PAYMENT_ARGENTO_MERCHANTID_ONE89BILL=x
      - PAYMENT_ARGENTO_PRIVATEKEY_ONE89BILL=x
      - SUBCODE_ONE89_BILL=x
      - PAYMENT_REF2_ONE89_BILL=x
    ports:
      - "7001:80"
    networks:
      - staging-serviceabstraction
    restart: always

networks:
  staging-serviceabstraction:
    name: staging-serviceabstraction
    driver: bridge