// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TCCTOBK.OperationBackend.Infrastructure.Database;

#nullable disable

namespace TCCTOBK.OperationBackend.Infrastructure.Database.Migrations
{
    [DbContext(typeof(TCCTOBKContext))]
    [Migration("20240714165317_AddTenantInRoleAndFailAttampt")]
    partial class AddTenantInRoleAndFailAttampt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.SOCUser", b =>
                {
                    b.Property<Guid>("SID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("FirstNameEn")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("IdentifyNumber")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying");

                    b.Property<int>("IdentifyType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("LastNameEn")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("SID");

                    b.ToTable("SOCUser");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("TID");

                    b.ToTable("Tenant");

                    b.HasData(
                        new
                        {
                            TID = new Guid("4199e4de-bdf8-48f8-a8a8-a5b31756a748"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "System",
                            CreatedDate = new DateTime(2024, 7, 14, 23, 53, 15, 570, DateTimeKind.Local).AddTicks(8520),
                            IsActive = true,
                            Name = "OBK CMS",
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "System",
                            UpdatedDate = new DateTime(2024, 7, 14, 23, 53, 15, 590, DateTimeKind.Local).AddTicks(4530),
                            description = "One bangkok CMS"
                        },
                        new
                        {
                            TID = new Guid("caa4ebec-15c8-4d6b-9985-6d6b66f94e63"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "System",
                            CreatedDate = new DateTime(2024, 7, 14, 23, 53, 15, 590, DateTimeKind.Local).AddTicks(5250),
                            IsActive = true,
                            Name = "Operation app",
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "System",
                            UpdatedDate = new DateTime(2024, 7, 14, 23, 53, 15, 590, DateTimeKind.Local).AddTicks(5260),
                            description = "Operation app"
                        });
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.TenantMember", b =>
                {
                    b.Property<Guid>("MID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TID")
                        .HasColumnType("uuid");

                    b.HasKey("MID", "TID");

                    b.HasIndex("TID");

                    b.ToTable("TenantMember");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.TimeCardEntries", b =>
                {
                    b.Property<Guid>("CAID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckIn")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CheckOut")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KCUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TSID")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CAID");

                    b.ToTable("TimeCardEntries");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.TimeSheet", b =>
                {
                    b.Property<Guid>("TSID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckCode")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Location")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TSID");

                    b.ToTable("TimeSheet");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.mtActionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("mtActionType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8eb7171-de01-4a85-a955-711b211eecc2"),
                            Action = "qr",
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 595, DateTimeKind.Local).AddTicks(7790),
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 595, DateTimeKind.Local).AddTicks(7920)
                        },
                        new
                        {
                            Id = new Guid("e8eb7171-de01-4a85-a955-711b211eecc3"),
                            Action = "confirm",
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 595, DateTimeKind.Local).AddTicks(7970),
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 595, DateTimeKind.Local).AddTicks(7970)
                        },
                        new
                        {
                            Id = new Guid("e8eb7171-de01-4a85-a955-711b211eecc4"),
                            Action = "photo",
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 595, DateTimeKind.Local).AddTicks(7980),
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 595, DateTimeKind.Local).AddTicks(7980)
                        },
                        new
                        {
                            Id = new Guid("e8eb7171-de01-4a85-a955-711b211eecc5"),
                            Action = "complex",
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 595, DateTimeKind.Local).AddTicks(8110),
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 595, DateTimeKind.Local).AddTicks(8110)
                        });
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.mtAppConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.ToTable("mtAppConfig");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.mtHomeContent", b =>
                {
                    b.Property<Guid>("HCID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("RemoteConfigDataJson")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("RemoteConfigResponseDataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying");

                    b.HasKey("HCID");

                    b.ToTable("HomeContent");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.mtMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Breadcrumb")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying");

                    b.Property<string>("Class")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Header")
                        .HasMaxLength(200)
                        .HasColumnType("character varying");

                    b.Property<string>("IconClass")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying");

                    b.Property<string>("IconName")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying");

                    b.Property<Guid?>("PTID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Separator")
                        .HasColumnType("boolean");

                    b.Property<string>("To")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("mtMenu");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.mtPrivilege", b =>
                {
                    b.Property<Guid>("PID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying");

                    b.HasKey("PID");

                    b.ToTable("mtPrivilege");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.mtPrivilegeItem", b =>
                {
                    b.Property<Guid>("PTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying");

                    b.Property<Guid>("PID")
                        .HasColumnType("uuid");

                    b.HasKey("PTID");

                    b.HasIndex("PID");

                    b.ToTable("mtPrivilegeItem");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.taMember", b =>
                {
                    b.Property<Guid>("MID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataJson")
                        .HasColumnType("character varying");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying");

                    b.Property<int>("FailAttempt")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyCloakUserId")
                        .HasColumnType("character varying");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MID");

                    b.ToTable("taMember");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionType")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying");

                    b.Property<string>("MetaData")
                        .HasColumnType("json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActionType");

                    b.ToTable("trAction");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2aa84ed4-a495-47c8-913f-fa5928c1b4b8"),
                            ActionType = new Guid("e8eb7171-de01-4a85-a955-711b211eecc2"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(1730),
                            Description = "L-10, Fire Exit Door 3 (Passenger Elevator)",
                            Name = "Scan QR Code",
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(1750)
                        },
                        new
                        {
                            Id = new Guid("3ff4f468-53ef-48a3-8781-61a8a053fa99"),
                            ActionType = new Guid("e8eb7171-de01-4a85-a955-711b211eecc2"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(1790),
                            Description = "L-10, Fire Exit Door 2 (Passenger Elevator)",
                            Name = "Scan QR Code",
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(1790)
                        },
                        new
                        {
                            Id = new Guid("564d0272-92c8-4108-82b2-0f98882058d4"),
                            ActionType = new Guid("e8eb7171-de01-4a85-a955-711b211eecc3"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(1790),
                            Description = "Inspect fire exits and make sure all the doors are closed",
                            Name = "Inspect Fire doors",
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(1800)
                        },
                        new
                        {
                            Id = new Guid("6d174fd6-b597-4b16-a117-08b7a84be839"),
                            ActionType = new Guid("e8eb7171-de01-4a85-a955-711b211eecc3"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(1800),
                            Description = "Inspect fire exits and make sure all the doors are closed",
                            Name = "Inspect Fire doors",
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(1830)
                        },
                        new
                        {
                            Id = new Guid("c1cb273c-570a-42f5-b563-66bac08911cc"),
                            ActionType = new Guid("e8eb7171-de01-4a85-a955-711b211eecc3"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(1830),
                            Description = "Check Distress Alert",
                            Name = "Distress Alert",
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(1840)
                        },
                        new
                        {
                            Id = new Guid("e8eb7171-de01-4a85-a955-711b211eecc1"),
                            ActionType = new Guid("e8eb7171-de01-4a85-a955-711b211eecc2"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(1860),
                            Description = "L-10, Fire Exit Door 1 (Passenger Elevator)",
                            Name = "Scan QR Code",
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(1860)
                        },
                        new
                        {
                            Id = new Guid("c1cb273c-570a-42f5-b563-66bac08911cd"),
                            ActionType = new Guid("e8eb7171-de01-4a85-a955-711b211eecc5"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(1860),
                            Description = "Check Distress Alert",
                            Name = "Distress Alert",
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(1860)
                        });
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trActivityProcedure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubtaskActions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("trActivityProcedure");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trInviteMember", b =>
                {
                    b.Property<Guid>("IMID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MID")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("IMID");

                    b.HasIndex("MID");

                    b.ToTable("trInviteMember");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trResetPassword", b =>
                {
                    b.Property<Guid>("RPID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MID")
                        .HasColumnType("uuid");

                    b.Property<string>("ResetPasswordCode")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("RPID");

                    b.HasIndex("MID");

                    b.ToTable("trResetPassword");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trRole", b =>
                {
                    b.Property<Guid>("RID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying");

                    b.Property<Guid>("TID")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("RID");

                    b.HasIndex("TID");

                    b.ToTable("trRole");

                    b.HasData(
                        new
                        {
                            RID = new Guid("fcddbf6b-88b8-4fae-ade7-63150ce1f1ec"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "System",
                            CreatedDate = new DateTime(2024, 7, 14, 23, 53, 15, 598, DateTimeKind.Local).AddTicks(5800),
                            Description = "Technician",
                            IsActive = true,
                            IsDelete = false,
                            Name = "Technician",
                            TID = new Guid("caa4ebec-15c8-4d6b-9985-6d6b66f94e63"),
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "System",
                            UpdatedDate = new DateTime(2024, 7, 14, 23, 53, 15, 598, DateTimeKind.Local).AddTicks(5820)
                        },
                        new
                        {
                            RID = new Guid("18a79217-9fa7-460d-bccc-e74285b07531"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "System",
                            CreatedDate = new DateTime(2024, 7, 14, 23, 53, 15, 598, DateTimeKind.Local).AddTicks(5920),
                            Description = "Cleaning",
                            IsActive = true,
                            IsDelete = false,
                            Name = "Cleaning",
                            TID = new Guid("caa4ebec-15c8-4d6b-9985-6d6b66f94e63"),
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "System",
                            UpdatedDate = new DateTime(2024, 7, 14, 23, 53, 15, 598, DateTimeKind.Local).AddTicks(5920)
                        },
                        new
                        {
                            RID = new Guid("f2cf879b-34f3-41da-9445-ee3bc590f224"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "System",
                            CreatedDate = new DateTime(2024, 7, 14, 23, 53, 15, 598, DateTimeKind.Local).AddTicks(5930),
                            Description = "Supervisor",
                            IsActive = true,
                            IsDelete = false,
                            Name = "Supervisor",
                            TID = new Guid("caa4ebec-15c8-4d6b-9985-6d6b66f94e63"),
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "System",
                            UpdatedDate = new DateTime(2024, 7, 14, 23, 53, 15, 598, DateTimeKind.Local).AddTicks(5930)
                        });
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trRoleMember", b =>
                {
                    b.Property<Guid>("RID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("RID", "MID");

                    b.HasIndex("MID");

                    b.ToTable("trRoleMember");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trRolePrivilegeItem", b =>
                {
                    b.Property<Guid>("RID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PTID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("RID", "PTID");

                    b.HasIndex("PTID");

                    b.ToTable("trRolePrivilegeItem");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trSubtask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("trSubtask");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77e2f48c-8178-4df5-9b84-48bfd253a496"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(3880),
                            Name = "Distress Alert",
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(3890)
                        },
                        new
                        {
                            Id = new Guid("eaab304c-89e1-484c-aefe-0e4e3e27e911"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(3920),
                            Name = "L-10, Fire Exit Door 3 (Passenger Elevator)",
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(3920)
                        },
                        new
                        {
                            Id = new Guid("1a157bf0-4748-4589-91cc-1450e0c06596"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(3930),
                            Name = "L-10, Fire Exit Door 2 (Passenger Elevator)",
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(3930)
                        },
                        new
                        {
                            Id = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(3930),
                            Name = "L-10, Fire Exit Door 4 (Passenger Elevator)",
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(3930)
                        },
                        new
                        {
                            Id = new Guid("35d4cfa7-04ea-473a-9b50-c9751843ead5"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(3930),
                            Name = "L-10, Fire Exit Door 1 (Passenger Elevator)",
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(3940)
                        });
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trSubtaskAction", b =>
                {
                    b.Property<Guid>("Subtask")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Action")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MetaData")
                        .HasColumnType("json");

                    b.Property<string>("Reading")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Subtask", "Action");

                    b.HasIndex("Action");

                    b.ToTable("trSubtaskAction");

                    b.HasData(
                        new
                        {
                            Subtask = new Guid("1a157bf0-4748-4589-91cc-1450e0c06596"),
                            Action = new Guid("3ff4f468-53ef-48a3-8781-61a8a053fa99"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9450),
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9460)
                        },
                        new
                        {
                            Subtask = new Guid("1a157bf0-4748-4589-91cc-1450e0c06596"),
                            Action = new Guid("564d0272-92c8-4108-82b2-0f98882058d4"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9480),
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9480)
                        },
                        new
                        {
                            Subtask = new Guid("1a157bf0-4748-4589-91cc-1450e0c06596"),
                            Action = new Guid("6d174fd6-b597-4b16-a117-08b7a84be839"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9490),
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9520)
                        },
                        new
                        {
                            Subtask = new Guid("35d4cfa7-04ea-473a-9b50-c9751843ead5"),
                            Action = new Guid("564d0272-92c8-4108-82b2-0f98882058d4"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9520),
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9530)
                        },
                        new
                        {
                            Subtask = new Guid("35d4cfa7-04ea-473a-9b50-c9751843ead5"),
                            Action = new Guid("6d174fd6-b597-4b16-a117-08b7a84be839"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9530),
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9530)
                        },
                        new
                        {
                            Subtask = new Guid("35d4cfa7-04ea-473a-9b50-c9751843ead5"),
                            Action = new Guid("e8eb7171-de01-4a85-a955-711b211eecc1"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9540),
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9540)
                        },
                        new
                        {
                            Subtask = new Guid("eaab304c-89e1-484c-aefe-0e4e3e27e911"),
                            Action = new Guid("2aa84ed4-a495-47c8-913f-fa5928c1b4b8"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9540),
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9550)
                        },
                        new
                        {
                            Subtask = new Guid("eaab304c-89e1-484c-aefe-0e4e3e27e911"),
                            Action = new Guid("564d0272-92c8-4108-82b2-0f98882058d4"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9550),
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9550)
                        },
                        new
                        {
                            Subtask = new Guid("eaab304c-89e1-484c-aefe-0e4e3e27e911"),
                            Action = new Guid("6d174fd6-b597-4b16-a117-08b7a84be839"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9550),
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9560)
                        },
                        new
                        {
                            Subtask = new Guid("77e2f48c-8178-4df5-9b84-48bfd253a496"),
                            Action = new Guid("c1cb273c-570a-42f5-b563-66bac08911cc"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9560),
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9560)
                        },
                        new
                        {
                            Subtask = new Guid("77e2f48c-8178-4df5-9b84-48bfd253a496"),
                            Action = new Guid("c1cb273c-570a-42f5-b563-66bac08911cd"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9570),
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(9570)
                        });
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying");

                    b.Property<DateTime?>("StartDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("trTask");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c055101-2271-44e0-95fe-bcf2c59a459b"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(6140),
                            LocationId = new Guid("2c055101-2271-44e0-95fe-bcf2c59a459a"),
                            MemberId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Illegal Parking",
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(6150)
                        },
                        new
                        {
                            Id = new Guid("4422cc3c-0ea5-4d73-a31e-a42485a81003"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(6180),
                            LocationId = new Guid("2c055101-2271-44e0-95fe-bcf2c59a459a"),
                            MemberId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Distress Alert",
                            StatusId = 0,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(6180)
                        });
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trTaskSubtask", b =>
                {
                    b.Property<Guid>("Task")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Subtask")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Task", "Subtask");

                    b.HasIndex("Subtask");

                    b.ToTable("trTaskSubtask");

                    b.HasData(
                        new
                        {
                            Task = new Guid("2c055101-2271-44e0-95fe-bcf2c59a459b"),
                            Subtask = new Guid("1a157bf0-4748-4589-91cc-1450e0c06596"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(7470),
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(7470)
                        },
                        new
                        {
                            Task = new Guid("2c055101-2271-44e0-95fe-bcf2c59a459b"),
                            Subtask = new Guid("35d4cfa7-04ea-473a-9b50-c9751843ead5"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(7500),
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(7500)
                        },
                        new
                        {
                            Task = new Guid("2c055101-2271-44e0-95fe-bcf2c59a459b"),
                            Subtask = new Guid("eaab304c-89e1-484c-aefe-0e4e3e27e911"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(7500),
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(7500)
                        },
                        new
                        {
                            Task = new Guid("4422cc3c-0ea5-4d73-a31e-a42485a81003"),
                            Subtask = new Guid("77e2f48c-8178-4df5-9b84-48bfd253a496"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(7510),
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 596, DateTimeKind.Local).AddTicks(7510)
                        });
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Location", b =>
                {
                    b.Property<Guid>("LID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LocationType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("LID");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            LID = new Guid("2c055101-2271-44e0-95fe-bcf2c59a459a"),
                            CreatedBy = "00000000-0000-0000-0000-000000000000",
                            CreatedByName = "system",
                            CreatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 597, DateTimeKind.Local).AddTicks(2510),
                            LocationName = "Location 1",
                            LocationType = 1,
                            UpdatedBy = "00000000-0000-0000-0000-000000000000",
                            UpdatedByName = "system",
                            UpdatedDate = new DateTime(2024, 6, 14, 23, 53, 15, 597, DateTimeKind.Local).AddTicks(2520)
                        });
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.SOCUserTanent", b =>
                {
                    b.Property<Guid>("SID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SOCUserSID")
                        .HasColumnType("uuid");

                    b.HasKey("SID", "TID");

                    b.HasIndex("SOCUserSID");

                    b.HasIndex("TID");

                    b.ToTable("SOCUserTanent");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.SpotCoordinate", b =>
                {
                    b.Property<Guid>("CID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LID")
                        .HasColumnType("uuid");

                    b.Property<float>("Lat")
                        .HasColumnType("real");

                    b.Property<float>("Long")
                        .HasColumnType("real");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CID");

                    b.HasIndex("LID");

                    b.ToTable("SpotCoordinate");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Unit", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("Area")
                        .HasColumnType("real");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IndoorSpillOutSeating")
                        .HasColumnType("integer");

                    b.Property<float?>("InlineAreaIndoorZone")
                        .HasColumnType("real");

                    b.Property<float?>("InlineAreaOutdoorZone")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LID")
                        .HasColumnType("uuid");

                    b.Property<float?>("Lat")
                        .HasColumnType("real");

                    b.Property<float?>("Long")
                        .HasColumnType("real");

                    b.Property<string>("UnitNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UID");

                    b.HasIndex("LID");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.WorkTransaction", b =>
                {
                    b.Property<Guid>("TID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HoneywellResponeDataJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SID")
                        .HasColumnType("uuid");

                    b.Property<int>("Transactiontype")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying");

                    b.Property<DateTime>("UpdatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TID");

                    b.ToTable("WorkTransaction");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.trRoleSOCUser", b =>
                {
                    b.Property<Guid>("RID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("RID", "SID");

                    b.HasIndex("SID");

                    b.ToTable("trRoleSOCUser");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.TenantMember", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.taMember", "taMember")
                        .WithMany("tenantMembers")
                        .HasForeignKey("MID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.Tenant", "Tenant")
                        .WithMany("tenantMembers")
                        .HasForeignKey("TID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("taMember");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.mtMenu", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.mtMenu", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.mtPrivilegeItem", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.mtPrivilege", "mtPrivilege")
                        .WithMany("mtPrivilegeItems")
                        .HasForeignKey("PID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mtPrivilege");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trAction", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.mtActionType", "mtActionType")
                        .WithMany()
                        .HasForeignKey("ActionType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mtActionType");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trInviteMember", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.taMember", "taMember")
                        .WithMany()
                        .HasForeignKey("MID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("taMember");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trResetPassword", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.taMember", "taMember")
                        .WithMany()
                        .HasForeignKey("MID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("taMember");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trRole", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trRoleMember", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.taMember", "taMember")
                        .WithMany("trRoleMembers")
                        .HasForeignKey("MID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.trRole", "trRole")
                        .WithMany("trRoleMembers")
                        .HasForeignKey("RID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("taMember");

                    b.Navigation("trRole");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trRolePrivilegeItem", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.mtPrivilegeItem", "mtPrivilegeItem")
                        .WithMany()
                        .HasForeignKey("PTID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.trRole", "trRole")
                        .WithMany("trRolePrivilagesItem")
                        .HasForeignKey("RID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mtPrivilegeItem");

                    b.Navigation("trRole");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trSubtaskAction", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.trAction", "trAction")
                        .WithMany()
                        .HasForeignKey("Action")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.trSubtask", "trSubtask")
                        .WithMany("trSubtaskAction")
                        .HasForeignKey("Subtask")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("trAction");

                    b.Navigation("trSubtask");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trTask", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Location", "location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("location");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trTaskSubtask", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.trSubtask", "trSubtask")
                        .WithMany()
                        .HasForeignKey("Subtask")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.trTask", "trTask")
                        .WithMany("trTaskSubtask")
                        .HasForeignKey("Task")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("trSubtask");

                    b.Navigation("trTask");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.SOCUserTanent", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.SOCUser", null)
                        .WithMany("SOCUserTanent")
                        .HasForeignKey("SOCUserSID");

                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.SpotCoordinate", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Location", "Location")
                        .WithMany("SpotCoordinate")
                        .HasForeignKey("LID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Unit", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Location", "Location")
                        .WithMany("Unit")
                        .HasForeignKey("LID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.trRoleSOCUser", b =>
                {
                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.trRole", "trRole")
                        .WithMany()
                        .HasForeignKey("RID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCCTOBK.OperationBackend.Domain.Entities.SOCUser", "SOCUser")
                        .WithMany("trRoleSOCUser")
                        .HasForeignKey("SID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SOCUser");

                    b.Navigation("trRole");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.SOCUser", b =>
                {
                    b.Navigation("SOCUserTanent");

                    b.Navigation("trRoleSOCUser");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("tenantMembers");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.mtPrivilege", b =>
                {
                    b.Navigation("mtPrivilegeItems");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.taMember", b =>
                {
                    b.Navigation("tenantMembers");

                    b.Navigation("trRoleMembers");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trRole", b =>
                {
                    b.Navigation("trRoleMembers");

                    b.Navigation("trRolePrivilagesItem");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trSubtask", b =>
                {
                    b.Navigation("trSubtaskAction");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Entities.trTask", b =>
                {
                    b.Navigation("trTaskSubtask");
                });

            modelBuilder.Entity("TCCTOBK.OperationBackend.Domain.Location", b =>
                {
                    b.Navigation("SpotCoordinate");

                    b.Navigation("Unit");
                });
#pragma warning restore 612, 618
        }
    }
}
