name: Deploy

on:
  push:
    branches:
      - uat
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ${{ vars.REPOSITORY_URL }}
      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ${{ vars.REPOSITORY_URL }}:latest
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: ${{ vars.REPOSITORY_URL }}/cache
          context: app
          file: app/Dockerfile.${{ github.ref_name }}
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/
      - name: Set Environment
        uses: nowactions/envsubst@v1
        with:
          input: ./k8s/${{ github.ref_name }}/gen
          output: ./k8s/${{ github.ref_name }}/kustomization.yaml
        env:
          REPOSITORY_URL: ${{ vars.REPOSITORY_URL }}
      - name: Config Kustomize
        run: |
          cd ./k8s/$GITHUB_REF_NAME
          kustomize edit add annotation "deploy-timestamp":$(date +%s) -f
          kustomize edit set image ${{ vars.REPOSITORY_URL }}:latest
          kustomize build
      - name: Deploy to ArgoCD
        run: |
          cd ./k8s/$GITHUB_REF_NAME
          git config --global user.email "github@github.com"
          git config --global user.name "Github CI/CD"
          git status
          git add kustomization.yaml
          git commit -m "[skip ci] deploy argoCD"
          git push --no-verify
