######## Ob iam ########
ob_iam_request_otp_url: /otp/request
ob_iam_validate_otp_url: /otp/verify
ob_iam_login_url: /login
ob_iam_link_external_identity_url: /external_identity/link
ob_iam_register_url: /auth/register
ob_iam_signin_url: /auth/login
ob_iam_identity_url: /identity
ob_iam_setting_url: /me/setting
ob_iam_account: /me/account
ob_iam_reactivate_url: /auth/reactivate
ob_iam_reset_password_url: /me/account/reset_password
