namespace TCCTOBK.OperationBackend.Application;

public class PPMModel
{
  public int? id { get; set; }
  public string? name { get; set; }
  public int? cwoTypeId { get; set; }
  public int? problemTypeId { get; set; }
  public int? priorityId { get; set; }
  public int? serviceCategoryId { get; set; }
  public int? locationId { get; set; }
  public string? description { get; set; }
  public string? createdBy { get; set; }
  public DateTime? createdOn { get; set; }
  public string? modifiedBy { get; set; }
  public DateTime? modifiedOn { get; set; }
  public int? requesterId { get; set; }
  public DateTime? requestedOn { get; set; }
  public bool? isActive { get; set; }
  public int? statusId { get; set; }
  public int? assetId { get; set; }
  public DateTime? ackedOn { get; set; }
  public string? ackedBy { get; set; }
  public DateTime? slaStartDateTime { get; set; }
  public DateTime? slatoResolve { get; set; }
  public DateTime? slatoRespond { get; set; }
  public int? estimatedTotalDuration { get; set; }
  public DateTime? estimatedCompletion { get; set; }
  public string? supervisorId { get; set; }
  public DateTime? supervisorAssignedOn { get; set; }
  public string? supervisorAssignedBy { get; set; }
  public string? technicianId { get; set; }
  public DateTime? technicianAssignedOn { get; set; }
  public string? technicianAssignedBy { get; set; }
  public string? operatorNote { get; set; }
  public DateTime? actualStartDateTime { get; set; }
  public DateTime? actualCompletionDateTime { get; set; }
  public string? completedBy { get; set; }
  public DateTime? closedOn { get; set; }
  public string? closedBy { get; set; }
  public bool? isTaskCompletionConfirmed { get; set; }
  public string? taskCompletionConfirmedBy { get; set; }
  public DateTime? taskCompletionConfirmedOn { get; set; }
  public bool? isCancelled { get; set; }
  public int? serviceProviderId { get; set; }
  public string? completionComment { get; set; }
  public string? closureComment { get; set; }
  public int? slaTriggerPoint { get; set; }
  public bool? isReworkRequested { get; set; }
  public string? reworkRequestedBy { get; set; }
  public DateTime? reworkRequestedOn { get; set; }
  public string? reasonToRework { get; set; }
  public bool? isPrevSupervisorRejected { get; set; }
  public string? prevRejectedSupervisorId { get; set; }
  public bool? isPrevTechnicianRejected { get; set; }
  public string? prevRejectedTechnicianId { get; set; }
  public string? acknowledgementVerifiedBy { get; set; }
  public string? completionAckedBy { get; set; }
  public string? completionVerifiedBy { get; set; }
  public string? clientVerificationSubmittedBy { get; set; }
  public DateTime? clientVerificationSubmittedOn { get; set; }
  public string? clientVerificationComment { get; set; }
  public string? clientVerifiedUser { get; set; }
  public bool? isWorkingOffline { get; set; }
  public DateTime? workOfflineOn { get; set; }
  public string? workOfflineBy { get; set; }
  public bool? isPaused { get; set; }
  public string? pausedBy { get; set; }
  public DateTime? pausedOn { get; set; }
  public string? pausedReason { get; set; }
  public string? resumedBy { get; set; }
  public DateTime? resumedOn { get; set; }
  public string? acknowledgementSignature { get; set; }
  public string? completionSignature { get; set; }
  public string? closureSignature { get; set; }
  public string? clientVerificationSignature { get; set; }
  public bool? isSynced { get; set; }
  public int? parentId { get; set; }
}