export const EMAIL_TEMPLATE: Record<string, string> = {
  'ob-iam.identity.email_added': 'new-email-added.html',
  'ob-iam.identity.email_default_set': 'new-email-default.html',
  'ob-iam.identity.phone_added': 'new-phone-added.html',
  'ob-iam.identity.phone_default_set': 'new-phone-default.html',
  'ob-iam.account.password_reset': 'password-reset.html',
  'ob-iam.account.password_set': 'password-set.html',
  'ob-iam.account.deleted': 'account-deleted.html',
  'ob-iam.account.reactivated': 'account-reactivated.html',
  'ob-iam.device.added': 'device-added.html',
  'ob-iam.setting.2fa_activated': '2fa-activated.html',
  'ob-iam.setting.2fa_deactivated': '2fa-deactivated.html',
  'ob-bms.visitor.visited': 'visitor.visited.html',
  'ob-bms.service_request_status.updated': 'service-request-update.html',
  'ob-bms.air_condition_status.updated': 'air-conditioner-request-update.html',
  'ob-iam.otp_reference.created': 'otp-reference-created.html',
  'ob-bms.service_request.created': 'service-request-created.html',
  'ob-bms.air_condition_request.created': 'air-conditioner-request-created.html',
  'ob-bms.visitor_pass.created': 'visitor-pass-created.html',
  'ob-bms.visitor_resident_pass.created': 'visitor-resident-pass-created.html',
  'ob-bms.visitor_resident_vehicle_checkout.created': 'visitor-resident-vehicle-checkout.html',
  'ob-bms.art_c_booking.confirmed': 'art-c-booking-confirm.html',
};
