apiVersion: apps/v1
kind: Deployment
metadata:
  name: ob-document
spec:
  selector:
    matchLabels:
      name: ob-document
  template:
    metadata:
      labels:
        name: ob-document
    spec:
      containers:
      - name: ob-document
        image: 418772626632.dkr.ecr.ap-southeast-1.amazonaws.com/one-bangkok-dev:ob-document_latest
        ports:
          - containerPort: 3000
        imagePullPolicy: Always
        env:
          - name: DATABASE_URL
            value: postgresql://postgres:2a843c492f23fdbd6d586d0911d275fc@ob-document-dev.caktmhpgapyr.ap-southeast-1.rds.amazonaws.com/ob_document_development

