using TCCTOBK.OperationBackend.Application.Configuration.Queries;

namespace TCCTOBK.OperationBackend.Application.Features.Mobile.MasterData.Query.FMRelatedServiceCategoryServingLocation;
public class FMRelatedServiceCategoryServingLocationQuery : IQuery<FMRelatedServiceCategoryServingLocationResult>
{
}
