apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-home-auto
  namespace: obk-production
spec:
  schedule: "0 3,6,9,12,15,18,21 * * *"
  timeZone: "Asia/Bangkok"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-script
            image: curlimages/curl:latest
            command: ["sh", "-c"]
            args:
              - |
                curl --location 'http://obk-tcct-serviceabstraction-production.obk-production.svc.prd-obk-services.local/api/v1/netatmo/sync-home' --header 'Content-Type: application/json' --data '{}'
          restartPolicy: OnFailure