apiVersion: v1
kind: Service
metadata:
  name: {{PROJECT-NAME}}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: https
    port: 443
    targetPort: 3000
  selector:
    name: {{PROJECT-NAME}}
