services:
  web:
    image: registry.lab.tcctech.app/obk/obk-parking-payment/trunk:latest
    environment:
      OBK_API_URL: 
      OBK_API_CLIENT_ID: 
      OBK_API_CLIENT_SECRET: 
    ports:
      - "6000:3000"
    restart: always
    networks:
      - webnet

networks:
  webnet:
    driver: bridge