include:
  - project: iac/pipeline
    file:
      - pipeline-env.yaml
      # - tpl.yaml
  - project: iac/projects/obk/opapp-dev
    file: project-env.yaml
    rules:
      - if: $CI_COMMIT_TAG =~ /^.*-dev/ 
  - project: iac/projects/obk/opapp-sit
    file: project-env.yaml
    rules:
      - if: $CI_COMMIT_TAG =~ /^.*-sit/ 
  - project: iac/projects/obk/opapp-uat
    file: project-env.yaml
    rules:
      - if: $CI_COMMIT_TAG =~ /^.*-uat/ 
  - project: iac/projects/obk/production
    file: project-env.yaml
    rules:
      - if: $CI_COMMIT_TAG =~ /^.*-prod/ 

  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml
  # - template: Jobs/Dependency-Scanning.gitlab-ci.yml

default: # Default runner for all job
  tags:
    - obk-np-opapp

sast:
  stage: pre-build
code_quality:
  stage: pre-build
secret_detection:
  stage: pre-build
iac-sast:
  stage: pre-build

container_scanning:
  stage: post-build
  extends:
    - .project_env 
  variables:
    GIT_STRATEGY: fetch
    CS_DOCKERFILE_PATH: "Dockerfile"
    CS_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}"
    CS_REGISTRY_USER: "${CI_REGISTRY_USER}"
    CS_REGISTRY_PASSWORD: "${CI_REGISTRY_PASS}"
    # SECURE_LOG_LEVEL: debug
  allow_failure: false
  rules:
  - if: $CI_COMMIT_TAG =~ /^.*-dev/ 
  - if: $CI_COMMIT_TAG =~ /^.*-sit/ 
  - if: $CI_COMMIT_TAG =~ /^.*-uat/ 
  - if: $CI_COMMIT_TAG =~ /^.*-prod/ 

variables:
  SERVICE_PORT: 80
  # FQDN_DEV: dev-.tccproptech.com
  # FQDN_SIT: sit-.tccproptech.com
  # FQDN_UAT: uat-.tccproptech.com
  # FQDN_PROD: .tccproptech.com

  FQDN1_DEV: dev-obk-operation.tccproptech.com
  FQDN2_DEV: dev-obk-cms.tccproptech.com
  FQDN3_DEV: dev-obk-gateway.tccproptech.com

  FQDN1_SIT: sit-obk-operation.tccproptech.com
  FQDN2_SIT: sit-obk-cms.tccproptech.com
  FQDN3_SIT: sit-obk-gateway.tccproptech.com

  FQDN1_UAT: uat-obk-operation.tccproptech.com
  FQDN2_UAT: uat-obk-cms.tccproptech.com
  FQDN3_UAT: uat-obk-gateway.tccproptech.com

  # Custom for production
  FQDN1_PROD: obkoperation.tccproptech.com
  FQDN2_PROD: obkcms.tccproptech.com
  FQDN3_PROD: obkgateway.tccproptech.com

stages:
  - pre-build
  - build
  - post-build
  - deploy

.build_tpl:
  stage: build
  image: docker
  allow_failure: false     
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "${DOCKER_TLS_CERTDIR}/client"
  services:
    - name: docker:20.10.16-dind
  before_script:
    - until docker info; do sleep 1; done 
  script:   
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASS} ${CI_REGISTRY}
    - docker build --pull --compress --network host -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA} ${SERVICE_BUILD_ARG} .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}
    - docker logout

.deploy_tpl:
  allow_failure: false     
  dependencies:
    - container_scanning
  stage: deploy
  image: alpine/k8s:1.24.15
  script:
    - |
      kubectl version --output=yaml;
      kubectl config set-cluster k8s --server=$K8S_API_URL --insecure-skip-tls-verify=true;
      kubectl config set-credentials k8s --token=$K8S_API_TOKEN;
      kubectl config set-context k8s --cluster k8s --user k8s --namespace=$K8S_NAMESPACE;
    - kubectl config use-context k8s
    - cat k8s.yml | envsubst | kubectl apply -f -              

.project_env:
  when: always

build_dev:
  extends:
    - .pipeline_obk_np_opapp                               
    - .project_env     
    - .build_tpl
  environment:
    name: dev
  variables:
    SERVICE_BUILD_ARG: "--build-arg SERVICE_PORT=${SERVICE_PORT} --build-arg GIT_COMMIT_HASH=${CI_COMMIT_SHA}"
  rules:
    - if: $CI_COMMIT_TAG =~ /^.*-dev/ 

deploy_dev:
  variables:
    # FQDN: ${FQDN_DEV}
    FQDN1: ${FQDN1_DEV}
    FQDN2: ${FQDN2_DEV}
    FQDN3: ${FQDN3_DEV}
  dependencies:
    - build_dev
  extends:
    - .pipeline_obk_np_opapp                              
    - .project_env 
    - .deploy_tpl                     
  environment:
    name: dev 
  rules:
    - if: $CI_COMMIT_TAG =~ /^.*-dev/ 

build_sit:
  extends:
    - .pipeline_obk_np_opapp                               
    - .project_env  
    - .build_tpl
  variables:
    SERVICE_BUILD_ARG: "--build-arg SERVICE_PORT=${SERVICE_PORT} --build-arg GIT_COMMIT_HASH=${CI_COMMIT_SHA}"
  environment:
    name: sit
  rules:
    - if: $CI_COMMIT_TAG =~ /^.*-sit/ 

deploy_sit:
  variables:
    # FQDN: ${FQDN_SIT}
    FQDN1: ${FQDN1_SIT}
    FQDN2: ${FQDN2_SIT}
    FQDN3: ${FQDN3_SIT}
  dependencies:
    - build_sit
  extends:
    - .pipeline_obk_np_opapp                               
    - .project_env 
    - .deploy_tpl    
  environment:
    name: sit                 
  rules:
    - if: $CI_COMMIT_TAG =~ /^.*-sit/ 

build_uat:
  extends:
    - .pipeline_obk_np_opapp                               
    - .project_env     
    - .build_tpl
  variables:
    SERVICE_BUILD_ARG: "--build-arg SERVICE_PORT=${SERVICE_PORT} --build-arg GIT_COMMIT_HASH=${CI_COMMIT_SHA}"
  environment:
    name: uat
  rules:
    - if: $CI_COMMIT_TAG =~ /^.*-uat/ 

deploy_uat:
  variables:
    # FQDN: ${FQDN_UAT}
    FQDN1: ${FQDN1_UAT}
    FQDN2: ${FQDN2_UAT}
    FQDN3: ${FQDN3_UAT}
  dependencies:
    - build_uat
  extends:
    - .pipeline_obk_np_opapp                             
    - .project_env
    - .deploy_tpl
  environment:
    name: uat
  rules:
    - if: $CI_COMMIT_TAG =~ /^.*-uat/ 

build_prod:
  extends:
    - .pipeline_sandbox_obk                        
    - .project_env     
    - .build_tpl
  variables:
    SERVICE_BUILD_ARG: "--build-arg SERVICE_PORT=${SERVICE_PORT} --build-arg GIT_COMMIT_HASH=${CI_COMMIT_SHA}"
  environment:
    name: production
  rules:
    - if: $CI_COMMIT_TAG =~ /^.*-prod/ 

deploy_prod:
  variables:
    # FQDN: ${FQDN_PROD}
    FQDN1: ${FQDN1_PROD}
    FQDN2: ${FQDN2_PROD}
    FQDN3: ${FQDN3_PROD}
  dependencies:
    - build_prod
  extends:
    - .pipeline_sandbox_obk                             
    - .project_env
    - .deploy_tpl
  environment:
    name: production
  rules:
    - if: $CI_COMMIT_TAG =~ /^.*-prod/ 
      when: manual
