apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base


configMapGenerator:
- literals:
  - NODE_ENV=production
  name: configmap

patches:
- patch: |-
    - op: replace
      path: /spec/source/repoURL
      value: https://github.com/mtel-thailand/ob-cms
    - op: replace
      path: /spec/source/targetRevision
      value: uat
    - op: replace
      path: /spec/source/path
      value: k8s/uat
  target:
    kind: Application